using {/UnrealEngine.com/Abilities}
# Module import path: /Fortnite.com/Itemization/AbsoluteDoomItems
AbsoluteDoomItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_chainsaw<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/AbsoluteDoomItems:)item_dual_micro_smgs_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/AbsoluteDoomItems:)item_dual_micro_smgs_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/AbsoluteDoomItems:)item_dual_micro_smgs_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/AbsoluteDoomItems:)item_dual_micro_smgs_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/AbsoluteDoomItems:)item_dual_micro_smgs_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_monarch_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_monarch_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_monarch_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_monarch_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_monarch_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_sovereign_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_sovereign_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_sovereign_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_sovereign_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_sovereign_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_striker_burst_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_striker_burst_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_striker_burst_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_striker_burst_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_striker_burst_rifle_uncommon<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/BallisticItems
BallisticItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_bubble_shield<public> := class<final><concrete>(entity):


    @experimental
    item_burst_ar_common<public> := class<final><concrete>(entity):


    @experimental
    item_drum_gun_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/BallisticItems:)item_enforcer_ar_common<public> := class<final><concrete>(entity):


    @experimental
    item_fire_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_flashbang<public> := class<final><concrete>(entity):


    @experimental
    item_frag_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_frenzy_auto_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_hammer_pump_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_hand_cannon_common<public> := class<final><concrete>(entity):


    @experimental
    item_hyper_smg_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/BallisticItems:)item_impulse_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_machine_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_nemesis_ar_common<public> := class<final><concrete>(entity):


    @experimental
    item_overdrive<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/BallisticItems:)item_proximity_mine<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_reaper_sniper_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_recon_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_rift_point_device<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/BallisticItems:)item_smoke_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_sovereign_sniper_common<public> := class<final><concrete>(entity):


    @experimental
    item_striker_ar_common<public> := class<final><concrete>(entity):


    @experimental
    item_thunder_burst_smg_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/BallisticItems:)item_veiled_precision_smg_common<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH1S1Items
CH1S1Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_bush<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S1Items:)item_pumpkin_launcher_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S1Items:)item_pumpkin_launcher_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S1Items:)item_pumpkin_launcher_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S1Items:)item_slurp_juice<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S1Items:)item_smoke_grenade<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH1S2Items
CH1S2Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_boogie_bomb<public> := class<final><concrete>(entity):


    @experimental
    item_cozy_campfire<public> := class<final><concrete>(entity):


    @experimental
    item_crossbow_epic<public> := class<final><concrete>(entity):


    @experimental
    item_crossbow_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S2Items:)item_impulse_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_legacy_chug_jug<public> := class<final><concrete>(entity):


    @experimental
    item_legacy_small_shield_potion<public> := class<final><concrete>(entity):


    @experimental
    item_minigun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_minigun_legendary<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH1S3Items
CH1S3Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_clinger<public> := class<final><concrete>(entity):


    @experimental
    item_egg_launcher_epic<public> := class<final><concrete>(entity):


    @experimental
    item_egg_launcher_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_egg_launcher_rare<public> := class<final><concrete>(entity):


    @experimental
    item_hand_cannon_epic<public> := class<final><concrete>(entity):


    @experimental
    item_hand_cannon_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S3Items:)item_hunting_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S3Items:)item_hunting_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_light_machine_gun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_light_machine_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_port_a_fort<public> := class<final><concrete>(entity):


    @experimental
    item_remote_explosives<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH1S4Items
CH1S4Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_apple<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S4Items:)item_burst_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S4Items:)item_burst_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_drum_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_drum_gun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_dual_pistols_epic<public> := class<final><concrete>(entity):


    @experimental
    item_dual_pistols_rare<public> := class<final><concrete>(entity):


    @experimental
    item_jetpack<public> := class<final><concrete>(entity):


    @experimental
    item_shield_mushroom<public> := class<final><concrete>(entity):


    @experimental
    item_stink_bomb<public> := class<final><concrete>(entity):


    @experimental
    item_thermal_scoped_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_thermal_scoped_assault_rifle_legendary<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH1S5Items
CH1S5Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_compact_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_compact_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_double_barrel_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_double_barrel_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_grappler<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_sniper_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_sniper_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_port_a_fortress<public> := class<final><concrete>(entity):


    @experimental
    item_rift_to_go<public> := class<final><concrete>(entity):


    @experimental
    item_shockwave_grenade<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S5Items:)item_submachine_gun_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S5Items:)item_submachine_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S5Items:)item_submachine_gun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_assault_rifle_legendary<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH1S6Items
CH1S6Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_balloons<public> := class<final><concrete>(entity):


    @experimental
    item_dynamite<public> := class<final><concrete>(entity):


    @experimental
    item_fiend_hunter_crossbow_epic<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S6Items:)item_pump_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S6Items:)item_pump_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_quad_launcher_epic<public> := class<final><concrete>(entity):


    @experimental
    item_quad_launcher_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_six_shooter_epic<public> := class<final><concrete>(entity):


    @experimental
    item_six_shooter_rare<public> := class<final><concrete>(entity):


    @experimental
    item_six_shooter_uncommon<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH1S7Items
CH1S7Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_boom_box<public> := class<final><concrete>(entity):


    @experimental
    item_bottle_rockets<public> := class<final><concrete>(entity):


    @experimental
    item_chiller_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_cupids_crossbow_epic<public> := class<final><concrete>(entity):


    @experimental
    item_gliders<public> := class<final><concrete>(entity):


    @experimental
    item_infantry_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_infantry_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_infantry_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_infinity_blade<public> := class<final><concrete>(entity):


    @experimental
    item_presents<public> := class<final><concrete>(entity):


    @experimental
    item_scoped_revolver_epic<public> := class<final><concrete>(entity):


    @experimental
    item_scoped_revolver_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_sneaky_snowman<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_sniper_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_sniper_rifle_legendary<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH1S8Items
CH1S8Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_banana<public> := class<final><concrete>(entity):


    @experimental
    item_boom_bow_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_coconut<public> := class<final><concrete>(entity):


    @experimental
    item_flint_knock_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_flint_knock_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S8Items:)item_infantry_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S8Items:)item_infantry_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_jewel<public> := class<final><concrete>(entity):


    @experimental
    item_pepper<public> := class<final><concrete>(entity):


    @experimental
    item_poison_dart_trap<public> := class<final><concrete>(entity):


    @experimental
    item_shadow_bomb<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH1S9Items
CH1S9Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_air_strike<public> := class<final><concrete>(entity):


    @experimental
    item_burst_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_burst_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_burst_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_chug_splash<public> := class<final><concrete>(entity):


    @experimental
    item_combat_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_combat_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_combat_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_drum_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_drum_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_drum_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_flag<public> := class<final><concrete>(entity):


    @experimental
    item_proximity_grenade_launcher_epic<public> := class<final><concrete>(entity):


    @experimental
    item_proximity_grenade_launcher_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S9Items:)item_revolver_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1S9Items:)item_revolver_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_storm_flip<public> := class<final><concrete>(entity):


    @experimental
    item_storm_scout_sniper_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_storm_scout_sniper_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_assault_rifle_rare<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH1SXItems
CH1SXItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_automatic_sniper_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_automatic_sniper_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_automatic_sniper_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_automatic_sniper_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_flashlight<public> := class<final><concrete>(entity):


    @experimental
    item_flashlight_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_junk_rift<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH1SXItems:)item_pump_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_shield_bubble<public> := class<final><concrete>(entity):


    @experimental
    item_torch<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH2S1Items
CH2S1Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_bandage_bazooka<public> := class<final><concrete>(entity):


    @experimental
    item_flopper<public> := class<final><concrete>(entity):


    @experimental
    item_gold<public> := class<final><concrete>(entity):


    @experimental
    item_harpoon_gun<public> := class<final><concrete>(entity):


    @experimental
    item_lump_of_coal<public> := class<final><concrete>(entity):


    @experimental
    item_mythic_goldfish<public> := class<final><concrete>(entity):


    @experimental
    item_pumpkin_launcher_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_rusty_can<public> := class<final><concrete>(entity):


    @experimental
    item_slurp_mushroom<public> := class<final><concrete>(entity):


    @experimental
    item_slurpfish<public> := class<final><concrete>(entity):


    @experimental
    item_small_fry<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH2S2Items
CH2S2Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_authority_keycard<public> := class<final><concrete>(entity):


    @experimental
    item_brutus_minigun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_crash_pad<public> := class<final><concrete>(entity):


    @experimental
    item_creepin_cardboard<public> := class<final><concrete>(entity):


    @experimental
    item_decoy<public> := class<final><concrete>(entity):


    @experimental
    item_grotto_keycard<public> := class<final><concrete>(entity):


    @experimental
    item_hand_cannon_rare<public> := class<final><concrete>(entity):


    @experimental
    item_meowscles_peow_peow_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_midas_drum_gun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_orange_paint_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_orange_paint_launcher_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH2S2Items:)item_proximity_mine<public> := class<final><concrete>(entity):


    @experimental
    item_purple_paint_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_purple_paint_launcher_rare<public> := class<final><concrete>(entity):


    @experimental
    item_rapid_fire_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_rapid_fire_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_rapid_fire_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_rapid_fire_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_rapid_fire_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_rig_keycard<public> := class<final><concrete>(entity):


    @experimental
    item_shark_keycard<public> := class<final><concrete>(entity):


    @experimental
    item_skyes_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_skyes_grappler<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_sniper_rifle_rare<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH2S3Items
CH2S3Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_cabbage<public> := class<final><concrete>(entity):


    @experimental
    item_catty_corner_keycard<public> := class<final><concrete>(entity):


    @experimental
    item_charge_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_charge_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_charge_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_charge_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_charge_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_corn<public> := class<final><concrete>(entity):


    @experimental
    item_firefly_jar<public> := class<final><concrete>(entity):


    @experimental
    item_flare_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_fortilla_keycard<public> := class<final><concrete>(entity):


    @experimental
    item_gas_can<public> := class<final><concrete>(entity):


    @experimental
    item_hunting_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_hunting_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_jules_drum_gun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_jules_glider_gun<public> := class<final><concrete>(entity):


    @experimental
    item_kits_charge_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_kits_shockwave_launcher_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_oceans_bottomless_chug_jug<public> := class<final><concrete>(entity):


    @experimental
    item_oceans_burst_assault_rifle_mythic<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH2S4Items
CH2S4Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_candy_corn<public> := class<final><concrete>(entity):


    @experimental
    item_fire_trap<public> := class<final><concrete>(entity):


    @experimental
    item_hop_drop<public> := class<final><concrete>(entity):


    @experimental
    item_hop_flopper<public> := class<final><concrete>(entity):


    @experimental
    item_jelly_bean<public> := class<final><concrete>(entity):


    @experimental
    item_jellyfish<public> := class<final><concrete>(entity):


    @experimental
    item_midas_flopper<public> := class<final><concrete>(entity):


    @experimental
    item_pepper_mint<public> := class<final><concrete>(entity):


    @experimental
    item_shadow_midas_drum_gun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_shield_fish<public> := class<final><concrete>(entity):


    @experimental
    item_spicy_fish<public> := class<final><concrete>(entity):


    @experimental
    item_thermal_fish<public> := class<final><concrete>(entity):


    @experimental
    item_thermal_taffy<public> := class<final><concrete>(entity):


    @experimental
    item_vendetta_flopper<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH2S5Items
CH2S5Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_boom_sniper_rifle_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_burst_quad_launcher_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_chug_cannon<public> := class<final><concrete>(entity):


    @experimental
    item_dragons_breath_sniper_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_holiday_presents<public> := class<final><concrete>(entity):


    @experimental
    item_hop_rock_dualies_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_legacy_dragons_breath_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_legacy_dragons_breath_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_lever_action_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_lever_action_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_lever_action_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_lever_action_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_lever_action_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_lever_action_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_lever_action_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_lever_action_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_lever_action_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_night_hawk_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_rift_fish<public> := class<final><concrete>(entity):


    @experimental
    item_shadow_tracker_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_snowy_flopper<public> := class<final><concrete>(entity):


    @experimental
    item_storm_scout_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_the_big_chill_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_the_dub_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_zero_point_fish<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH4S1Items
CH4S1Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_big_bush_bomb<public> := class<final><concrete>(entity):


    @experimental
    item_ex_caliber_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_ex_caliber_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_ex_caliber_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_ex_caliber_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_ex_caliber_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_falcon_scout<public> := class<final><concrete>(entity):


    @experimental
    item_guardian_shield<public> := class<final><concrete>(entity):


    @experimental
    item_heisted_accelerant_shotgun_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_heisted_blink_mag_smg_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_heisted_breacher_shotgun_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_heisted_explosive_assault_rifle_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_heisted_run_n_gun_smg_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_maven_auto_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_maven_auto_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_maven_auto_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_maven_auto_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_maven_auto_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_red_eye_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_red_eye_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_red_eye_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_red_eye_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_red_eye_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_shockwave_hammer_epic<public> := class<final><concrete>(entity):


    @experimental
    item_slap_berry<public> := class<final><concrete>(entity):


    @experimental
    item_slap_juice<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH4S1Items:)item_tactical_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH4S1Items:)item_tactical_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH4S1Items:)item_tactical_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH4S1Items:)item_tactical_pistol_mythic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH4S1Items:)item_tactical_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH4S1Items:)item_tactical_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_the_ageless_champions_ex_caliber_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_the_ageless_champions_shockwave_hammer_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_thunder_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_thunder_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_thunder_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_thunder_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_thunder_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_twin_mag_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_twin_mag_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_twin_mag_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_twin_mag_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_twin_mag_smg_uncommon<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH6MS2Items
CH6MS2Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_compact_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_compact_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_compact_smg_mythic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH6MS2Items:)item_infantry_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH6MS2Items:)item_infantry_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH6MS2Items:)item_tactical_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH6MS2Items:)item_tactical_shotgun_legendary<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CH7S1Items
CH7S1Items<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_arc_lightning_gun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_arc_lightning_gun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_brutus_twin_hammer_shotguns_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_deadeye_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_deadeye_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_deadeye_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_deadeye_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_deadeye_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_dual_micro_smgs_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_dual_micro_smgs_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_dual_micro_smgs_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_dual_micro_smgs_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_dual_micro_smgs_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_enforcer_ar_common<public> := class<final><concrete>(entity):


    @experimental
    item_enforcer_ar_epic<public> := class<final><concrete>(entity):


    @experimental
    item_enforcer_ar_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_enforcer_ar_rare<public> := class<final><concrete>(entity):


    @experimental
    item_enforcer_ar_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_holo_rush_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_holo_rush_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_holo_rush_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_holo_rush_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_holo_rush_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_human_bills_arc_lightning_gun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_hushs_deadeye_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_iron_pump_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_iron_pump_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_iron_pump_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_iron_pump_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_iron_pump_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_tactical_pistol_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_pinpoint_iron_pump_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_six_shooter_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_tactical_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_tactical_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_tactical_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_tactical_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/CH7S1Items:)item_tactical_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_twin_hammer_shotguns_common<public> := class<final><concrete>(entity):


    @experimental
    item_twin_hammer_shotguns_epic<public> := class<final><concrete>(entity):


    @experimental
    item_twin_hammer_shotguns_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_twin_hammer_shotguns_rare<public> := class<final><concrete>(entity):


    @experimental
    item_twin_hammer_shotguns_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_vengeful_sniper_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_vengeful_sniper_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_vengeful_sniper_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_vengeful_sniper_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_wingsuit<public> := class<final><concrete>(entity):


    @experimental
    item_yule_troopers_holo_rush_smg_mythic<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CreativeItems
CreativeItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_acorn<public> := class<final><concrete>(entity):


    @experimental
    item_active_powercell<public> := class<final><concrete>(entity):


    @experimental
    item_adhesive_resin<public> := class<final><concrete>(entity):


    @experimental
    item_bacon<public> := class<final><concrete>(entity):


    @experimental
    item_basic_hammer_common<public> := class<final><concrete>(entity):


    @experimental
    item_basic_sword_common<public> := class<final><concrete>(entity):


    @experimental
    item_batteries<public> := class<final><concrete>(entity):


    @experimental
    item_blast_powder<public> := class<final><concrete>(entity):


    @experimental
    item_blue_flecked_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_blue_mushroom<public> := class<final><concrete>(entity):


    @experimental
    item_blue_shimmering_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_blue_speckled_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_boar_hair<public> := class<final><concrete>(entity):


    @experimental
    item_bouncer<public> := class<final><concrete>(entity):


    @experimental
    item_brightcore_ore<public> := class<final><concrete>(entity):


    @experimental
    item_brown_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_brown_speckled_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_butter<public> := class<final><concrete>(entity):


    @experimental
    item_carved_twine<public> := class<final><concrete>(entity):


    @experimental
    item_char_black_mineral_powder<public> := class<final><concrete>(entity):


    @experimental
    item_chiller<public> := class<final><concrete>(entity):


    @experimental
    item_coal<public> := class<final><concrete>(entity):


    @experimental
    item_copper_ore<public> := class<final><concrete>(entity):


    @experimental
    item_creative_fishing_rod<public> := class<final><concrete>(entity):


    @experimental
    item_creative_pro_fishing_rod<public> := class<final><concrete>(entity):


    @experimental
    item_damage_trap<public> := class<final><concrete>(entity):


    @experimental
    item_diamond<public> := class<final><concrete>(entity):


    @experimental
    item_duct_tape<public> := class<final><concrete>(entity):


    @experimental
    item_efficient_mechanical_parts<public> := class<final><concrete>(entity):


    @experimental
    item_fibrous_herbs<public> := class<final><concrete>(entity):


    @experimental
    item_fine_grain_mineral_powder<public> := class<final><concrete>(entity):


    @experimental
    item_flower_petals<public> := class<final><concrete>(entity):


    @experimental
    item_gray_eruption_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_green_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_green_flecked_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_green_marbled_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_grub<public> := class<final><concrete>(entity):


    @experimental
    item_herb<public> := class<final><concrete>(entity):


    @experimental
    item_honey<public> := class<final><concrete>(entity):


    @experimental
    item_lemon_lime<public> := class<final><concrete>(entity):


    @experimental
    item_malachite_ore<public> := class<final><concrete>(entity):


    @experimental
    item_maple_syrup<public> := class<final><concrete>(entity):


    @experimental
    item_milk<public> := class<final><concrete>(entity):


    @experimental
    item_obsidian_ore<public> := class<final><concrete>(entity):


    @experimental
    item_oxidized_mineral_powder<public> := class<final><concrete>(entity):


    @experimental
    item_patchwork_tool<public> := class<final><concrete>(entity):


    @experimental
    item_peaky_twine<public> := class<final><concrete>(entity):


    @experimental
    item_pink_marbled_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_pink_mushroom<public> := class<final><concrete>(entity):


    @experimental
    item_planks<public> := class<final><concrete>(entity):


    @experimental
    item_prop_o_matic<public> := class<final><concrete>(entity):


    @experimental
    item_pumpkin<public> := class<final><concrete>(entity):


    @experimental
    item_quartz_crystal<public> := class<final><concrete>(entity):


    @experimental
    item_rainbow_crystal<public> := class<final><concrete>(entity):


    @experimental
    item_raptor_eye<public> := class<final><concrete>(entity):


    @experimental
    item_red_eruption_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_red_flecked_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_red_mushroom<public> := class<final><concrete>(entity):


    @experimental
    item_red_shimmering_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_roasted_chicken<public> := class<final><concrete>(entity):


    @experimental
    item_rotating_gizmo<public> := class<final><concrete>(entity):


    @experimental
    item_rough_mineral_powder<public> := class<final><concrete>(entity):


    @experimental
    item_rough_ore<public> := class<final><concrete>(entity):


    @experimental
    item_rusty_mechanical_parts<public> := class<final><concrete>(entity):


    @experimental
    item_shadowshard_crystal<public> := class<final><concrete>(entity):


    @experimental
    item_shark_tooth<public> := class<final><concrete>(entity):


    @experimental
    item_shove<public> := class<final><concrete>(entity):


    @experimental
    item_signal_remote<public> := class<final><concrete>(entity):


    @experimental
    item_signal_remote_a<public> := class<final><concrete>(entity):


    @experimental
    item_signal_remote_b<public> := class<final><concrete>(entity):


    @experimental
    item_signal_remote_c<public> := class<final><concrete>(entity):


    @experimental
    item_signal_remote_d<public> := class<final><concrete>(entity):


    @experimental
    item_silver_ore<public> := class<final><concrete>(entity):


    @experimental
    item_simple_mechanical_parts<public> := class<final><concrete>(entity):


    @experimental
    item_simple_mineral_powder<public> := class<final><concrete>(entity):


    @experimental
    item_simple_twine<public> := class<final><concrete>(entity):


    @experimental
    item_sleek_mechanical_parts<public> := class<final><concrete>(entity):


    @experimental
    item_spectral_twine<public> := class<final><concrete>(entity):


    @experimental
    item_spectrolite_ore<public> := class<final><concrete>(entity):


    @experimental
    item_speed_boost<public> := class<final><concrete>(entity):


    @experimental
    item_speed_boost_high<public> := class<final><concrete>(entity):


    @experimental
    item_speed_boost_low<public> := class<final><concrete>(entity):


    @experimental
    item_stringy_twine<public> := class<final><concrete>(entity):


    @experimental
    item_sturdy_mechanical_parts<public> := class<final><concrete>(entity):


    @experimental
    item_sturdy_twine<public> := class<final><concrete>(entity):


    @experimental
    item_sunbeam_crystal<public> := class<final><concrete>(entity):


    @experimental
    item_vindertech_mechanical_parts<public> := class<final><concrete>(entity):


    @experimental
    item_wheat<public> := class<final><concrete>(entity):


    @experimental
    item_white_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_white_marbled_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_white_mushroom<public> := class<final><concrete>(entity):


    @experimental
    item_white_shimmering_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_white_speckled_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_wolf_tooth<public> := class<final><concrete>(entity):


    @experimental
    item_yellow_eruption_dino_egg<public> := class<final><concrete>(entity):


    @experimental
    item_yellow_mushroom<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/CubedItems
CubedItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_armored_wall<public> := class<final><concrete>(entity):


    @experimental
    item_chili_chug_splash<public> := class<final><concrete>(entity):


    @experimental
    item_combat_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_combat_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_combat_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_combat_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_combat_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_combat_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_combat_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    item_combat_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_combat_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_combat_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_combat_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_dual_fiend_hunters_common<public> := class<final><concrete>(entity):


    @experimental
    item_dual_fiend_hunters_epic<public> := class<final><concrete>(entity):


    @experimental
    item_dual_fiend_hunters_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_dual_fiend_hunters_rare<public> := class<final><concrete>(entity):


    @experimental
    item_dual_fiend_hunters_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_icy_grappler<public> := class<final><concrete>(entity):


    @experimental
    item_monster_parts<public> := class<final><concrete>(entity):


    @experimental
    item_shadow_flopper<public> := class<final><concrete>(entity):


    @experimental
    item_shockwave_launcher_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_minigun_common<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_minigun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_minigun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_minigun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_minigun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_minigun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_scythe_common<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_scythe_epic<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_scythe_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_scythe_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_scythe_rare<public> := class<final><concrete>(entity):


    @experimental
    item_sideways_scythe_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_slones_burst_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_zero_point_pretzel<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/FlippedItems
FlippedItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_auto_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_auto_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_auto_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_auto_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_auto_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_auto_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_dual_suppressed_pistols_epic<public> := class<final><concrete>(entity):


    @experimental
    item_dual_suppressed_pistols_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_dual_suppressed_pistols_rare<public> := class<final><concrete>(entity):


    @experimental
    item_dual_suppressed_pistols_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_gunnars_stinger_smg_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_guzzle_juice<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_hunter_bolt_action_sniper_common<public> := class<final><concrete>(entity):


    @experimental
    item_hunter_bolt_action_sniper_epic<public> := class<final><concrete>(entity):


    @experimental
    item_hunter_bolt_action_sniper_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_hunter_bolt_action_sniper_rare<public> := class<final><concrete>(entity):


    @experimental
    item_hunter_bolt_action_sniper_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_machine_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_machine_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_machine_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_machine_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_machine_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_med_mist<public> := class<final><concrete>(entity):


    @experimental
    item_mk_seven_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_mk_seven_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_mk_seven_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_mk_seven_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_mk_seven_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_pizza_party<public> := class<final><concrete>(entity):


    @experimental
    item_pizza_slice<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_suppressed_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_suppressed_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_suppressed_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_suppressed_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_shield_keg<public> := class<final><concrete>(entity):


    @experimental
    item_sidearm_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_sidearm_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    item_sidearm_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_sidearm_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_sidearm_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_stinger_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_stinger_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_stinger_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_stinger_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_stinger_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_striker_pump_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_striker_pump_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_striker_pump_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_striker_pump_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_striker_pump_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_striker_pump_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_the_foundations_mk_seven_assault_rifle_mythic<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/FortniteOGItems
FortniteOGItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_assault_rifle_common_1<public> := class<final><concrete>(entity):


    @experimental
    item_assault_rifle_common_2<public> := class<final><concrete>(entity):


    @experimental
    item_assault_rifle_epic_1<public> := class<final><concrete>(entity):


    @experimental
    item_assault_rifle_epic_2<public> := class<final><concrete>(entity):


    @experimental
    item_assault_rifle_legendary_1<public> := class<final><concrete>(entity):


    @experimental
    item_assault_rifle_legendary_2<public> := class<final><concrete>(entity):


    @experimental
    item_assault_rifle_rare_1<public> := class<final><concrete>(entity):


    @experimental
    item_assault_rifle_rare_2<public> := class<final><concrete>(entity):


    @experimental
    item_assault_rifle_uncommon_1<public> := class<final><concrete>(entity):


    @experimental
    item_assault_rifle_uncommon_2<public> := class<final><concrete>(entity):


    @experimental
    item_bolt_action_sniper_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_bolt_action_sniper_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_bolt_action_sniper_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_bolt_action_sniper_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_bolt_action_sniper_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_burst_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_burst_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_burst_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_burst_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_burst_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_ceiling_zapper<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_grenade_launcher_epic<public> := class<final><concrete>(entity):


    @experimental
    item_grenade_launcher_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_grenade_launcher_rare<public> := class<final><concrete>(entity):


    @experimental
    item_guided_missile_epic<public> := class<final><concrete>(entity):


    @experimental
    item_guided_missile_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_pump_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_pump_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_pump_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_pump_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_pump_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_revolver_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_revolver_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_revolver_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_revolver_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_revolver_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_rocket_launcher_common<public> := class<final><concrete>(entity):


    @experimental
    item_rocket_launcher_epic<public> := class<final><concrete>(entity):


    @experimental
    item_rocket_launcher_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_rocket_launcher_rare<public> := class<final><concrete>(entity):


    @experimental
    item_rocket_launcher_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_scoped_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_scoped_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_scoped_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_scoped_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_sniper_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_sniper_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_sniper_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_semi_auto_sniper_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_snowball_launcher_epic<public> := class<final><concrete>(entity):


    @experimental
    item_snowball_launcher_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_snowball_launcher_rare<public> := class<final><concrete>(entity):


    @experimental
    item_snowball_launcher_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_submachine_gun_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_submachine_gun_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_submachine_gun_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_submachine_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_submachine_gun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_submachine_gun_common<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_submachine_gun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_submachine_gun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_submachine_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_submachine_gun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_tactical_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)item_tactical_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_submachine_gun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_submachine_gun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_submachine_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_submachine_gun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_wall_dynamo<public> := class<final><concrete>(entity):


    @experimental
    item_zapotron_legendary<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/HuntersItems
HuntersItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_blizzard_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_fury_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_holo_twister_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_oni_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_sentinel_pump_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_surgefire_smg_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_twinfire_auto_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_fire_oni_mask_epic<public> := class<final><concrete>(entity):


    @experimental
    item_fury_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_fury_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_fury_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_fury_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_fury_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_holo_twister_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_holo_twister_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_holo_twister_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_holo_twister_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_holo_twister_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_hunting_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/HuntersItems:)item_hunting_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/HuntersItems:)item_hunting_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_night_rose_veiled_precision_smg_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_night_roses_void_oni_mask<public> := class<final><concrete>(entity):


    @experimental
    item_oni_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_oni_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_oni_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_oni_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_oni_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_sentinel_pump_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_sentinel_pump_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_sentinel_pump_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_sentinel_pump_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_sentinel_pump_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_shogun_xs_fire_oni_mask_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_surgefire_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_surgefire_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_surgefire_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_surgefire_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_surgefire_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_twinfire_auto_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_twinfire_auto_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_twinfire_auto_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_twinfire_auto_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_twinfire_auto_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_typhoon_blade_epic<public> := class<final><concrete>(entity):


    @experimental
    item_typhoon_blade_mythic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/HuntersItems:)item_veiled_precision_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_veiled_precision_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_veiled_precision_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_veiled_precision_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_veiled_precision_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_void_oni_mask<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/InvasionItems
InvasionItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_alien_nanites<public> := class<final><concrete>(entity):


    @experimental
    item_burst_pulse_rifle_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_inflate_a_bull<public> := class<final><concrete>(entity):


    @experimental
    item_kymera_ray_gun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_kymera_ray_gun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_kymera_ray_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_plasma_cannon_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_pulse_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_pulse_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_pulse_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_rail_gun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_rail_gun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_rail_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_recon_scanner_rare<public> := class<final><concrete>(entity):


    @experimental
    item_slones_pulse_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_zyg_and_choppys_ray_gun_mythic<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/LastResortItems
LastResortItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_business_turret<public> := class<final><concrete>(entity):


    @experimental
    item_crash_pad_jr<public> := class<final><concrete>(entity):


    @experimental
    item_diamonds_thermal_dmr_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_infiltrator_pump_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_estate_vault_keycard<public> := class<final><concrete>(entity):


    @experimental
    item_hearts_havoc_suppressed_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_high_stakes_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_infiltrator_pump_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_infiltrator_pump_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_infiltrator_pump_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_infiltrator_pump_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_infiltrator_pump_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_rocket_ram_rare<public> := class<final><concrete>(entity):


    @experimental
    item_scoped_burst_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_scoped_burst_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_scoped_burst_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_scoped_burst_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_scoped_burst_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_shield_breaker_emp<public> := class<final><concrete>(entity):


    @experimental
    item_sticky_grenade_launcher_epic<public> := class<final><concrete>(entity):


    @experimental
    item_sticky_grenade_launcher_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_dmr_common<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_dmr_epic<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_dmr_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_dmr_rare<public> := class<final><concrete>(entity):


    @experimental
    item_tactical_dmr_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_thornes_scoped_burst_smg_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_thornes_vampiric_blade_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_twin_mag_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_twin_mag_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_twin_mag_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_twin_mag_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_twin_mag_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_witch_broom<public> := class<final><concrete>(entity):


    @experimental
    item_wood_stake_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_wood_stake_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_wood_stake_shotgun_rare<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/LawlessItems
LawlessItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_barons_double_down_pistol_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_chug_jug<public> := class<final><concrete>(entity):


    @experimental
    item_collateral_damage_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_collateral_damage_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_collateral_damage_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_collateral_damage_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_collateral_damage_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_dragons_breath_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_dragons_breath_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_collateral_damage_ar_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_falcon_eye_sniper_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_outlaw_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_falcon_eye_sniper_common<public> := class<final><concrete>(entity):


    @experimental
    item_falcon_eye_sniper_epic<public> := class<final><concrete>(entity):


    @experimental
    item_falcon_eye_sniper_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_falcon_eye_sniper_rare<public> := class<final><concrete>(entity):


    @experimental
    item_falcon_eye_sniper_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_gold_splash<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_accelerant_holo_twister_ar_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_blink_pump__dump_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_explosive_mammoth_pistol_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_final_mark_rifle_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_heavy_impact_tracking_rifle_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_rift_launcher<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_shockwave_rocket_launcher_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_slap_cannon<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_slap_jug<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_stink_rifle_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_trinity_assault_rifle_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_lawless_twinfire_slap_shotgun_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_med_mist_smoke_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_midas_gilded_eye_drum_gun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_outlaw_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_outlaw_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_outlaw_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_outlaw_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_outlaw_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_plasma_burst_laser_epic<public> := class<final><concrete>(entity):


    @experimental
    item_port_a_cover<public> := class<final><concrete>(entity):


    @experimental
    item_pulse_scanner<public> := class<final><concrete>(entity):


    @experimental
    item_pump__dump_common<public> := class<final><concrete>(entity):


    @experimental
    item_pump__dump_epic<public> := class<final><concrete>(entity):


    @experimental
    item_pump__dump_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_pump__dump_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_pump__dump_rare<public> := class<final><concrete>(entity):


    @experimental
    item_pump__dump_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_rocket_drill<public> := class<final><concrete>(entity):


    @experimental
    item_suppressed_pistol_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_the_kneecapper_epic<public> := class<final><concrete>(entity):


    @experimental
    item_thermite<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/MEGAItems
MEGAItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_combat_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_havoc_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_havoc_pump_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_havoc_pump_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_havoc_pump_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_havoc_pump_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_havoc_pump_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_havoc_suppressed_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_havoc_suppressed_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_havoc_suppressed_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_havoc_suppressed_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_havoc_suppressed_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_havoc_suppressed_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_heal_egg<public> := class<final><concrete>(entity):


    @experimental
    item_highcards_havoc_suppressed_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_hop_egg<public> := class<final><concrete>(entity):


    @experimental
    item_kinetic_blade_epic<public> := class<final><concrete>(entity):


    @experimental
    item_kinetic_blade_rare<public> := class<final><concrete>(entity):


    @experimental
    item_lock_on_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_mk_alpha_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_mk_alpha_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_mk_alpha_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_mk_alpha_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_mk_alpha_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_overclocked_pulse_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_reliks_mk_alpha_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/MEGAItems:)item_submachine_gun_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/MEGAItems:)item_submachine_gun_legendary<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/MythsAndMortalsItems
MythsAndMortalsItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_ares_modular_warforged_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_banana_of_the_gods<public> := class<final><concrete>(entity):


    @experimental
    item_cerberus_modular_gatekeeper_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_chains_of_hades_epic<public> := class<final><concrete>(entity):


    @experimental
    item_hades_modular_harbinger_smg_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_midas_modular_drum_gun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_drum_gun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_drum_gun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_drum_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_gatekeeper_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_gatekeeper_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_gatekeeper_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_gatekeeper_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_gatekeeper_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hand_cannon_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hand_cannon_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hand_cannon_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_harbinger_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_harbinger_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_harbinger_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_harbinger_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_harbinger_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_huntress_dmr_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_huntress_dmr_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_huntress_dmr_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_huntress_dmr_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_tactical_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_tactical_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_tactical_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_tactical_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_tactical_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_warforged_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_warforged_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_warforged_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_warforged_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_warforged_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_zeus_huntress_dmr_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_shield_bubble_jr<public> := class<final><concrete>(entity):


    @experimental
    item_thunderbolt_of_zeus<public> := class<final><concrete>(entity):


    @experimental
    item_wings_of_icarus<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/ParadiseItems
ParadiseItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_birthday_presents<public> := class<final><concrete>(entity):


    @experimental
    item_cobra_dmr_common<public> := class<final><concrete>(entity):


    @experimental
    item_cobra_dmr_epic<public> := class<final><concrete>(entity):


    @experimental
    item_cobra_dmr_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_cobra_dmr_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_cobra_dmr_rare<public> := class<final><concrete>(entity):


    @experimental
    item_cobra_dmr_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_dial_a_drop<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_burst_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_burst_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_burst_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_burst_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_burst_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_burst_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_evochrome_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_explosive_goo_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_grapple_glider<public> := class<final><concrete>(entity):


    @experimental
    item_inkquisitors_suppressed_smg_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_key<public> := class<final><concrete>(entity):


    @experimental
    item_legacy_launch_pad<public> := class<final><concrete>(entity):


    @experimental
    item_port_a_bunker<public> := class<final><concrete>(entity):


    @experimental
    item_rapid_fire_smg_mythic<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/PreSeasonItems
PreSeasonItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_ammo_heavy_bullets<public> := class<final><concrete>(entity):


    @experimental
    item_ammo_light_bullets<public> := class<final><concrete>(entity):


    @experimental
    item_ammo_medium_bullets<public> := class<final><concrete>(entity):


    @experimental
    item_ammo_rockets<public> := class<final><concrete>(entity):


    @experimental
    item_ammo_shells<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/PreSeasonItems:)item_burst_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/PreSeasonItems:)item_burst_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/PreSeasonItems:)item_burst_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/PreSeasonItems:)item_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_legacy_bandage<public> := class<final><concrete>(entity):


    @experimental
    item_legacy_med_kit<public> := class<final><concrete>(entity):


    @experimental
    item_legacy_shield_potion<public> := class<final><concrete>(entity):


    @experimental
    item_metal<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/PreSeasonItems:)item_pump_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/PreSeasonItems:)item_pump_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/PreSeasonItems:)item_revolver_common<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/PreSeasonItems:)item_revolver_rare<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/PreSeasonItems:)item_revolver_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_stone<public> := class<final><concrete>(entity):


    @experimental
    item_wood<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/PrimalItems
PrimalItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_ammo_arrows<public> := class<final><concrete>(entity):


    @experimental
    item_animal_bones<public> := class<final><concrete>(entity):


    @experimental
    item_cuddle_fish<public> := class<final><concrete>(entity):


    @experimental
    item_dual_pistols_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_dual_pistols_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_egg_launcher_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_grappler_bow_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_bow_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_revolver_common<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_revolver_rare<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_revolver_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_submachine_gun_common<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_submachine_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_makeshift_submachine_gun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_marksman_six_shooter_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_meat<public> := class<final><concrete>(entity):


    @experimental
    item_mechanical_bow_rare<public> := class<final><concrete>(entity):


    @experimental
    item_mechanical_explosive_bow_epic<public> := class<final><concrete>(entity):


    @experimental
    item_mechanical_explosive_bow_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_mechanical_explosive_bow_rare<public> := class<final><concrete>(entity):


    @experimental
    item_mechanical_parts<public> := class<final><concrete>(entity):


    @experimental
    item_mechanical_shockwave_bow_epic<public> := class<final><concrete>(entity):


    @experimental
    item_mechanical_shockwave_bow_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_mechanical_shockwave_bow_rare<public> := class<final><concrete>(entity):


    @experimental
    item_primal_bow_rare<public> := class<final><concrete>(entity):


    @experimental
    item_primal_flame_bow_epic<public> := class<final><concrete>(entity):


    @experimental
    item_primal_flame_bow_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_primal_flame_bow_rare<public> := class<final><concrete>(entity):


    @experimental
    item_primal_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    item_primal_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_primal_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_primal_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_primal_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_primal_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_primal_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_primal_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_primal_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_primal_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_primal_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_primal_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_primal_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_primal_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_primal_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_primal_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_primal_stink_bow_epic<public> := class<final><concrete>(entity):


    @experimental
    item_primal_stink_bow_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_primal_stink_bow_rare<public> := class<final><concrete>(entity):


    @experimental
    item_razs_explosive_bow_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_recycler_epic<public> := class<final><concrete>(entity):


    @experimental
    item_recycler_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_recycler_rare<public> := class<final><concrete>(entity):


    @experimental
    item_spire_assassins_primal_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_spire_assassins_recycler_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_spire_guardians_primal_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_spire_jumpboots<public> := class<final><concrete>(entity):


    @experimental
    item_stink_fish<public> := class<final><concrete>(entity):


    @experimental
    item_stink_sac<public> := class<final><concrete>(entity):


    @experimental
    item_tntinas_ka_boom_bow<public> := class<final><concrete>(entity):


    @experimental
    item_unstable_bow<public> := class<final><concrete>(entity):


    @experimental
    item_vehicle_mod_off_road_tires<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/RebellionItems
RebellionItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_anvil_rocket_launcher_epic<public> := class<final><concrete>(entity):


    @experimental
    item_anvil_rocket_launcher_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_anvil_rocket_launcher_rare<public> := class<final><concrete>(entity):


    @experimental
    item_combat_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_combat_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_combat_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_combat_smg_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_combat_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_combat_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_command_cavern_keycard<public> := class<final><concrete>(entity):


    @experimental
    item_drum_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_drum_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_huntmaster_sabers_thermal_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_light_machine_gun_common<public> := class<final><concrete>(entity):


    @experimental
    item_light_machine_gun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_light_machine_gun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_ranger_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_repair_torch<public> := class<final><concrete>(entity):


    @experimental
    item_striker_burst_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_striker_burst_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_striker_burst_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_striker_burst_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_striker_burst_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_striker_burst_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_vehicle_mod_cow_catcher<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/ShockNAwesomeItems
ShockNAwesomeItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_bug_blaster_epic<public> := class<final><concrete>(entity):


    @experimental
    item_bug_blaster_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_bug_blaster_rare<public> := class<final><concrete>(entity):


    @experimental
    item_double_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_wrecker_revolver_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_eradicator_hop_rock_fury_assault_rifle_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_eradicator_marksman_wrecker_revolver_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_eradicator_oxr_rifle_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_eradicator_shadow_precision_smg_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_eradicator_shock_n_slow_shockwave_launcher_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_exotic_slapberry_fizz<public> := class<final><concrete>(entity):


    @experimental
    item_launch_pad<public> := class<final><concrete>(entity):


    @experimental
    item_leadspitter_3000_epic<public> := class<final><concrete>(entity):


    @experimental
    item_leadspitter_3000_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_leadspitter_3000_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_oxr_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_oxr_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_oxr_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_oxr_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_oxr_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_oxr_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_precision_air_strike<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/ShockNAwesomeItems:)item_pumpkin_launcher_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/ShockNAwesomeItems:)item_pumpkin_launcher_legendary<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/ShockNAwesomeItems:)item_pumpkin_launcher_rare<public> := class<final><concrete>(entity):


    @experimental
    item_shockwave_launcher_epic<public> := class<final><concrete>(entity):


    @experimental
    (/Fortnite.com/Itemization/ShockNAwesomeItems:)item_slurp_juice<public> := class<final><concrete>(entity):


    @experimental
    item_swarmstrike_epic<public> := class<final><concrete>(entity):


    @experimental
    item_swarmstrike_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_sweeper_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_sweeper_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_sweeper_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_sweeper_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_sweeper_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_sweeper_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_trouble_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_wrecker_revolver_common<public> := class<final><concrete>(entity):


    @experimental
    item_wrecker_revolver_epic<public> := class<final><concrete>(entity):


    @experimental
    item_wrecker_revolver_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_wrecker_revolver_rare<public> := class<final><concrete>(entity):


    @experimental
    item_wrecker_revolver_uncommon<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/SuperItems
SuperItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_ascended_myst_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_bass_boost_epic<public> := class<final><concrete>(entity):


    @experimental
    item_bass_boost_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_bass_boost_rare<public> := class<final><concrete>(entity):


    @experimental
    item_deadeye_dmr_common<public> := class<final><concrete>(entity):


    @experimental
    item_deadeye_dmr_epic<public> := class<final><concrete>(entity):


    @experimental
    item_deadeye_dmr_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_deadeye_dmr_rare<public> := class<final><concrete>(entity):


    @experimental
    item_deadeye_dmr_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_hyperburst_pistol_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_spire_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_hyperburst_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_hyperburst_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    item_hyperburst_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_hyperburst_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_hyperburst_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_killswitch_revolvers_epic<public> := class<final><concrete>(entity):


    @experimental
    item_killswitch_revolvers_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_killswitch_revolvers_rare<public> := class<final><concrete>(entity):


    @experimental
    item_killswitchs_revolvers_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_kors_deadeye_dmr_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_lightriders_surf_cube<public> := class<final><concrete>(entity):


    @experimental
    item_myst_form<public> := class<final><concrete>(entity):


    @experimental
    item_myst_gauntlets_epic<public> := class<final><concrete>(entity):


    @experimental
    item_spire_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_spire_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_spire_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_spire_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_spire_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_surf_cube<public> := class<final><concrete>(entity):


    @experimental
    item_tracking_visor<public> := class<final><concrete>(entity):


    @experimental
    item_unstable_bounce_grenade<public> := class<final><concrete>(entity):


    @experimental
    item_unstable_frostfire_shotgun_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_unstable_thunderclap_dmr_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_unstable_voltage_burst_pistol_exotic<public> := class<final><concrete>(entity):


    @experimental
    item_unstable_yoink_shotgun_exotic<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/UndergroundItems
UndergroundItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_ballistic_shield_epic<public> := class<final><concrete>(entity):


    @experimental
    item_bandage<public> := class<final><concrete>(entity):


    @experimental
    item_cluster_clinger<public> := class<final><concrete>(entity):


    @experimental
    item_flowberry<public> := class<final><concrete>(entity):


    @experimental
    item_flowberry_fizz<public> := class<final><concrete>(entity):


    @experimental
    item_grapple_blade_epic<public> := class<final><concrete>(entity):


    @experimental
    item_med_kit<public> := class<final><concrete>(entity):


    @experimental
    item_modular_enforcer_ar_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_enforcer_ar_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_enforcer_ar_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_enforcer_ar_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_enforcer_ar_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_frenzy_auto_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_frenzy_auto_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_frenzy_auto_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_frenzy_auto_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_frenzy_auto_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hammer_pump_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hammer_pump_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hammer_pump_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hammer_pump_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hammer_pump_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hyper_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hyper_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hyper_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hyper_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_hyper_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_nemesis_ar_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_nemesis_ar_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_nemesis_ar_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_nemesis_ar_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_nemesis_ar_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_ranger_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_ranger_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_ranger_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_ranger_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_ranger_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_striker_ar_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_striker_ar_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_striker_ar_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_striker_ar_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_striker_ar_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_thunder_burst_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_thunder_burst_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_thunder_burst_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_thunder_burst_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_thunder_burst_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_montagues_modular_nemesis_ar_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_nishas_modular_striker_ar_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_oscars_modular_frenzy_auto_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_reaper_modular_sniper_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_reaper_modular_sniper_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_reaper_modular_sniper_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_reaper_modular_sniper_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_shield_potion<public> := class<final><concrete>(entity):


    @experimental
    item_small_shield_potion<public> := class<final><concrete>(entity):


    @experimental
    item_valerias_modular_hyper_smg_mythic<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/VibinItems
VibinItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_charge_smg_common<public> := class<final><concrete>(entity):


    @experimental
    item_charge_smg_epic<public> := class<final><concrete>(entity):


    @experimental
    item_charge_smg_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_charge_smg_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_charge_smg_rare<public> := class<final><concrete>(entity):


    @experimental
    item_charge_smg_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_dmr_common<public> := class<final><concrete>(entity):


    @experimental
    item_dmr_epic<public> := class<final><concrete>(entity):


    @experimental
    item_dmr_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_dmr_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_dmr_rare<public> := class<final><concrete>(entity):


    @experimental
    item_dmr_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_firework_flare_gun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_frozen_icecream_cone<public> := class<final><concrete>(entity):


    @experimental
    item_grapple_glove<public> := class<final><concrete>(entity):


    @experimental
    item_guzzling_icecream_cone<public> := class<final><concrete>(entity):


    @experimental
    item_hammer_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_hammer_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_hammer_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_hammer_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_hammer_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_hammer_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_sniper_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_icecream_cone<public> := class<final><concrete>(entity):


    @experimental
    item_lilwhips_special_serve<public> := class<final><concrete>(entity):


    @experimental
    item_prime_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_prime_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_prime_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_prime_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_prime_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_prime_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_ripsaw_launcher_rare<public> := class<final><concrete>(entity):


    @experimental
    item_spicy_icecream_cone<public> := class<final><concrete>(entity):


    @experimental
    item_two_shot_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_two_shot_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_two_shot_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_two_shot_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_two_shot_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_two_shot_shotgun_uncommon<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/WildsItems
WildsItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_cloak_gauntlets<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_drum_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_enhanced_flapjack_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_explosive_repeater_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_explosive_repeater_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_explosive_repeater_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_explosive_repeater_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_explosive_repeater_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_explosive_repeater_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_flapjack_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_flapjack_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_flapjack_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_flapjack_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_flapjack_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_kinetic_boomerang_epic<public> := class<final><concrete>(entity):


    @experimental
    item_mammoth_pistol_common<public> := class<final><concrete>(entity):


    @experimental
    item_mammoth_pistol_epic<public> := class<final><concrete>(entity):


    @experimental
    item_mammoth_pistol_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_mammoth_pistol_rare<public> := class<final><concrete>(entity):


    @experimental
    item_mammoth_pistol_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_sharp_tooth_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_sharp_tooth_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_sharp_tooth_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_sharp_tooth_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_slap_splash<public> := class<final><concrete>(entity):


    @experimental
    item_super_slap_splash<public> := class<final><concrete>(entity):


    @experimental
    item_thermal_dmr_common<public> := class<final><concrete>(entity):


    @experimental
    item_thermal_dmr_epic<public> := class<final><concrete>(entity):


    @experimental
    item_thermal_dmr_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_thermal_dmr_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_thermal_dmr_rare<public> := class<final><concrete>(entity):


    @experimental
    item_thermal_dmr_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_wildguard_reliks_cloak_gauntlets<public> := class<final><concrete>(entity):


    @experimental
    item_wildwasp_jar<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Itemization/WreckedItems
WreckedItems<public> := module:
    using {/Verse.org/SceneGraph}
    @experimental
    item_heavy_impact_sniper_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_impact_sniper_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_heavy_impact_sniper_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_megalo_dons_modular_combat_shotgun_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_megalo_dons_nitro_fists_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_minigun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_boom_bolt_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_boom_bolt_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_boom_bolt_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_combat_assault_rifle_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_combat_assault_rifle_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_combat_assault_rifle_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_combat_assault_rifle_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_combat_assault_rifle_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_combat_shotgun_common<public> := class<final><concrete>(entity):


    @experimental
    item_modular_combat_shotgun_epic<public> := class<final><concrete>(entity):


    @experimental
    item_modular_combat_shotgun_legendary<public> := class<final><concrete>(entity):


    @experimental
    item_modular_combat_shotgun_rare<public> := class<final><concrete>(entity):


    @experimental
    item_modular_combat_shotgun_uncommon<public> := class<final><concrete>(entity):


    @experimental
    item_modular_conductor_hand_cannon_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_nitro_fists_epic<public> := class<final><concrete>(entity):


    @experimental
    item_nitro_splash<public> := class<final><concrete>(entity):


    @experimental
    item_ringmasters_modular_boom_bolt_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_the_machinists_modular_combat_assault_rifle_mythic<public> := class<final><concrete>(entity):


    @experimental
    item_tow_hook_cannon_rare<public> := class<final><concrete>(entity):


play_animation_on_self<epic_internal> := class(ability):
    GameplayAbilityPath<override>:?string = external {}