using {/UnrealEngine.com/Abilities}
using {/Verse.org/SceneGraph}
# Module import path: /Fortnite.com/Itemization/AbsoluteDoomItems
AbsoluteDoomItems<public> := module:
    @experimental
    fort_item_chainsaw<public> := class<final>(entity):


    @experimental
    fort_item_dual_micro_smgs_common<public> := class<final>(entity):


    @experimental
    fort_item_dual_micro_smgs_epic<public> := class<final>(entity):


    @experimental
    fort_item_dual_micro_smgs_legendary<public> := class<final>(entity):


    @experimental
    fort_item_dual_micro_smgs_rare<public> := class<final>(entity):


    @experimental
    fort_item_dual_micro_smgs_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_monarch_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_monarch_pistol_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_monarch_pistol_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_monarch_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_monarch_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_sovereign_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_sovereign_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_sovereign_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_sovereign_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_sovereign_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_striker_burst_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_striker_burst_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_striker_burst_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_striker_burst_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_striker_burst_rifle_uncommon<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/BallisticItems
BallisticItems<public> := module:
    @experimental
    fort_item_bubble_shield<public> := class<final>(entity):


    @experimental
    fort_item_burst_ar_common<public> := class<final>(entity):


    @experimental
    fort_item_drum_gun_common<public> := class<final>(entity):


    @experimental
    fort_item_enforcer_ar_common<public> := class<final>(entity):


    @experimental
    fort_item_fire_grenade<public> := class<final>(entity):


    @experimental
    fort_item_flashbang<public> := class<final>(entity):


    @experimental
    fort_item_frag_grenade<public> := class<final>(entity):


    @experimental
    fort_item_frenzy_auto_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_hammer_pump_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_hand_cannon_common<public> := class<final>(entity):


    @experimental
    fort_item_hyper_smg_common<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/BallisticItems:)fort_item_impulse_grenade<public> := class<final>(entity):


    @experimental
    fort_item_machine_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_nemesis_ar_common<public> := class<final>(entity):


    @experimental
    fort_item_overdrive<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/BallisticItems:)fort_item_proximity_mine<public> := class<final>(entity):


    @experimental
    fort_item_ranger_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_reaper_sniper_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_recon_grenade<public> := class<final>(entity):


    @experimental
    fort_item_rift_point_device<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/BallisticItems:)fort_item_smoke_grenade<public> := class<final>(entity):


    @experimental
    fort_item_sovereign_sniper_common<public> := class<final>(entity):


    @experimental
    fort_item_striker_ar_common<public> := class<final>(entity):


    @experimental
    fort_item_thunder_burst_smg_common<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/BallisticItems:)fort_item_veiled_precision_smg_common<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/CH4S1Items
CH4S1Items<public> := module:
    @experimental
    fort_item_big_bush_bomb<public> := class<final>(entity):


    @experimental
    fort_item_ex_caliber_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_ex_caliber_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_ex_caliber_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_ex_caliber_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_ex_caliber_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_falcon_scout<public> := class<final>(entity):


    @experimental
    fort_item_guardian_shield<public> := class<final>(entity):


    @experimental
    fort_item_heisted_accelerant_shotgun_exotic<public> := class<final>(entity):


    @experimental
    fort_item_heisted_blink_mag_smg_exotic<public> := class<final>(entity):


    @experimental
    fort_item_heisted_breacher_shotgun_exotic<public> := class<final>(entity):


    @experimental
    fort_item_heisted_explosive_assault_rifle_exotic<public> := class<final>(entity):


    @experimental
    fort_item_heisted_run_n_gun_smg_exotic<public> := class<final>(entity):


    @experimental
    fort_item_maven_auto_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_maven_auto_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_maven_auto_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_maven_auto_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_maven_auto_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_red_eye_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_red_eye_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_red_eye_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_red_eye_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_red_eye_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_shockwave_hammer_epic<public> := class<final>(entity):


    @experimental
    fort_item_slap_berry<public> := class<final>(entity):


    @experimental
    fort_item_slap_juice<public> := class<final>(entity):


    @experimental
    fort_item_tactical_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_tactical_pistol_epic<public> := class<final>(entity):


    @experimental
    fort_item_tactical_pistol_legendary<public> := class<final>(entity):


    @experimental
    fort_item_tactical_pistol_mythic<public> := class<final>(entity):


    @experimental
    fort_item_tactical_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_tactical_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_the_ageless_champions_ex_caliber_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_the_ageless_champions_shockwave_hammer_mythic<public> := class<final>(entity):


    @experimental
    fort_item_thunder_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_thunder_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_thunder_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_thunder_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_thunder_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_twin_mag_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_twin_mag_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_twin_mag_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_twin_mag_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_twin_mag_smg_uncommon<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/CreativeItems
CreativeItems<public> := module:
    @experimental
    fort_item_acorn<public> := class<final>(entity):


    @experimental
    fort_item_active_powercell<public> := class<final>(entity):


    @experimental
    fort_item_adhesive_resin<public> := class<final>(entity):


    @experimental
    fort_item_bacon<public> := class<final>(entity):


    @experimental
    fort_item_basic_hammer_common<public> := class<final>(entity):


    @experimental
    fort_item_basic_sword_common<public> := class<final>(entity):


    @experimental
    fort_item_batteries<public> := class<final>(entity):


    @experimental
    fort_item_blast_powder<public> := class<final>(entity):


    @experimental
    fort_item_blue_flecked_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_blue_mushroom<public> := class<final>(entity):


    @experimental
    fort_item_blue_shimmering_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_blue_speckled_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_boar_hair<public> := class<final>(entity):


    @experimental
    fort_item_bouncer<public> := class<final>(entity):


    @experimental
    fort_item_brightcore_ore<public> := class<final>(entity):


    @experimental
    fort_item_brown_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_brown_speckled_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_butter<public> := class<final>(entity):


    @experimental
    fort_item_carved_twine<public> := class<final>(entity):


    @experimental
    fort_item_char_black_mineral_powder<public> := class<final>(entity):


    @experimental
    fort_item_chiller<public> := class<final>(entity):


    @experimental
    fort_item_coal<public> := class<final>(entity):


    @experimental
    fort_item_copper_ore<public> := class<final>(entity):


    @experimental
    fort_item_creative_fishing_rod<public> := class<final>(entity):


    @experimental
    fort_item_creative_pro_fishing_rod<public> := class<final>(entity):


    @experimental
    fort_item_damage_trap<public> := class<final>(entity):


    @experimental
    fort_item_diamond<public> := class<final>(entity):


    @experimental
    fort_item_duct_tape<public> := class<final>(entity):


    @experimental
    fort_item_efficient_mechanical_parts<public> := class<final>(entity):


    @experimental
    fort_item_fibrous_herbs<public> := class<final>(entity):


    @experimental
    fort_item_fine_grain_mineral_powder<public> := class<final>(entity):


    @experimental
    fort_item_flower_petals<public> := class<final>(entity):


    @experimental
    fort_item_gray_eruption_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_green_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_green_flecked_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_green_marbled_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_grub<public> := class<final>(entity):


    @experimental
    fort_item_herb<public> := class<final>(entity):


    @experimental
    fort_item_honey<public> := class<final>(entity):


    @experimental
    fort_item_lemon_lime<public> := class<final>(entity):


    @experimental
    fort_item_malachite_ore<public> := class<final>(entity):


    @experimental
    fort_item_maple_syrup<public> := class<final>(entity):


    @experimental
    fort_item_milk<public> := class<final>(entity):


    @experimental
    fort_item_obsidian_ore<public> := class<final>(entity):


    @experimental
    fort_item_oxidized_mineral_powder<public> := class<final>(entity):


    @experimental
    fort_item_patchwork_tool<public> := class<final>(entity):


    @experimental
    fort_item_peaky_twine<public> := class<final>(entity):


    @experimental
    fort_item_pink_marbled_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_pink_mushroom<public> := class<final>(entity):


    @experimental
    fort_item_planks<public> := class<final>(entity):


    @experimental
    fort_item_prop_o_matic<public> := class<final>(entity):


    @experimental
    fort_item_pumpkin<public> := class<final>(entity):


    @experimental
    fort_item_quartz_crystal<public> := class<final>(entity):


    @experimental
    fort_item_rainbow_crystal<public> := class<final>(entity):


    @experimental
    fort_item_raptor_eye<public> := class<final>(entity):


    @experimental
    fort_item_red_eruption_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_red_flecked_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_red_mushroom<public> := class<final>(entity):


    @experimental
    fort_item_red_shimmering_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_roasted_chicken<public> := class<final>(entity):


    @experimental
    fort_item_rotating_gizmo<public> := class<final>(entity):


    @experimental
    fort_item_rough_mineral_powder<public> := class<final>(entity):


    @experimental
    fort_item_rough_ore<public> := class<final>(entity):


    @experimental
    fort_item_rusty_mechanical_parts<public> := class<final>(entity):


    @experimental
    fort_item_shadowshard_crystal<public> := class<final>(entity):


    @experimental
    fort_item_shark_tooth<public> := class<final>(entity):


    @experimental
    fort_item_shove<public> := class<final>(entity):


    @experimental
    fort_item_signal_remote<public> := class<final>(entity):


    @experimental
    fort_item_signal_remote_a<public> := class<final>(entity):


    @experimental
    fort_item_signal_remote_b<public> := class<final>(entity):


    @experimental
    fort_item_signal_remote_c<public> := class<final>(entity):


    @experimental
    fort_item_signal_remote_d<public> := class<final>(entity):


    @experimental
    fort_item_silver_ore<public> := class<final>(entity):


    @experimental
    fort_item_simple_mechanical_parts<public> := class<final>(entity):


    @experimental
    fort_item_simple_mineral_powder<public> := class<final>(entity):


    @experimental
    fort_item_simple_twine<public> := class<final>(entity):


    @experimental
    fort_item_sleek_mechanical_parts<public> := class<final>(entity):


    @experimental
    fort_item_spectral_twine<public> := class<final>(entity):


    @experimental
    fort_item_spectrolite_ore<public> := class<final>(entity):


    @experimental
    fort_item_speed_boost<public> := class<final>(entity):


    @experimental
    fort_item_speed_boost_high<public> := class<final>(entity):


    @experimental
    fort_item_speed_boost_low<public> := class<final>(entity):


    @experimental
    fort_item_stringy_twine<public> := class<final>(entity):


    @experimental
    fort_item_sturdy_mechanical_parts<public> := class<final>(entity):


    @experimental
    fort_item_sturdy_twine<public> := class<final>(entity):


    @experimental
    fort_item_sunbeam_crystal<public> := class<final>(entity):


    @experimental
    fort_item_vindertech_mechanical_parts<public> := class<final>(entity):


    @experimental
    fort_item_wheat<public> := class<final>(entity):


    @experimental
    fort_item_white_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_white_marbled_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_white_mushroom<public> := class<final>(entity):


    @experimental
    fort_item_white_shimmering_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_white_speckled_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_wolf_tooth<public> := class<final>(entity):


    @experimental
    fort_item_yellow_eruption_dino_egg<public> := class<final>(entity):


    @experimental
    fort_item_yellow_mushroom<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/CubedItems
CubedItems<public> := module:
    @experimental
    fort_item_armored_wall<public> := class<final>(entity):


    @experimental
    fort_item_chili_chug_splash<public> := class<final>(entity):


    @experimental
    fort_item_combat_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_combat_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_combat_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_combat_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_combat_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_combat_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_combat_pistol_epic<public> := class<final>(entity):


    @experimental
    fort_item_combat_pistol_legendary<public> := class<final>(entity):


    @experimental
    fort_item_combat_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_combat_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_dual_fiend_hunters_common<public> := class<final>(entity):


    @experimental
    fort_item_dual_fiend_hunters_epic<public> := class<final>(entity):


    @experimental
    fort_item_dual_fiend_hunters_legendary<public> := class<final>(entity):


    @experimental
    fort_item_dual_fiend_hunters_rare<public> := class<final>(entity):


    @experimental
    fort_item_dual_fiend_hunters_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_icy_grappler<public> := class<final>(entity):


    @experimental
    fort_item_monster_parts<public> := class<final>(entity):


    @experimental
    fort_item_shadow_flopper<public> := class<final>(entity):


    @experimental
    fort_item_shockwave_launcher_legendary<public> := class<final>(entity):


    @experimental
    fort_item_sideways_minigun_common<public> := class<final>(entity):


    @experimental
    fort_item_sideways_minigun_epic<public> := class<final>(entity):


    @experimental
    fort_item_sideways_minigun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_sideways_minigun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_sideways_minigun_rare<public> := class<final>(entity):


    @experimental
    fort_item_sideways_minigun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_sideways_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_sideways_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_sideways_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_sideways_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_sideways_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_sideways_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_sideways_scythe_common<public> := class<final>(entity):


    @experimental
    fort_item_sideways_scythe_epic<public> := class<final>(entity):


    @experimental
    fort_item_sideways_scythe_legendary<public> := class<final>(entity):


    @experimental
    fort_item_sideways_scythe_mythic<public> := class<final>(entity):


    @experimental
    fort_item_sideways_scythe_rare<public> := class<final>(entity):


    @experimental
    fort_item_sideways_scythe_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_zero_point_pretzel<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/FlippedItems
FlippedItems<public> := module:
    @experimental
    fort_item_auto_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_auto_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_auto_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_auto_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_auto_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_auto_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_dual_suppressed_pistols_epic<public> := class<final>(entity):


    @experimental
    fort_item_dual_suppressed_pistols_legendary<public> := class<final>(entity):


    @experimental
    fort_item_dual_suppressed_pistols_rare<public> := class<final>(entity):


    @experimental
    fort_item_dual_suppressed_pistols_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_gunnars_stinger_smg_mythic<public> := class<final>(entity):


    @experimental
    fort_item_guzzle_juice<public> := class<final>(entity):


    @experimental
    fort_item_hunter_bolt_action_sniper_common<public> := class<final>(entity):


    @experimental
    fort_item_hunter_bolt_action_sniper_epic<public> := class<final>(entity):


    @experimental
    fort_item_hunter_bolt_action_sniper_legendary<public> := class<final>(entity):


    @experimental
    fort_item_hunter_bolt_action_sniper_rare<public> := class<final>(entity):


    @experimental
    fort_item_hunter_bolt_action_sniper_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_machine_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_machine_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_machine_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_machine_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_machine_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_med_mist<public> := class<final>(entity):


    @experimental
    fort_item_mk_seven_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_mk_seven_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_mk_seven_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_mk_seven_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_mk_seven_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_pizza_party<public> := class<final>(entity):


    @experimental
    fort_item_pizza_slice<public> := class<final>(entity):


    @experimental
    fort_item_ranger_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_ranger_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_ranger_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_ranger_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_ranger_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_ranger_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_suppressed_pistol_epic<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_suppressed_pistol_legendary<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_suppressed_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_suppressed_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_shield_keg<public> := class<final>(entity):


    @experimental
    fort_item_sidearm_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_sidearm_pistol_epic<public> := class<final>(entity):


    @experimental
    fort_item_sidearm_pistol_legendary<public> := class<final>(entity):


    @experimental
    fort_item_sidearm_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_sidearm_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_stinger_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_stinger_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_stinger_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_stinger_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_stinger_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_striker_pump_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_striker_pump_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_striker_pump_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_striker_pump_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_striker_pump_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_striker_pump_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_the_foundations_mk_seven_assault_rifle_mythic<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/FortniteItems
FortniteItems<public> := module:
    @experimental
    fort_item_air_strike<public> := class<final>(entity):


    @experimental
    fort_item_ammo_heavy_bullets<public> := class<final>(entity):


    @experimental
    fort_item_ammo_light_bullets<public> := class<final>(entity):


    @experimental
    fort_item_ammo_medium_bullets<public> := class<final>(entity):


    @experimental
    fort_item_ammo_rockets<public> := class<final>(entity):


    @experimental
    fort_item_ammo_shells<public> := class<final>(entity):


    @experimental
    fort_item_apple<public> := class<final>(entity):


    @experimental
    fort_item_authority_keycard<public> := class<final>(entity):


    @experimental
    fort_item_automatic_sniper_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_automatic_sniper_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_automatic_sniper_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_automatic_sniper_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_balloons<public> := class<final>(entity):


    @experimental
    fort_item_banana<public> := class<final>(entity):


    @experimental
    fort_item_bandage_bazooka<public> := class<final>(entity):


    @experimental
    fort_item_boogie_bomb<public> := class<final>(entity):


    @experimental
    fort_item_boom_bow_legendary<public> := class<final>(entity):


    @experimental
    fort_item_boom_box<public> := class<final>(entity):


    @experimental
    fort_item_boom_sniper_rifle_exotic<public> := class<final>(entity):


    @experimental
    fort_item_bottle_rockets<public> := class<final>(entity):


    @experimental
    fort_item_brutus_minigun_mythic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_burst_assault_rifle_common<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_burst_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_burst_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_burst_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_burst_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_burst_quad_launcher_exotic<public> := class<final>(entity):


    @experimental
    fort_item_burst_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_burst_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_burst_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_bush<public> := class<final>(entity):


    @experimental
    fort_item_cabbage<public> := class<final>(entity):


    @experimental
    fort_item_candy_corn<public> := class<final>(entity):


    @experimental
    fort_item_catty_corner_keycard<public> := class<final>(entity):


    @experimental
    fort_item_charge_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_charge_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_charge_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_charge_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_charge_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_chiller_grenade<public> := class<final>(entity):


    @experimental
    fort_item_chug_cannon<public> := class<final>(entity):


    @experimental
    fort_item_chug_splash<public> := class<final>(entity):


    @experimental
    fort_item_clinger<public> := class<final>(entity):


    @experimental
    fort_item_coconut<public> := class<final>(entity):


    @experimental
    fort_item_combat_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_combat_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_combat_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_combat_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_combat_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_corn<public> := class<final>(entity):


    @experimental
    fort_item_cozy_campfire<public> := class<final>(entity):


    @experimental
    fort_item_crash_pad<public> := class<final>(entity):


    @experimental
    fort_item_creepin_cardboard<public> := class<final>(entity):


    @experimental
    fort_item_crossbow_epic<public> := class<final>(entity):


    @experimental
    fort_item_crossbow_rare<public> := class<final>(entity):


    @experimental
    fort_item_cupids_crossbow_epic<public> := class<final>(entity):


    @experimental
    fort_item_decoy<public> := class<final>(entity):


    @experimental
    fort_item_double_barrel_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_double_barrel_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_dragons_breath_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_dragons_breath_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_dragons_breath_sniper_exotic<public> := class<final>(entity):


    @experimental
    fort_item_drum_gun_rare<public> := class<final>(entity):


    @experimental
    fort_item_drum_gun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_drum_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_drum_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_drum_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_drum_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_drum_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_dual_pistols_epic<public> := class<final>(entity):


    @experimental
    fort_item_dual_pistols_rare<public> := class<final>(entity):


    @experimental
    fort_item_dynamite<public> := class<final>(entity):


    @experimental
    fort_item_egg_launcher_epic<public> := class<final>(entity):


    @experimental
    fort_item_egg_launcher_legendary<public> := class<final>(entity):


    @experimental
    fort_item_egg_launcher_rare<public> := class<final>(entity):


    @experimental
    fort_item_egg_launcher_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_fiend_hunter_crossbow_epic<public> := class<final>(entity):


    @experimental
    fort_item_fire_trap<public> := class<final>(entity):


    @experimental
    fort_item_firefly_jar<public> := class<final>(entity):


    @experimental
    fort_item_flag<public> := class<final>(entity):


    @experimental
    fort_item_flare_gun_rare<public> := class<final>(entity):


    @experimental
    fort_item_flashlight<public> := class<final>(entity):


    @experimental
    fort_item_flashlight_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_flint_knock_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_flint_knock_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_flopper<public> := class<final>(entity):


    @experimental
    fort_item_fortilla_keycard<public> := class<final>(entity):


    @experimental
    fort_item_gas_can<public> := class<final>(entity):


    @experimental
    fort_item_gliders<public> := class<final>(entity):


    @experimental
    fort_item_gold<public> := class<final>(entity):


    @experimental
    fort_item_grappler<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_grenade<public> := class<final>(entity):


    @experimental
    fort_item_grotto_keycard<public> := class<final>(entity):


    @experimental
    fort_item_hand_cannon_epic<public> := class<final>(entity):


    @experimental
    fort_item_hand_cannon_legendary<public> := class<final>(entity):


    @experimental
    fort_item_hand_cannon_rare<public> := class<final>(entity):


    @experimental
    fort_item_harpoon_gun<public> := class<final>(entity):


    @experimental
    fort_item_heavy_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_heavy_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_heavy_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_heavy_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_heavy_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_heavy_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_heavy_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_heavy_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_heavy_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_heavy_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_heavy_sniper_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_heavy_sniper_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_heavy_sniper_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_holiday_presents<public> := class<final>(entity):


    @experimental
    fort_item_hop_drop<public> := class<final>(entity):


    @experimental
    fort_item_hop_flopper<public> := class<final>(entity):


    @experimental
    fort_item_hop_rock_dualies_exotic<public> := class<final>(entity):


    @experimental
    fort_item_hunting_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_hunting_rifle_legendary<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_hunting_rifle_rare<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_hunting_rifle_uncommon<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_impulse_grenade<public> := class<final>(entity):


    @experimental
    fort_item_infantry_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_infantry_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_infantry_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_infantry_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_infantry_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_infinity_blade<public> := class<final>(entity):


    @experimental
    fort_item_jelly_bean<public> := class<final>(entity):


    @experimental
    fort_item_jellyfish<public> := class<final>(entity):


    @experimental
    fort_item_jetpack<public> := class<final>(entity):


    @experimental
    fort_item_jewel<public> := class<final>(entity):


    @experimental
    fort_item_jules_drum_gun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_jules_glider_gun<public> := class<final>(entity):


    @experimental
    fort_item_junk_rift<public> := class<final>(entity):


    @experimental
    fort_item_kits_charge_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_kits_shockwave_launcher_mythic<public> := class<final>(entity):


    @experimental
    fort_item_legacy_bandage<public> := class<final>(entity):


    @experimental
    fort_item_legacy_chug_jug<public> := class<final>(entity):


    @experimental
    fort_item_legacy_dragons_breath_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_legacy_dragons_breath_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_legacy_med_kit<public> := class<final>(entity):


    @experimental
    fort_item_legacy_shield_potion<public> := class<final>(entity):


    @experimental
    fort_item_legacy_small_shield_potion<public> := class<final>(entity):


    @experimental
    fort_item_lever_action_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_lever_action_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_lever_action_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_lever_action_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_lever_action_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_lever_action_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_lever_action_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_lever_action_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_lever_action_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_light_machine_gun_common<public> := class<final>(entity):


    @experimental
    fort_item_light_machine_gun_epic<public> := class<final>(entity):


    @experimental
    fort_item_light_machine_gun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_light_machine_gun_rare<public> := class<final>(entity):


    @experimental
    fort_item_light_machine_gun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_lump_of_coal<public> := class<final>(entity):


    @experimental
    fort_item_meowscles_peow_peow_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_metal<public> := class<final>(entity):


    @experimental
    fort_item_midas_drum_gun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_midas_flopper<public> := class<final>(entity):


    @experimental
    fort_item_minigun_epic<public> := class<final>(entity):


    @experimental
    fort_item_minigun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_minigun_rare<public> := class<final>(entity):


    @experimental
    fort_item_mythic_goldfish<public> := class<final>(entity):


    @experimental
    fort_item_night_hawk_exotic<public> := class<final>(entity):


    @experimental
    fort_item_oceans_bottomless_chug_jug<public> := class<final>(entity):


    @experimental
    fort_item_oceans_burst_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_orange_paint_grenade<public> := class<final>(entity):


    @experimental
    fort_item_orange_paint_launcher_rare<public> := class<final>(entity):


    @experimental
    fort_item_pepper<public> := class<final>(entity):


    @experimental
    fort_item_pepper_mint<public> := class<final>(entity):


    @experimental
    fort_item_poison_dart_trap<public> := class<final>(entity):


    @experimental
    fort_item_port_a_fort<public> := class<final>(entity):


    @experimental
    fort_item_port_a_fortress<public> := class<final>(entity):


    @experimental
    fort_item_presents<public> := class<final>(entity):


    @experimental
    fort_item_proximity_grenade_launcher_epic<public> := class<final>(entity):


    @experimental
    fort_item_proximity_grenade_launcher_legendary<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_proximity_mine<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_pump_shotgun_common<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_pump_shotgun_epic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_pump_shotgun_legendary<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_pump_shotgun_rare<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_pump_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_pumpkin_launcher_epic<public> := class<final>(entity):


    @experimental
    fort_item_pumpkin_launcher_legendary<public> := class<final>(entity):


    @experimental
    fort_item_pumpkin_launcher_rare<public> := class<final>(entity):


    @experimental
    fort_item_pumpkin_launcher_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_purple_paint_grenade<public> := class<final>(entity):


    @experimental
    fort_item_purple_paint_launcher_rare<public> := class<final>(entity):


    @experimental
    fort_item_quad_launcher_epic<public> := class<final>(entity):


    @experimental
    fort_item_quad_launcher_legendary<public> := class<final>(entity):


    @experimental
    fort_item_rapid_fire_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_rapid_fire_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_rapid_fire_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_rapid_fire_smg_mythic<public> := class<final>(entity):


    @experimental
    fort_item_rapid_fire_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_rapid_fire_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_remote_explosives<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_revolver_common<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_revolver_epic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_revolver_legendary<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_revolver_rare<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_revolver_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_rift_fish<public> := class<final>(entity):


    @experimental
    fort_item_rift_to_go<public> := class<final>(entity):


    @experimental
    fort_item_rig_keycard<public> := class<final>(entity):


    @experimental
    fort_item_rusty_can<public> := class<final>(entity):


    @experimental
    fort_item_scoped_revolver_epic<public> := class<final>(entity):


    @experimental
    fort_item_scoped_revolver_legendary<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_pistol_epic<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_pistol_legendary<public> := class<final>(entity):


    @experimental
    fort_item_shadow_bomb<public> := class<final>(entity):


    @experimental
    fort_item_shadow_midas_drum_gun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_shadow_tracker_exotic<public> := class<final>(entity):


    @experimental
    fort_item_shark_keycard<public> := class<final>(entity):


    @experimental
    fort_item_shield_bubble<public> := class<final>(entity):


    @experimental
    fort_item_shield_fish<public> := class<final>(entity):


    @experimental
    fort_item_shield_mushroom<public> := class<final>(entity):


    @experimental
    fort_item_shockwave_grenade<public> := class<final>(entity):


    @experimental
    fort_item_six_shooter_epic<public> := class<final>(entity):


    @experimental
    fort_item_six_shooter_rare<public> := class<final>(entity):


    @experimental
    fort_item_six_shooter_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_skyes_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_skyes_grappler<public> := class<final>(entity):


    @experimental
    fort_item_slones_burst_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_slurp_juice<public> := class<final>(entity):


    @experimental
    fort_item_slurp_mushroom<public> := class<final>(entity):


    @experimental
    fort_item_slurpfish<public> := class<final>(entity):


    @experimental
    fort_item_small_fry<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_smoke_grenade<public> := class<final>(entity):


    @experimental
    fort_item_sneaky_snowman<public> := class<final>(entity):


    @experimental
    fort_item_snowy_flopper<public> := class<final>(entity):


    @experimental
    fort_item_spicy_fish<public> := class<final>(entity):


    @experimental
    fort_item_stink_bomb<public> := class<final>(entity):


    @experimental
    fort_item_stink_fish<public> := class<final>(entity):


    @experimental
    fort_item_stone<public> := class<final>(entity):


    @experimental
    fort_item_storm_flip<public> := class<final>(entity):


    @experimental
    fort_item_storm_scout_exotic<public> := class<final>(entity):


    @experimental
    fort_item_storm_scout_sniper_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_storm_scout_sniper_rifle_legendary<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_submachine_gun_common<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_submachine_gun_epic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_submachine_gun_legendary<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_submachine_gun_rare<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteItems:)fort_item_submachine_gun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_sniper_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_sniper_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_sniper_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_tactical_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_tactical_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_tactical_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_tactical_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_tactical_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_the_big_chill_exotic<public> := class<final>(entity):


    @experimental
    fort_item_the_dub_exotic<public> := class<final>(entity):


    @experimental
    fort_item_thermal_fish<public> := class<final>(entity):


    @experimental
    fort_item_thermal_scoped_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_thermal_scoped_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_thermal_taffy<public> := class<final>(entity):


    @experimental
    fort_item_torch<public> := class<final>(entity):


    @experimental
    fort_item_vendetta_flopper<public> := class<final>(entity):


    @experimental
    fort_item_wood<public> := class<final>(entity):


    @experimental
    fort_item_zero_point_fish<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/FortniteOGItems
FortniteOGItems<public> := module:
    @experimental
    fort_item_assault_rifle_common_1<public> := class<final>(entity):


    @experimental
    fort_item_assault_rifle_common_2<public> := class<final>(entity):


    @experimental
    fort_item_assault_rifle_epic_1<public> := class<final>(entity):


    @experimental
    fort_item_assault_rifle_epic_2<public> := class<final>(entity):


    @experimental
    fort_item_assault_rifle_legendary_1<public> := class<final>(entity):


    @experimental
    fort_item_assault_rifle_legendary_2<public> := class<final>(entity):


    @experimental
    fort_item_assault_rifle_rare_1<public> := class<final>(entity):


    @experimental
    fort_item_assault_rifle_rare_2<public> := class<final>(entity):


    @experimental
    fort_item_assault_rifle_uncommon_1<public> := class<final>(entity):


    @experimental
    fort_item_assault_rifle_uncommon_2<public> := class<final>(entity):


    @experimental
    fort_item_bolt_action_sniper_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_bolt_action_sniper_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_bolt_action_sniper_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_bolt_action_sniper_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_bolt_action_sniper_rifle_uncommon<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_burst_assault_rifle_common<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_burst_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_burst_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_burst_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_burst_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_ceiling_zapper<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_grenade<public> := class<final>(entity):


    @experimental
    fort_item_grenade_launcher_epic<public> := class<final>(entity):


    @experimental
    fort_item_grenade_launcher_legendary<public> := class<final>(entity):


    @experimental
    fort_item_grenade_launcher_rare<public> := class<final>(entity):


    @experimental
    fort_item_guided_missile_epic<public> := class<final>(entity):


    @experimental
    fort_item_guided_missile_legendary<public> := class<final>(entity):


    @experimental
    fort_item_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_pistol_uncommon<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_pump_shotgun_common<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_pump_shotgun_epic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_pump_shotgun_legendary<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_pump_shotgun_rare<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_pump_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_revolver_common<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_revolver_epic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_revolver_legendary<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_revolver_rare<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_revolver_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_rocket_launcher_common<public> := class<final>(entity):


    @experimental
    fort_item_rocket_launcher_epic<public> := class<final>(entity):


    @experimental
    fort_item_rocket_launcher_legendary<public> := class<final>(entity):


    @experimental
    fort_item_rocket_launcher_rare<public> := class<final>(entity):


    @experimental
    fort_item_rocket_launcher_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_scoped_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_scoped_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_scoped_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_scoped_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_sniper_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_sniper_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_sniper_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_semi_auto_sniper_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_snowball_launcher_epic<public> := class<final>(entity):


    @experimental
    fort_item_snowball_launcher_legendary<public> := class<final>(entity):


    @experimental
    fort_item_snowball_launcher_rare<public> := class<final>(entity):


    @experimental
    fort_item_snowball_launcher_uncommon<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_submachine_gun_common<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_submachine_gun_epic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_submachine_gun_legendary<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_submachine_gun_rare<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/FortniteOGItems:)fort_item_submachine_gun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_submachine_gun_common<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_submachine_gun_epic<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_submachine_gun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_submachine_gun_rare<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_submachine_gun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_tactical_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_tactical_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_tactical_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_tactical_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_tactical_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_tactical_submachine_gun_epic<public> := class<final>(entity):


    @experimental
    fort_item_tactical_submachine_gun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_tactical_submachine_gun_rare<public> := class<final>(entity):


    @experimental
    fort_item_tactical_submachine_gun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_wall_dynamo<public> := class<final>(entity):


    @experimental
    fort_item_zapotron_legendary<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/HuntersItems
HuntersItems<public> := module:
    @experimental
    fort_item_blizzard_grenade<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_fury_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_holo_twister_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_oni_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_sentinel_pump_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_surgefire_smg_mythic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_twinfire_auto_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_fire_oni_mask_epic<public> := class<final>(entity):


    @experimental
    fort_item_fury_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_fury_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_fury_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_fury_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_fury_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_holo_twister_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_holo_twister_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_holo_twister_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_holo_twister_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_holo_twister_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_hunting_rifle_mythic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/HuntersItems:)fort_item_hunting_rifle_rare<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/HuntersItems:)fort_item_hunting_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_night_rose_veiled_precision_smg_mythic<public> := class<final>(entity):


    @experimental
    fort_item_night_roses_void_oni_mask<public> := class<final>(entity):


    @experimental
    fort_item_oni_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_oni_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_oni_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_oni_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_oni_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_sentinel_pump_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_sentinel_pump_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_sentinel_pump_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_sentinel_pump_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_sentinel_pump_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_shogun_xs_fire_oni_mask_mythic<public> := class<final>(entity):


    @experimental
    fort_item_surgefire_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_surgefire_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_surgefire_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_surgefire_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_surgefire_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_twinfire_auto_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_twinfire_auto_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_twinfire_auto_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_twinfire_auto_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_twinfire_auto_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_typhoon_blade_epic<public> := class<final>(entity):


    @experimental
    fort_item_typhoon_blade_mythic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/HuntersItems:)fort_item_veiled_precision_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_veiled_precision_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_veiled_precision_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_veiled_precision_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_veiled_precision_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_void_oni_mask<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/InvasionItems
InvasionItems<public> := module:
    @experimental
    fort_item_alien_nanites<public> := class<final>(entity):


    @experimental
    fort_item_burst_pulse_rifle_exotic<public> := class<final>(entity):


    @experimental
    fort_item_inflate_a_bull<public> := class<final>(entity):


    @experimental
    fort_item_kymera_ray_gun_epic<public> := class<final>(entity):


    @experimental
    fort_item_kymera_ray_gun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_kymera_ray_gun_rare<public> := class<final>(entity):


    @experimental
    fort_item_plasma_cannon_legendary<public> := class<final>(entity):


    @experimental
    fort_item_pulse_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_pulse_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_pulse_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_rail_gun_epic<public> := class<final>(entity):


    @experimental
    fort_item_rail_gun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_rail_gun_rare<public> := class<final>(entity):


    @experimental
    fort_item_recon_scanner_rare<public> := class<final>(entity):


    @experimental
    fort_item_slones_pulse_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_zyg_and_choppys_ray_gun_mythic<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/LastResortItems
LastResortItems<public> := module:
    @experimental
    fort_item_business_turret<public> := class<final>(entity):


    @experimental
    fort_item_crash_pad_jr<public> := class<final>(entity):


    @experimental
    fort_item_diamonds_thermal_dmr_mythic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_infiltrator_pump_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_estate_vault_keycard<public> := class<final>(entity):


    @experimental
    fort_item_hearts_havoc_suppressed_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_high_stakes_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_infiltrator_pump_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_infiltrator_pump_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_infiltrator_pump_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_infiltrator_pump_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_infiltrator_pump_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_rocket_ram_rare<public> := class<final>(entity):


    @experimental
    fort_item_scoped_burst_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_scoped_burst_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_scoped_burst_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_scoped_burst_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_scoped_burst_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_shield_breaker_emp<public> := class<final>(entity):


    @experimental
    fort_item_sticky_grenade_launcher_epic<public> := class<final>(entity):


    @experimental
    fort_item_sticky_grenade_launcher_legendary<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_pistol_epic<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_pistol_legendary<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_tactical_dmr_common<public> := class<final>(entity):


    @experimental
    fort_item_tactical_dmr_epic<public> := class<final>(entity):


    @experimental
    fort_item_tactical_dmr_legendary<public> := class<final>(entity):


    @experimental
    fort_item_tactical_dmr_rare<public> := class<final>(entity):


    @experimental
    fort_item_tactical_dmr_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_thornes_scoped_burst_smg_mythic<public> := class<final>(entity):


    @experimental
    fort_item_thornes_vampiric_blade_mythic<public> := class<final>(entity):


    @experimental
    fort_item_twin_mag_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_twin_mag_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_twin_mag_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_twin_mag_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_twin_mag_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_witch_broom<public> := class<final>(entity):


    @experimental
    fort_item_wood_stake_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_wood_stake_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_wood_stake_shotgun_rare<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/LawlessItems
LawlessItems<public> := module:
    @experimental
    fort_item_barons_double_down_pistol_mythic<public> := class<final>(entity):


    @experimental
    fort_item_chug_jug<public> := class<final>(entity):


    @experimental
    fort_item_collateral_damage_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_collateral_damage_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_collateral_damage_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_collateral_damage_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_collateral_damage_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_collateral_damage_ar_mythic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_falcon_eye_sniper_mythic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_outlaw_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_falcon_eye_sniper_common<public> := class<final>(entity):


    @experimental
    fort_item_falcon_eye_sniper_epic<public> := class<final>(entity):


    @experimental
    fort_item_falcon_eye_sniper_legendary<public> := class<final>(entity):


    @experimental
    fort_item_falcon_eye_sniper_rare<public> := class<final>(entity):


    @experimental
    fort_item_falcon_eye_sniper_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_gold_splash<public> := class<final>(entity):


    @experimental
    fort_item_lawless_accelerant_holo_twister_ar_exotic<public> := class<final>(entity):


    @experimental
    fort_item_lawless_blink_pump__dump_exotic<public> := class<final>(entity):


    @experimental
    fort_item_lawless_explosive_mammoth_pistol_exotic<public> := class<final>(entity):


    @experimental
    fort_item_lawless_final_mark_rifle_exotic<public> := class<final>(entity):


    @experimental
    fort_item_lawless_heavy_impact_tracking_rifle_exotic<public> := class<final>(entity):


    @experimental
    fort_item_lawless_rift_launcher<public> := class<final>(entity):


    @experimental
    fort_item_lawless_shockwave_rocket_launcher_exotic<public> := class<final>(entity):


    @experimental
    fort_item_lawless_slap_cannon<public> := class<final>(entity):


    @experimental
    fort_item_lawless_slap_jug<public> := class<final>(entity):


    @experimental
    fort_item_lawless_stink_rifle_exotic<public> := class<final>(entity):


    @experimental
    fort_item_lawless_trinity_assault_rifle_exotic<public> := class<final>(entity):


    @experimental
    fort_item_lawless_twinfire_slap_shotgun_exotic<public> := class<final>(entity):


    @experimental
    fort_item_med_mist_smoke_grenade<public> := class<final>(entity):


    @experimental
    fort_item_midas_gilded_eye_drum_gun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_outlaw_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_outlaw_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_outlaw_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_outlaw_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_outlaw_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_plasma_burst_laser_epic<public> := class<final>(entity):


    @experimental
    fort_item_port_a_cover<public> := class<final>(entity):


    @experimental
    fort_item_pulse_scanner<public> := class<final>(entity):


    @experimental
    fort_item_pump__dump_common<public> := class<final>(entity):


    @experimental
    fort_item_pump__dump_epic<public> := class<final>(entity):


    @experimental
    fort_item_pump__dump_legendary<public> := class<final>(entity):


    @experimental
    fort_item_pump__dump_mythic<public> := class<final>(entity):


    @experimental
    fort_item_pump__dump_rare<public> := class<final>(entity):


    @experimental
    fort_item_pump__dump_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_rocket_drill<public> := class<final>(entity):


    @experimental
    fort_item_suppressed_pistol_mythic<public> := class<final>(entity):


    @experimental
    fort_item_the_kneecapper_epic<public> := class<final>(entity):


    @experimental
    fort_item_thermite<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/MEGAItems
MEGAItems<public> := module:
    @experimental
    fort_item_enhanced_havoc_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_havoc_pump_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_havoc_pump_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_havoc_pump_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_havoc_pump_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_havoc_pump_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_havoc_suppressed_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_havoc_suppressed_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_havoc_suppressed_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_havoc_suppressed_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_havoc_suppressed_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_havoc_suppressed_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_heal_egg<public> := class<final>(entity):


    @experimental
    fort_item_highcards_havoc_suppressed_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_hop_egg<public> := class<final>(entity):


    @experimental
    fort_item_kinetic_blade_epic<public> := class<final>(entity):


    @experimental
    fort_item_kinetic_blade_rare<public> := class<final>(entity):


    @experimental
    fort_item_lock_on_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_mk_alpha_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_mk_alpha_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_mk_alpha_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_mk_alpha_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_mk_alpha_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_overclocked_pulse_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_reliks_mk_alpha_assault_rifle_mythic<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/MythsAndMortalsItems
MythsAndMortalsItems<public> := module:
    @experimental
    fort_item_ares_modular_warforged_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_banana_of_the_gods<public> := class<final>(entity):


    @experimental
    fort_item_cerberus_modular_gatekeeper_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_chains_of_hades_epic<public> := class<final>(entity):


    @experimental
    fort_item_hades_modular_harbinger_smg_mythic<public> := class<final>(entity):


    @experimental
    fort_item_midas_modular_drum_gun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_modular_drum_gun_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_drum_gun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_drum_gun_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_gatekeeper_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_gatekeeper_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_gatekeeper_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_gatekeeper_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_gatekeeper_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_hand_cannon_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_hand_cannon_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_hand_cannon_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_harbinger_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_harbinger_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_harbinger_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_harbinger_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_harbinger_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_huntress_dmr_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_huntress_dmr_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_huntress_dmr_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_huntress_dmr_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_tactical_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_tactical_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_tactical_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_tactical_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_tactical_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_warforged_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_warforged_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_warforged_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_warforged_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_warforged_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_zeus_huntress_dmr_mythic<public> := class<final>(entity):


    @experimental
    fort_item_shield_bubble_jr<public> := class<final>(entity):


    @experimental
    fort_item_thunderbolt_of_zeus<public> := class<final>(entity):


    @experimental
    fort_item_wings_of_icarus<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/ParadiseItems
ParadiseItems<public> := module:
    @experimental
    fort_item_birthday_presents<public> := class<final>(entity):


    @experimental
    fort_item_cobra_dmr_common<public> := class<final>(entity):


    @experimental
    fort_item_cobra_dmr_epic<public> := class<final>(entity):


    @experimental
    fort_item_cobra_dmr_legendary<public> := class<final>(entity):


    @experimental
    fort_item_cobra_dmr_mythic<public> := class<final>(entity):


    @experimental
    fort_item_cobra_dmr_rare<public> := class<final>(entity):


    @experimental
    fort_item_cobra_dmr_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_dial_a_drop<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_burst_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_burst_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_burst_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_burst_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_burst_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_burst_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_evochrome_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_explosive_goo_gun_rare<public> := class<final>(entity):


    @experimental
    fort_item_grapple_glider<public> := class<final>(entity):


    @experimental
    fort_item_inkquisitors_suppressed_smg_mythic<public> := class<final>(entity):


    @experimental
    fort_item_key<public> := class<final>(entity):


    @experimental
    fort_item_legacy_launch_pad<public> := class<final>(entity):


    @experimental
    fort_item_port_a_bunker<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/PrimalItems
PrimalItems<public> := module:
    @experimental
    fort_item_ammo_arrows<public> := class<final>(entity):


    @experimental
    fort_item_animal_bones<public> := class<final>(entity):


    @experimental
    fort_item_cuddle_fish<public> := class<final>(entity):


    @experimental
    fort_item_dual_pistols_legendary<public> := class<final>(entity):


    @experimental
    fort_item_dual_pistols_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_grappler_bow_exotic<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_bow_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_revolver_common<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_revolver_rare<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_revolver_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_submachine_gun_common<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_submachine_gun_rare<public> := class<final>(entity):


    @experimental
    fort_item_makeshift_submachine_gun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_marksman_six_shooter_exotic<public> := class<final>(entity):


    @experimental
    fort_item_meat<public> := class<final>(entity):


    @experimental
    fort_item_mechanical_bow_rare<public> := class<final>(entity):


    @experimental
    fort_item_mechanical_explosive_bow_epic<public> := class<final>(entity):


    @experimental
    fort_item_mechanical_explosive_bow_legendary<public> := class<final>(entity):


    @experimental
    fort_item_mechanical_explosive_bow_rare<public> := class<final>(entity):


    @experimental
    fort_item_mechanical_parts<public> := class<final>(entity):


    @experimental
    fort_item_mechanical_shockwave_bow_epic<public> := class<final>(entity):


    @experimental
    fort_item_mechanical_shockwave_bow_legendary<public> := class<final>(entity):


    @experimental
    fort_item_mechanical_shockwave_bow_rare<public> := class<final>(entity):


    @experimental
    fort_item_primal_bow_rare<public> := class<final>(entity):


    @experimental
    fort_item_primal_flame_bow_epic<public> := class<final>(entity):


    @experimental
    fort_item_primal_flame_bow_legendary<public> := class<final>(entity):


    @experimental
    fort_item_primal_flame_bow_rare<public> := class<final>(entity):


    @experimental
    fort_item_primal_pistol_epic<public> := class<final>(entity):


    @experimental
    fort_item_primal_pistol_legendary<public> := class<final>(entity):


    @experimental
    fort_item_primal_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_primal_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_primal_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_primal_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_primal_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_primal_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_primal_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_primal_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_primal_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_primal_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_primal_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_primal_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_primal_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_primal_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_primal_stink_bow_epic<public> := class<final>(entity):


    @experimental
    fort_item_primal_stink_bow_legendary<public> := class<final>(entity):


    @experimental
    fort_item_primal_stink_bow_rare<public> := class<final>(entity):


    @experimental
    fort_item_razs_explosive_bow_mythic<public> := class<final>(entity):


    @experimental
    fort_item_recycler_epic<public> := class<final>(entity):


    @experimental
    fort_item_recycler_legendary<public> := class<final>(entity):


    @experimental
    fort_item_recycler_rare<public> := class<final>(entity):


    @experimental
    fort_item_spire_assassins_primal_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_spire_assassins_recycler_mythic<public> := class<final>(entity):


    @experimental
    fort_item_spire_guardians_primal_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_spire_jumpboots<public> := class<final>(entity):


    @experimental
    fort_item_stink_sac<public> := class<final>(entity):


    @experimental
    fort_item_tntinas_ka_boom_bow<public> := class<final>(entity):


    @experimental
    fort_item_unstable_bow<public> := class<final>(entity):


    @experimental
    fort_item_vehicle_mod_off_road_tires<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/RebellionItems
RebellionItems<public> := module:
    @experimental
    fort_item_anvil_rocket_launcher_epic<public> := class<final>(entity):


    @experimental
    fort_item_anvil_rocket_launcher_legendary<public> := class<final>(entity):


    @experimental
    fort_item_anvil_rocket_launcher_rare<public> := class<final>(entity):


    @experimental
    fort_item_combat_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_combat_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_combat_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_combat_smg_mythic<public> := class<final>(entity):


    @experimental
    fort_item_combat_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_combat_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_command_cavern_keycard<public> := class<final>(entity):


    @experimental
    fort_item_huntmaster_sabers_thermal_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_ranger_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_ranger_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_ranger_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_ranger_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_ranger_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_repair_torch<public> := class<final>(entity):


    @experimental
    fort_item_striker_burst_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_striker_burst_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_striker_burst_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_striker_burst_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_striker_burst_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_striker_burst_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_vehicle_mod_cow_catcher<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/ShockNAwesomeItems
ShockNAwesomeItems<public> := module:
    @experimental
    fort_item_bug_blaster_epic<public> := class<final>(entity):


    @experimental
    fort_item_bug_blaster_legendary<public> := class<final>(entity):


    @experimental
    fort_item_bug_blaster_rare<public> := class<final>(entity):


    @experimental
    fort_item_double_exotic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_wrecker_revolver_mythic<public> := class<final>(entity):


    @experimental
    fort_item_eradicator_hop_rock_fury_assault_rifle_exotic<public> := class<final>(entity):


    @experimental
    fort_item_eradicator_marksman_wrecker_revolver_exotic<public> := class<final>(entity):


    @experimental
    fort_item_eradicator_oxr_rifle_exotic<public> := class<final>(entity):


    @experimental
    fort_item_eradicator_shadow_precision_smg_exotic<public> := class<final>(entity):


    @experimental
    fort_item_eradicator_shock_n_slow_shockwave_launcher_exotic<public> := class<final>(entity):


    @experimental
    fort_item_exotic_slapberry_fizz<public> := class<final>(entity):


    @experimental
    fort_item_launch_pad<public> := class<final>(entity):


    @experimental
    fort_item_leadspitter_3000_epic<public> := class<final>(entity):


    @experimental
    fort_item_leadspitter_3000_legendary<public> := class<final>(entity):


    @experimental
    fort_item_leadspitter_3000_mythic<public> := class<final>(entity):


    @experimental
    fort_item_oxr_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_oxr_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_oxr_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_oxr_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_oxr_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_oxr_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_precision_air_strike<public> := class<final>(entity):


    @experimental
    fort_item_shockwave_launcher_epic<public> := class<final>(entity):


    @experimental
    (/Fortnite.com/Itemization/ShockNAwesomeItems:)fort_item_slurp_juice<public> := class<final>(entity):


    @experimental
    fort_item_swarmstrike_epic<public> := class<final>(entity):


    @experimental
    fort_item_swarmstrike_legendary<public> := class<final>(entity):


    @experimental
    fort_item_sweeper_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_sweeper_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_sweeper_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_sweeper_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_sweeper_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_sweeper_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_trouble_exotic<public> := class<final>(entity):


    @experimental
    fort_item_wrecker_revolver_common<public> := class<final>(entity):


    @experimental
    fort_item_wrecker_revolver_epic<public> := class<final>(entity):


    @experimental
    fort_item_wrecker_revolver_legendary<public> := class<final>(entity):


    @experimental
    fort_item_wrecker_revolver_rare<public> := class<final>(entity):


    @experimental
    fort_item_wrecker_revolver_uncommon<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/SuperItems
SuperItems<public> := module:
    @experimental
    fort_item_ascended_myst_legendary<public> := class<final>(entity):


    @experimental
    fort_item_bass_boost_epic<public> := class<final>(entity):


    @experimental
    fort_item_bass_boost_mythic<public> := class<final>(entity):


    @experimental
    fort_item_bass_boost_rare<public> := class<final>(entity):


    @experimental
    fort_item_deadeye_dmr_common<public> := class<final>(entity):


    @experimental
    fort_item_deadeye_dmr_epic<public> := class<final>(entity):


    @experimental
    fort_item_deadeye_dmr_legendary<public> := class<final>(entity):


    @experimental
    fort_item_deadeye_dmr_rare<public> := class<final>(entity):


    @experimental
    fort_item_deadeye_dmr_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_hyperburst_pistol_mythic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_spire_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_hyperburst_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_hyperburst_pistol_epic<public> := class<final>(entity):


    @experimental
    fort_item_hyperburst_pistol_legendary<public> := class<final>(entity):


    @experimental
    fort_item_hyperburst_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_hyperburst_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_killswitch_revolvers_epic<public> := class<final>(entity):


    @experimental
    fort_item_killswitch_revolvers_legendary<public> := class<final>(entity):


    @experimental
    fort_item_killswitch_revolvers_rare<public> := class<final>(entity):


    @experimental
    fort_item_killswitchs_revolvers_mythic<public> := class<final>(entity):


    @experimental
    fort_item_kors_deadeye_dmr_mythic<public> := class<final>(entity):


    @experimental
    fort_item_lightriders_surf_cube<public> := class<final>(entity):


    @experimental
    fort_item_myst_form<public> := class<final>(entity):


    @experimental
    fort_item_myst_gauntlets_epic<public> := class<final>(entity):


    @experimental
    fort_item_spire_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_spire_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_spire_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_spire_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_spire_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_surf_cube<public> := class<final>(entity):


    @experimental
    fort_item_tracking_visor<public> := class<final>(entity):


    @experimental
    fort_item_unstable_bounce_grenade<public> := class<final>(entity):


    @experimental
    fort_item_unstable_frostfire_shotgun_exotic<public> := class<final>(entity):


    @experimental
    fort_item_unstable_thunderclap_dmr_exotic<public> := class<final>(entity):


    @experimental
    fort_item_unstable_voltage_burst_pistol_exotic<public> := class<final>(entity):


    @experimental
    fort_item_unstable_yoink_shotgun_exotic<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/UndergroundItems
UndergroundItems<public> := module:
    @experimental
    fort_item_ballistic_shield_epic<public> := class<final>(entity):


    @experimental
    fort_item_bandage<public> := class<final>(entity):


    @experimental
    fort_item_cluster_clinger<public> := class<final>(entity):


    @experimental
    fort_item_flowberry<public> := class<final>(entity):


    @experimental
    fort_item_flowberry_fizz<public> := class<final>(entity):


    @experimental
    fort_item_grapple_blade_epic<public> := class<final>(entity):


    @experimental
    fort_item_med_kit<public> := class<final>(entity):


    @experimental
    fort_item_modular_enforcer_ar_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_enforcer_ar_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_enforcer_ar_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_enforcer_ar_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_enforcer_ar_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_frenzy_auto_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_frenzy_auto_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_frenzy_auto_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_frenzy_auto_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_frenzy_auto_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_hammer_pump_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_hammer_pump_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_hammer_pump_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_hammer_pump_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_hammer_pump_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_hyper_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_hyper_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_hyper_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_hyper_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_hyper_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_nemesis_ar_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_nemesis_ar_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_nemesis_ar_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_nemesis_ar_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_nemesis_ar_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_ranger_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_ranger_pistol_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_ranger_pistol_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_ranger_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_ranger_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_striker_ar_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_striker_ar_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_striker_ar_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_striker_ar_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_striker_ar_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_thunder_burst_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_thunder_burst_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_thunder_burst_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_thunder_burst_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_thunder_burst_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_montagues_modular_nemesis_ar_mythic<public> := class<final>(entity):


    @experimental
    fort_item_nishas_modular_striker_ar_mythic<public> := class<final>(entity):


    @experimental
    fort_item_oscars_modular_frenzy_auto_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_reaper_modular_sniper_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_reaper_modular_sniper_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_reaper_modular_sniper_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_reaper_modular_sniper_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_shield_potion<public> := class<final>(entity):


    @experimental
    fort_item_small_shield_potion<public> := class<final>(entity):


    @experimental
    fort_item_valerias_modular_hyper_smg_mythic<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/VibinItems
VibinItems<public> := module:
    @experimental
    fort_item_charge_smg_common<public> := class<final>(entity):


    @experimental
    fort_item_charge_smg_epic<public> := class<final>(entity):


    @experimental
    fort_item_charge_smg_legendary<public> := class<final>(entity):


    @experimental
    fort_item_charge_smg_mythic<public> := class<final>(entity):


    @experimental
    fort_item_charge_smg_rare<public> := class<final>(entity):


    @experimental
    fort_item_charge_smg_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_dmr_common<public> := class<final>(entity):


    @experimental
    fort_item_dmr_epic<public> := class<final>(entity):


    @experimental
    fort_item_dmr_legendary<public> := class<final>(entity):


    @experimental
    fort_item_dmr_mythic<public> := class<final>(entity):


    @experimental
    fort_item_dmr_rare<public> := class<final>(entity):


    @experimental
    fort_item_dmr_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_firework_flare_gun_rare<public> := class<final>(entity):


    @experimental
    fort_item_frozen_icecream_cone<public> := class<final>(entity):


    @experimental
    fort_item_grapple_glove<public> := class<final>(entity):


    @experimental
    fort_item_guzzling_icecream_cone<public> := class<final>(entity):


    @experimental
    fort_item_hammer_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_hammer_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_hammer_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_hammer_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_hammer_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_hammer_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_icecream_cone<public> := class<final>(entity):


    @experimental
    fort_item_lilwhips_special_serve<public> := class<final>(entity):


    @experimental
    fort_item_prime_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_prime_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_prime_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_prime_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_prime_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_prime_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_ripsaw_launcher_rare<public> := class<final>(entity):


    @experimental
    fort_item_spicy_icecream_cone<public> := class<final>(entity):


    @experimental
    fort_item_two_shot_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_two_shot_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_two_shot_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_two_shot_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_two_shot_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_two_shot_shotgun_uncommon<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/WildsItems
WildsItems<public> := module:
    @experimental
    fort_item_cloak_gauntlets<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_drum_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_enhanced_flapjack_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_explosive_repeater_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_explosive_repeater_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_explosive_repeater_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_explosive_repeater_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_explosive_repeater_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_explosive_repeater_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_flapjack_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_flapjack_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_flapjack_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_flapjack_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_flapjack_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_kinetic_boomerang_epic<public> := class<final>(entity):


    @experimental
    fort_item_mammoth_pistol_common<public> := class<final>(entity):


    @experimental
    fort_item_mammoth_pistol_epic<public> := class<final>(entity):


    @experimental
    fort_item_mammoth_pistol_legendary<public> := class<final>(entity):


    @experimental
    fort_item_mammoth_pistol_rare<public> := class<final>(entity):


    @experimental
    fort_item_mammoth_pistol_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_sharp_tooth_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_sharp_tooth_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_sharp_tooth_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_sharp_tooth_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_slap_splash<public> := class<final>(entity):


    @experimental
    fort_item_super_slap_splash<public> := class<final>(entity):


    @experimental
    fort_item_thermal_dmr_common<public> := class<final>(entity):


    @experimental
    fort_item_thermal_dmr_epic<public> := class<final>(entity):


    @experimental
    fort_item_thermal_dmr_legendary<public> := class<final>(entity):


    @experimental
    fort_item_thermal_dmr_mythic<public> := class<final>(entity):


    @experimental
    fort_item_thermal_dmr_rare<public> := class<final>(entity):


    @experimental
    fort_item_thermal_dmr_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_wildguard_reliks_cloak_gauntlets<public> := class<final>(entity):


    @experimental
    fort_item_wildwasp_jar<public> := class<final>(entity):


# Module import path: /Fortnite.com/Itemization/WreckedItems
WreckedItems<public> := module:
    @experimental
    fort_item_heavy_impact_sniper_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_heavy_impact_sniper_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_heavy_impact_sniper_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_megalo_dons_modular_combat_shotgun_mythic<public> := class<final>(entity):


    @experimental
    fort_item_megalo_dons_nitro_fists_mythic<public> := class<final>(entity):


    @experimental
    fort_item_modular_boom_bolt_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_boom_bolt_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_boom_bolt_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_combat_assault_rifle_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_combat_assault_rifle_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_combat_assault_rifle_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_combat_assault_rifle_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_combat_assault_rifle_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_combat_shotgun_common<public> := class<final>(entity):


    @experimental
    fort_item_modular_combat_shotgun_epic<public> := class<final>(entity):


    @experimental
    fort_item_modular_combat_shotgun_legendary<public> := class<final>(entity):


    @experimental
    fort_item_modular_combat_shotgun_rare<public> := class<final>(entity):


    @experimental
    fort_item_modular_combat_shotgun_uncommon<public> := class<final>(entity):


    @experimental
    fort_item_modular_conductor_hand_cannon_mythic<public> := class<final>(entity):


    @experimental
    fort_item_nitro_fists_epic<public> := class<final>(entity):


    @experimental
    fort_item_nitro_splash<public> := class<final>(entity):


    @experimental
    fort_item_ringmasters_modular_boom_bolt_mythic<public> := class<final>(entity):


    @experimental
    fort_item_the_machinists_modular_combat_assault_rifle_mythic<public> := class<final>(entity):


    @experimental
    fort_item_tow_hook_cannon_rare<public> := class<final>(entity):


play_animation_on_self<epic_internal> := class(ability):
    GameplayAbilityPath<override>:?string = external {}