# Verse path: /Fortnite.com/Marketplace
using {/UnrealEngine.com/Marketplace}
@deprecated {Message := "Use `offer_interactable_component` from the /UnrealEngine.com/Marketplace module instead."}
# DEPRECATED - Use `offer_interactable_component` from the /UnrealEngine.com/Marketplace module instead.
(/Fortnite.com/Marketplace:)offer_interactable_component<public> := (/UnrealEngine.com/Marketplace:)offer_interactable_component