{
	"Title": "NPC Behavior Basic",
	"Description": "Create a new Verse-authored NPC behavior with minimal code to be used within an NPC Spawner Device's NPC Behavior Script Override or an NPC Character Definition. It also creates an NPC Spawner device when placed in the level.",
	"IsComponent": false,
	"SortPriority": 31,
	"Replacements": [
		{
			"Title": "NPC Behavior Name",
			"Token": "new_npc_behavior_basic"
		}
	]
}