{
	"Title": "NPC Behavior",
	"Description": "Create a new Verse-authored NPC behavior with detailed examples to be used within an NPC Spawner Device's NPC Behavior Script Override or an NPC Character Definition. It also creates an NPC spawner device when placed in the level.",
	"IsComponent": false,
	"SortPriority": 30,
	"Replacements": [
		{
			"Title": "NPC Behavior Name",
			"Token": "new_npc_behavior"
		}
	]
}