# Verse path: /Fortnite.com
# Module import path: /Fortnite.com/Items
Items<public> := module:
    # Module import path: /Fortnite.com/Items/LEGO
    (/Fortnite.com/Items:)LEGO<public> := module:
        using {/Verse.org/SceneGraph}
        Apple_V1_Common<public> := class<final><concrete>(entity):


        Banana_V1_Common<public> := class<final><concrete>(entity):


        ChronosteelShard_V1_Epic<public> := class<final><concrete>(entity):


        Coconut_V1_Common<public> := class<final><concrete>(entity):


        Corn_V1_Common<public> := class<final><concrete>(entity):


        Diamond_V1_Epic<public> := class<final><concrete>(entity):


        GoldStud_V1_Common<public> := class<final><concrete>(entity):


        HealEgg_V1_Uncommon<public> := class<final><concrete>(entity):


        ImpulseGrenade_V1_Rare<public> := class<final><concrete>(entity):


        LegacySlurpJuice_V1_Rare<public> := class<final><concrete>(entity):


        Meat_V1_Uncommon<public> := class<final><concrete>(entity):


        MechanicalParts_V1_Rare<public> := class<final><concrete>(entity):


        MonsterShard_V1_Common<public> := class<final><concrete>(entity):


        PatchworkTool_V1_Rare<public> := class<final><concrete>(entity):


        Pizza_V1_Rare<public> := class<final><concrete>(entity):


        Pumpkin_V1_Common<public> := class<final><concrete>(entity):


        RedMushroom_V1_Uncommon<public> := class<final><concrete>(entity):


        ShockwaveGrenade_V1_Epic<public> := class<final><concrete>(entity):


        SlapBerry_V1_Uncommon<public> := class<final><concrete>(entity):


        SlapJuice_V1_Rare<public> := class<final><concrete>(entity):


        SpinjitzuScroll_V1_Rare<public> := class<final><concrete>(entity):


        VampireTooth_V1_Rare<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Weapons
Weapons<public> := module:
    # Module import path: /Fortnite.com/Weapons/LEGO
    (/Fortnite.com/Weapons:)LEGO<public> := module:
        using {/Verse.org/SceneGraph}
        AmmoCrossbowAmmo_V1_Common<public> := class<final><concrete>(entity):


        AmmoEnergyAmmo_V1_Common<public> := class<final><concrete>(entity):


        AmmoHeavyAmmo_V1_Common<public> := class<final><concrete>(entity):


        AmmoLauncherAmmo_V1_Common<public> := class<final><concrete>(entity):


        AmmoLightAmmo_V1_Common<public> := class<final><concrete>(entity):


        AmmoMediumAmmo_V1_Common<public> := class<final><concrete>(entity):


        AmmoShellAmmo_V1_Common<public> := class<final><concrete>(entity):


        BurstPulseRifle_V1_Rare<public> := class<final><concrete>(entity):


        BurstPulseRifle_V1_Epic<public> := class<final><concrete>(entity):


        BurstPulseRifle_V1_Legendary<public> := class<final><concrete>(entity):


        BurstPulseRifle_V1_Mythic<public> := class<final><concrete>(entity):


        BurstPulseRifle_V1_Exotic<public> := class<final><concrete>(entity):


        Crossbow_V1_Common<public> := class<final><concrete>(entity):


        Crossbow_V1_Uncommon<public> := class<final><concrete>(entity):


        Crossbow_V1_Rare<public> := class<final><concrete>(entity):


        Crossbow_V1_Epic<public> := class<final><concrete>(entity):


        Crossbow_V1_Legendary<public> := class<final><concrete>(entity):


        CXBurstLaserMk1_V1_Common<public> := class<final><concrete>(entity):


        CXBurstLaserMk2_V1_Uncommon<public> := class<final><concrete>(entity):


        CXBurstLaserMk3_V1_Rare<public> := class<final><concrete>(entity):


        CXBurstLaserMk4_V1_Epic<public> := class<final><concrete>(entity):


        CXPulseLaserMk1_V1_Common<public> := class<final><concrete>(entity):


        CXPulseLaserMk2_V1_Uncommon<public> := class<final><concrete>(entity):


        CXPulseLaserMk3_V1_Rare<public> := class<final><concrete>(entity):


        CXPulseLaserMk4_V1_Epic<public> := class<final><concrete>(entity):


        CXPulseLaserMk5_V1_Legendary<public> := class<final><concrete>(entity):


        DoubleSaucer_V1_Common<public> := class<final><concrete>(entity):


        DoubleSaucer_V1_Uncommon<public> := class<final><concrete>(entity):


        DoubleSaucer_V1_Rare<public> := class<final><concrete>(entity):


        DoubleSaucer_V1_Epic<public> := class<final><concrete>(entity):


        ExplosiveGooGun_V1_Rare<public> := class<final><concrete>(entity):


        GoodOlTrusty_V1_Common<public> := class<final><concrete>(entity):


        GoodOlTrusty_V1_Uncommon<public> := class<final><concrete>(entity):


        GoodOlTrusty_V1_Rare<public> := class<final><concrete>(entity):


        Grappler_V1_Epic<public> := class<final><concrete>(entity):


        HandAxe_V1_Common<public> := class<final><concrete>(entity):


        HandAxe_V1_Uncommon<public> := class<final><concrete>(entity):


        HandAxe_V1_Rare<public> := class<final><concrete>(entity):


        HandAxe_V1_Epic<public> := class<final><concrete>(entity):


        HandAxe_V1_Legendary<public> := class<final><concrete>(entity):


        Katana_V1_Common<public> := class<final><concrete>(entity):


        Katana_V1_Uncommon<public> := class<final><concrete>(entity):


        Katana_V1_Rare<public> := class<final><concrete>(entity):


        Katana_V1_Epic<public> := class<final><concrete>(entity):


        Katana_V1_Legendary<public> := class<final><concrete>(entity):


        KineticBlade_V1_Rare<public> := class<final><concrete>(entity):


        KineticBlade_V1_Epic<public> := class<final><concrete>(entity):


        KineticBlade_V1_Legendary<public> := class<final><concrete>(entity):


        KymeraRayGun_V1_Rare<public> := class<final><concrete>(entity):


        KymeraRayGun_V1_Epic<public> := class<final><concrete>(entity):


        KymeraRayGun_V1_Legendary<public> := class<final><concrete>(entity):


        KymeraRayGun_V1_Mythic<public> := class<final><concrete>(entity):


        Nunchucks_V1_Common<public> := class<final><concrete>(entity):


        Nunchucks_V1_Uncommon<public> := class<final><concrete>(entity):


        Nunchucks_V1_Rare<public> := class<final><concrete>(entity):


        Nunchucks_V1_Epic<public> := class<final><concrete>(entity):


        Nunchucks_V1_Legendary<public> := class<final><concrete>(entity):


        OverclockedCXBurstLaser_V1_Legendary<public> := class<final><concrete>(entity):


        OverclockedCXPulseLaser_V1_Mythic<public> := class<final><concrete>(entity):


        PropOMatic_V1_Rare<public> := class<final><concrete>(entity):


        PrototypePulseRifleX2_V1_Legendary<public> := class<final><concrete>(entity):


        PulseRifleX2Mk1_V1_Uncommon<public> := class<final><concrete>(entity):


        PulseRifleX2Mk2_V1_Rare<public> := class<final><concrete>(entity):


        PulseRifleX2Mk3_V1_Epic<public> := class<final><concrete>(entity):


        RoyalStingBlaster_V1_Epic<public> := class<final><concrete>(entity):


        RoyalStingBlaster_V1_Legendary<public> := class<final><concrete>(entity):


        Scythe_V1_Common<public> := class<final><concrete>(entity):


        Scythe_V1_Uncommon<public> := class<final><concrete>(entity):


        Scythe_V1_Rare<public> := class<final><concrete>(entity):


        Scythe_V1_Epic<public> := class<final><concrete>(entity):


        Scythe_V1_Legendary<public> := class<final><concrete>(entity):


        Shurikens_V1_Common<public> := class<final><concrete>(entity):


        Shurikens_V1_Uncommon<public> := class<final><concrete>(entity):


        Shurikens_V1_Rare<public> := class<final><concrete>(entity):


        Shurikens_V1_Epic<public> := class<final><concrete>(entity):


        Shurikens_V1_Legendary<public> := class<final><concrete>(entity):


        SnowballLauncher_V1_Uncommon<public> := class<final><concrete>(entity):


        SnowballLauncher_V1_Rare<public> := class<final><concrete>(entity):


        SnowballLauncher_V1_Epic<public> := class<final><concrete>(entity):


        SnowballLauncher_V1_Legendary<public> := class<final><concrete>(entity):


        StingBlaster_V1_Common<public> := class<final><concrete>(entity):


        StingBlaster_V1_Uncommon<public> := class<final><concrete>(entity):


        StingBlaster_V1_Rare<public> := class<final><concrete>(entity):


        SuperSaucer_V1_Legendary<public> := class<final><concrete>(entity):


        SuperSaucer_V1_Exotic<public> := class<final><concrete>(entity):


        Sword_V1_Common<public> := class<final><concrete>(entity):


        Sword_V1_Uncommon<public> := class<final><concrete>(entity):


        Sword_V1_Rare<public> := class<final><concrete>(entity):


        Sword_V1_Epic<public> := class<final><concrete>(entity):


        Sword_V1_Legendary<public> := class<final><concrete>(entity):
