# Verse path: /Fortnite.com
# Module import path: /Fortnite.com/Items
Items<public> := module:
    # Module import path: /Fortnite.com/Items/TMNT
    (/Fortnite.com/Items:)TMNT<public> := module:
        using {/Verse.org/SceneGraph}
        TMNTPizzaParty_V1_Epic<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Weapons
Weapons<public> := module:
    # Module import path: /Fortnite.com/Weapons/TMNT
    (/Fortnite.com/Weapons:)TMNT<public> := module:
        using {/Verse.org/SceneGraph}
        DonatellosStaff_V1_Mythic<public> := class<final><concrete>(entity):


        LeonardosKatanas_V1_Mythic<public> := class<final><concrete>(entity):


        MichelangelosNunchaku_V1_Mythic<public> := class<final><concrete>(entity):


        RaphaelsSai_V1_Mythic<public> := class<final><concrete>(entity):
