# Verse path: /Fortnite.com
# Module import path: /Fortnite.com/Items
Items<public> := module:
    # Module import path: /Fortnite.com/Items/SquidGame
    SquidGame<public> := module:
        using {/Verse.org/SceneGraph}
        DdakjiBlue_V1_Common<public> := class<final><concrete>(entity):


        DdakjiRed_V1_Common<public> := class<final><concrete>(entity):


        DisguiseFrontMan_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseGamesGuardManager_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseGamesGuardSoldier_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseGamesGuardWorker_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseGamesManager_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseGamesPlayer_V1_Rare<public> := class<final><concrete>(entity):


        FlyingStone_V1_Common<public> := class<final><concrete>(entity):


        Invitation_V1_Legendary<public> := class<final><concrete>(entity):
