# Verse path: /Fortnite.com
# Module import path: /Fortnite.com/Items
Items<public> := module:
    # Module import path: /Fortnite.com/Items/KPopDemonHunters
    (/Fortnite.com/Items:)KPopDemonHunters<public> := module:
        using {/Verse.org/SceneGraph}
        MirasXTraSpicyRamyeon_V1_Epic<public> := class<final><concrete>(entity):


        TigersTeleportingMask_V1_Epic<public> := class<final><concrete>(entity):


        ZoeysBubbleShield_V1_Legendary<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Weapons
Weapons<public> := module:
    # Module import path: /Fortnite.com/Weapons/KPopDemonHunters
    (/Fortnite.com/Weapons:)KPopDemonHunters<public> := module:
        using {/Verse.org/SceneGraph}
        RumisEmpoweredSword_V1_Mythic<public> := class<final><concrete>(entity):
