# Module import path: /UnrealEngine.com/BasicShapes
BasicShapes<public> := module:
    using {/Verse.org/SceneGraph}
    cube<public> := class<final><public>(mesh_component):


    sphere<public> := class<final><public>(mesh_component):


    plane<public> := class<final><public>(mesh_component):


    cone<public> := class<final><public>(mesh_component):


    cylinder<public> := class<final><public>(mesh_component):


@deprecated
# Module import path: /UnrealEngine.com/SceneGraph
(/UnrealEngine.com:)SceneGraph<public> := module:
