# Module import path: /Verse.org/Assets
Assets<public> := module:
    animation_sequence<native><public> := class<computes><final><epic_internal>:


    material<native><public> := class<epic_internal>:


    particle_system<native><public> := class<computes><final><epic_internal>:


    mesh<native><public> := class<computes><epic_internal>:


    sound_wave<native><public> := class<computes><final><epic_internal>:


    texture<native><public> := class<computes><final><epic_internal>:
