# Module import path: /Fortnite.com/Items
Items<public> := module:
    # Module import path: /Fortnite.com/Items/StarWars
    (/Fortnite.com/Items:)StarWars<public> := module:
        using {/Verse.org/Native}
        using {/Verse.org/SceneGraph}
        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        Jetpack_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Lightning as an augment item. Only usable with a lightsaber equipped.
        ForcePowerLightning_LightsaberAugment_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Push as an augment item. Only usable with a lightsaber equipped.
        ForcePowerPush_LightsaberAugment_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Pull as an augment item. Only usable with a lightsaber equipped.
        ForcePowerPull_LightsaberAugment_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Throw as an augment item. Only usable with a lightsaber equipped.
        ForcePowerThrow_LightsaberAugment_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Shield as an augment item. Only usable with a lightsaber equipped.
        ForcePowerShield_LightsaberAugment_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Heal as an augment item. Only usable with a lightsaber equipped.
        ForcePowerHeal_LightsaberAugment_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Training (Jump & Sprint) as an augment item.
        ForcePowerTraining_Augment_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Awareness as an augment item. Only usable with a lightsaber equipped.
        ForcePowerAwareness_LightsaberAugment_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Mind Trick as an augment item. Only usable with a lightsaber equipped.
        ForcePowerTrick_LightsaberAugment_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Distraction as an augment item. Only usable with a lightsaber equipped.
        ForcePowerDistraction_LightsaberAugment_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Saber Throw as an augment item. Only usable with a lightsaber equipped.
        ForcePowerSaberThrow_LightsaberAugment_V1<native><public> := class<concrete><final>(entity):


# Module import path: /Fortnite.com/Weapons
Weapons<public> := module:
    # Module import path: /Fortnite.com/Weapons/StarWars
    (/Fortnite.com/Weapons:)StarWars<public> := module:
        using {/Verse.org/Native}
        using {/Verse.org/SceneGraph}
        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        AmbanSniperRifle_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        AmbanSniperRifle_InfiniteAmmo_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        E11BlasterRifle_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DC15BlasterRifle_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        BARMST12ScatterBlaster_V1_Common<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        BARMST12ScatterBlaster_V1_Uncommon<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        BARMST12ScatterBlaster_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        BARMST12ScatterBlaster_V1_Epic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        BARMST12ScatterBlaster_V1_Legendary<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        BARMST12ScatterBlaster_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CR2Blaster_V1_Common<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CR2Blaster_V1_Uncommon<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CR2Blaster_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CR2Blaster_V1_Epic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CR2Blaster_V1_Legendary<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CR2Blaster_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DLT19BlasterRifle_V1_Common<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DLT19BlasterRifle_V1_Uncommon<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DLT19BlasterRifle_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DLT19BlasterRifle_V1_Epic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DLT19BlasterRifle_V1_Legendary<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DLT19BlasterRifle_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        ACPScatterBlaster_V1_Common<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        ACPScatterBlaster_V1_Uncommon<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        ACPScatterBlaster_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        ACPScatterBlaster_V1_Epic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        ACPScatterBlaster_V1_Legendary<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        ACPScatterBlaster_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        A280CFEBlasterRifle_V1_Common<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        A280CFEBlasterRifle_V1_Uncommon<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        A280CFEBlasterRifle_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        A280CFEBlasterRifle_V1_Epic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        A280CFEBlasterRifle_V1_Legendary<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        A280CFEBlasterRifle_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CA87JawaScatterBlaster_V1_Common<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CA87JawaScatterBlaster_V1_Uncommon<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CA87JawaScatterBlaster_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CA87JawaScatterBlaster_V1_Epic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CA87JawaScatterBlaster_V1_Legendary<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        CA87JawaScatterBlaster_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WESTAR34BlasterPistols_V1_Common<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WESTAR34BlasterPistols_V1_Uncommon<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WESTAR34BlasterPistols_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WESTAR34BlasterPistols_V1_Epic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WESTAR34BlasterPistols_V1_Legendary<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WESTAR34BlasterPistols_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        IQA11MarksmanBlasterRifle_V1_Common<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        IQA11MarksmanBlasterRifle_V1_Uncommon<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        IQA11MarksmanBlasterRifle_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        IQA11MarksmanBlasterRifle_V1_Epic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        IQA11MarksmanBlasterRifle_V1_Legendary<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        IQA11MarksmanBlasterRifle_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DL44BlasterPistol_V1_Common<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DL44BlasterPistol_V1_Uncommon<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DL44BlasterPistol_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DL44BlasterPistol_V1_Epic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DL44BlasterPistol_V1_Legendary<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        DL44BlasterPistol_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        F11DBlaster_V1_Common<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        F11DBlaster_V1_Uncommon<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        F11DBlaster_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        F11DBlaster_V1_Epic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        F11DBlaster_V1_Legendary<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        F11DBlaster_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WookieeBowcaster_V1_Common<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WookieeBowcaster_V1_Uncommon<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WookieeBowcaster_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WookieeBowcaster_V1_Epic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WookieeBowcaster_V1_Legendary<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        WookieeBowcaster_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        ThermalImploder_V1_Rare<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        ThermalImploder_V1_Mythic<public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Lightning as a weapon item. Must be equipped to use.
        ForcePowerLightning_Weapon_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Push as a weapon item. Must be equipped to use.
        ForcePowerPush_Weapon_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Pull as a weapon item. Must be equipped to use.
        ForcePowerPull_Weapon_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Throw as a weapon item. Must be equipped to use.
        ForcePowerThrow_Weapon_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Shield as a weapon item. Must be equipped to use.
        ForcePowerShield_Weapon_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Heal as a weapon item. Must be equipped to use.
        ForcePowerHeal_Weapon_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Awareness as a weapon item. Must be equipped to use.
        ForcePowerAwareness_Weapon_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Mind Trick as a weapon item. Must be equipped to use.
        ForcePowerTrick_Weapon_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Distraction as a weapon item. Must be equipped to use.
        ForcePowerDistraction_Weapon_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        # Force Saber Throw as a weapon item. Must be equipped to use.
        ForcePowerSaberThrow_Weapon_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        LightsaberKenobi_V1<native><public> := class<final><concrete>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        LightsaberRen_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        LightsaberRey_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        LightsaberSkywalker_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        LightsaberVader_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        LightsaberWindu_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        LightsaberJediPadawanA_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        LightsaberJediPadawanB_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        LightsaberJediTraining_V1<native><public> := class<concrete><final>(entity):


        @available {MinUploadedAtFNVersion := 4020}
        @experimental
        LightsaberSithApprentice_V1<native><public> := class<concrete><final>(entity):
