# Verse path: /Fortnite.com
# Module import path: /Fortnite.com/Items
Items<public> := module:
    # Module import path: /Fortnite.com/Items/StarWars
    (/Fortnite.com/Items:)StarWars<public> := module:
        using {/Verse.org/SceneGraph}
        CivilianFemaleDelta_V1_Rare<public> := class<final><concrete>(entity):


        CivilianFemaleLambda_V1_Rare<public> := class<final><concrete>(entity):


        CivilianFemaleLimit_V1_Rare<public> := class<final><concrete>(entity):


        CivilianFemalePrime_V1_Rare<public> := class<final><concrete>(entity):


        CivilianFemaleSigma_V1_Rare<public> := class<final><concrete>(entity):


        CivilianFemaleVector_V1_Rare<public> := class<final><concrete>(entity):


        CivilianMaleDelta_V1_Rare<public> := class<final><concrete>(entity):


        CivilianMaleLambda_V1_Rare<public> := class<final><concrete>(entity):


        CivilianMaleLimit_V1_Rare<public> := class<final><concrete>(entity):


        CivilianMalePrime_V1_Rare<public> := class<final><concrete>(entity):


        CivilianMaleSigma_V1_Rare<public> := class<final><concrete>(entity):


        CivilianMaleVector_V1_Rare<public> := class<final><concrete>(entity):


        Disguise212thBattalionTrooper_V1_Rare<public> := class<final><concrete>(entity):


        Disguise501stTrooper_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseAhsokasCloneTrooper_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseAWRTrooper_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseCloneTrooper_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseCoruscantGuard_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseFirstOrderStormtrooper_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianHonor_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianHonorGreen_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianHonorYellow_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianLoyalty_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianLoyaltyBlue_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianLoyaltyGold_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianSpirit_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianSpiritGreen_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianSpiritRed_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianStrength_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianStrengthBlue_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseMandalorianStrengthRed_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperFemaleArctic_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperFemaleDeckside_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperFemaleDust_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperFemaleForest_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperFemaleOcean_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperFemaleSand_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperFemaleTundra_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperMaleArctic_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperMaleDeckside_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperMaleDust_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperMaleForest_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperMaleOcean_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperMaleSand_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseRebelTrooperMaleTundra_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseSithTrooper_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseStormtrooper_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseStormtrooperSamurai_V1_Rare<public> := class<final><concrete>(entity):


        DisguiseWolfPackTrooper_V1_Rare<public> := class<final><concrete>(entity):


        EnhancedMandalorianJetpack_V1_Mythic<public> := class<final><concrete>(entity):


        ImperialAirStrike_V1_Legendary<public> := class<final><concrete>(entity):


        MoonTraderFemaleDelta_V1_Rare<public> := class<final><concrete>(entity):


        MoonTraderFemaleLambda_V1_Rare<public> := class<final><concrete>(entity):


        MoonTraderFemaleLimit_V1_Rare<public> := class<final><concrete>(entity):


        MoonTraderFemalePrime_V1_Rare<public> := class<final><concrete>(entity):


        MoonTraderFemaleSigma_V1_Rare<public> := class<final><concrete>(entity):


        MoonTraderFemaleVector_V1_Rare<public> := class<final><concrete>(entity):


        MoonTraderMaleDelta_V1_Rare<public> := class<final><concrete>(entity):


        MoonTraderMaleLambda_V1_Rare<public> := class<final><concrete>(entity):


        MoonTraderMaleLimit_V1_Rare<public> := class<final><concrete>(entity):


        MoonTraderMalePrime_V1_Rare<public> := class<final><concrete>(entity):


        MoonTraderMaleSigma_V1_Rare<public> := class<final><concrete>(entity):


        MoonTraderMaleVector_V1_Rare<public> := class<final><concrete>(entity):


        RebelAirStrike_V1_Legendary<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Weapons
Weapons<public> := module:
    # Module import path: /Fortnite.com/Weapons/StarWars
    (/Fortnite.com/Weapons:)StarWars<public> := module:
        using {/Verse.org/SceneGraph}
        DarthVadersLightsaber_V1_Mythic<public> := class<final><concrete>(entity):


        JediPadawanLightsaberBlue_V1_Mythic<public> := class<final><concrete>(entity):


        JediPadawanLightsaberGreen_V1_Mythic<public> := class<final><concrete>(entity):


        JediTrainingLightsaber_V1_Mythic<public> := class<final><concrete>(entity):


        KyloRensLightsaber_V1_Mythic<public> := class<final><concrete>(entity):


        LukesBlueLightsaber_V1_Mythic<public> := class<final><concrete>(entity):


        LukesGreenLightsaber_V1_Mythic<public> := class<final><concrete>(entity):


        MaceWindusLightsaber_V1_Mythic<public> := class<final><concrete>(entity):


        ObiWansLightsaber_V1_Mythic<public> := class<final><concrete>(entity):


        ReysLightsaber_V1_Mythic<public> := class<final><concrete>(entity):


        SithApprenticeLightsaber_V1_Mythic<public> := class<final><concrete>(entity):
