# Module import path: /Fortnite.com/Items
Items<public> := module:
    using {/Verse.org/SceneGraph}
    Acorn_Creative_V1_Common<public> := class<final><concrete>(entity):


    ActivePowercell_Creative_V1_Epic<public> := class<final><concrete>(entity):


    AdhesiveResin_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    AirStrike_BR_CH1S9_Legendary<public> := class<final><concrete>(entity):


    AlienNanites_BR_CH2S7_Common<public> := class<final><concrete>(entity):


    AmmoArrows_BR_CH2S6_Common<public> := class<final><concrete>(entity):


    AmmoHeavyBullets_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    AmmoLightBullets_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    AmmoMediumBullets_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    AmmoRockets_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    AmmoShells_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    AnimalBones_BR_CH2S6_Common<public> := class<final><concrete>(entity):


    Apple_BR_CH1S4_Common<public> := class<final><concrete>(entity):


    ArmoredWall_BR_CH2S8_Uncommon<public> := class<final><concrete>(entity):


    AuthorityKeycard_BR_CH2S3_Legendary<public> := class<final><concrete>(entity):


    Bacon_Creative_V1_Common<public> := class<final><concrete>(entity):


    Balloons_BR_CH1S6_Rare<public> := class<final><concrete>(entity):


    Banana_BR_CH1S8_Common<public> := class<final><concrete>(entity):


    BananaOfTheGods_BR_CH5S2_Legendary<public> := class<final><concrete>(entity):


    Bandage_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    Bandage_BR_CH5S1_Common<public> := class<final><concrete>(entity):


    BandageBazooka_BR_CH2S1_Epic<public> := class<final><concrete>(entity):


    Batteries_Creative_V1_Common<public> := class<final><concrete>(entity):


    BigBushBomb_BR_CH4S1_Rare<public> := class<final><concrete>(entity):


    BirthdayPresents_BR_CH1S9_Legendary<public> := class<final><concrete>(entity):


    BlastPowder_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    BlizzardGrenade_BR_CH6S1_Rare<public> := class<final><concrete>(entity):


    BoarHair_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    BoogieBomb_BR_CH1S2_Rare<public> := class<final><concrete>(entity):


    BoomBox_BR_CH1S7_Epic<public> := class<final><concrete>(entity):


    BottleRockets_BR_CH1S7_Uncommon<public> := class<final><concrete>(entity):


    Bouncer_BR_CH1S4_Rare<public> := class<final><concrete>(entity):


    BrickABunker_BR_CH7S2_Common<public> := class<final><concrete>(entity):


    BubbleShield_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    Bush_BR_CH1S1_Legendary<public> := class<final><concrete>(entity):


    BusinessTurret_BR_CH4S4_Epic<public> := class<final><concrete>(entity):


    Butter_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    Cabbage_BR_CH2S3_Common<public> := class<final><concrete>(entity):


    CandyCorn_BR_CH2S4_Common<public> := class<final><concrete>(entity):


    CattyCornerKeycard_BR_CH2S3_Legendary<public> := class<final><concrete>(entity):


    CeilingZapper_BR_CH1S1_Rare<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use CeilingZapper_BR_CH1S1_Rare instead.
    CeilingZapper_BR_CH4MS1_Rare<public> := class<final><concrete>(entity):


    ChiliChugSplash_BR_CH2S8_Exotic<public> := class<final><concrete>(entity):


    Chiller_BR_CH1S6_Common<public> := class<final><concrete>(entity):


    ChillerGrenade_BR_CH1S7_Common<public> := class<final><concrete>(entity):


    ChugCannon_BR_CH2S5_Exotic<public> := class<final><concrete>(entity):


    ChugJug_BR_CH1S2_Legendary<public> := class<final><concrete>(entity):


    OceansBottomlessChugJug_BR_CH2S3_Mythic<public> := class<final><concrete>(entity):


    ChugJug_BR_CH6S2_Legendary<public> := class<final><concrete>(entity):


    ChugSplash_BR_CH1S9_Rare<public> := class<final><concrete>(entity):


    Clinger_BR_CH1S3_Uncommon<public> := class<final><concrete>(entity):


    CloakGauntlets_BR_CH4S3_Epic<public> := class<final><concrete>(entity):


    WildguardReliksCloakGauntlets_BR_CH4S3_Mythic<public> := class<final><concrete>(entity):


    ClusterClinger_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    Coconut_BR_CH1S8_Common<public> := class<final><concrete>(entity):


    CommandCavernKeycard_BR_CH3S2_Legendary<public> := class<final><concrete>(entity):


    Corn_BR_CH2S3_Common<public> := class<final><concrete>(entity):


    CozyCampfire_BR_CH1S2_Rare<public> := class<final><concrete>(entity):


    CrashPad_BR_CH2S2_Rare<public> := class<final><concrete>(entity):


    CrashPadJr_BR_CH4S4_Uncommon<public> := class<final><concrete>(entity):


    CreepinCardboard_BR_CH2S2_Uncommon<public> := class<final><concrete>(entity):


    QuartzCrystal_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    RainbowCrystal_Creative_V1_Epic<public> := class<final><concrete>(entity):


    ShadowshardCrystal_Creative_V1_Epic<public> := class<final><concrete>(entity):


    SunbeamCrystal_Creative_V1_Epic<public> := class<final><concrete>(entity):


    CuddleFish_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    DamageTrap_BR_CH1S2_Uncommon<public> := class<final><concrete>(entity):


    Decoy_BR_CH2S2_Rare<public> := class<final><concrete>(entity):


    DialADrop_BR_CH3S4_Epic<public> := class<final><concrete>(entity):


    Diamond_Creative_V1_Epic<public> := class<final><concrete>(entity):


    WhiteDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    BrownDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    GreenDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    WhiteSpeckledDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    BrownSpeckledDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    BlueSpeckledDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    WhiteMarbledDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    PinkMarbledDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    GreenMarbledDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    BlueFleckedDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    RedFleckedDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    GreenFleckedDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    WhiteShimmeringDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    BlueShimmeringDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    RedShimmeringDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    GrayEruptionDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    RedEruptionDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    YellowEruptionDinoEgg_Creative_V1_Rare<public> := class<final><concrete>(entity):


    DuctTape_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    Dynamite_BR_CH1S6_Uncommon<public> := class<final><concrete>(entity):


    EnhancedHarpoonGun_BR_CH7S2_Mythic<public> := class<final><concrete>(entity):


    EstateVaultKeycard_BR_CH4S4_Legendary<public> := class<final><concrete>(entity):


    ExoticSlapBerryFizz_BR_CH6S4_Exotic<public> := class<final><concrete>(entity):


    FalconScout_BR_CH4S1_Epic<public> := class<final><concrete>(entity):


    FibrousHerbs_Creative_V1_Common<public> := class<final><concrete>(entity):


    FireflyJar_BR_CH2S3_Rare<public> := class<final><concrete>(entity):


    FireGrenade_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    FireTrap_BR_CH2S4_Uncommon<public> := class<final><concrete>(entity):


    CreativeFishingRod_Creative_V1_Common<public> := class<final><concrete>(entity):


    CreativeProFishingRod_Creative_V1_Rare<public> := class<final><concrete>(entity):


    Flag_Creative_V1_Rare<public> := class<final><concrete>(entity):


    Flashbang_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    Flashlight_Creative_V1_Rare<public> := class<final><concrete>(entity):


    Flopper_BR_CH2S1_Uncommon<public> := class<final><concrete>(entity):


    FlowBerry_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    FlowBerryFizz_BR_CH5S1_Rare<public> := class<final><concrete>(entity):


    FlowBerryMistGrenade_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    FlowerPetals_Creative_V1_Common<public> := class<final><concrete>(entity):


    FortillaKeycard_BR_CH2S3_Legendary<public> := class<final><concrete>(entity):


    FragGrenade_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    FrozenIcecreamCone_BR_CH3S3_Common<public> := class<final><concrete>(entity):


    GasCan_BR_CH2S3_Common<public> := class<final><concrete>(entity):


    Gliders_BR_CH1S7_Rare<public> := class<final><concrete>(entity):


    Gold_BR_CH2S1_Common<public> := class<final><concrete>(entity):


    GoldSplash_BR_CH6S2_Rare<public> := class<final><concrete>(entity):


    GrappleGlider_BR_CH3S4_Epic<public> := class<final><concrete>(entity):


    GrappleGlove_BR_CH3S3_Epic<public> := class<final><concrete>(entity):


    Grappler_BR_CH1S5_Epic<public> := class<final><concrete>(entity):


    Grenade_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    Grenade_BR_CH4MS1_Common<public> := class<final><concrete>(entity):


    Grenade_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    GrottoKeycard_BR_CH2S2_Legendary<public> := class<final><concrete>(entity):


    Grub_Creative_V1_Common<public> := class<final><concrete>(entity):


    GuardianShield_BR_CH4S1_Rare<public> := class<final><concrete>(entity):


    GuzzleJuice_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    GuzzlingIcecreamCone_BR_CH3S3_Uncommon<public> := class<final><concrete>(entity):


    HarpoonGun_BR_CH2S1_Rare<public> := class<final><concrete>(entity):


    HealEgg_BR_CH4S2_Uncommon<public> := class<final><concrete>(entity):


    Herb_Creative_V1_Common<public> := class<final><concrete>(entity):


    HolidayPresents_BR_CH2S5_Legendary<public> := class<final><concrete>(entity):


    Honey_Creative_V1_Rare<public> := class<final><concrete>(entity):


    HopDrop_BR_CH2S4_Common<public> := class<final><concrete>(entity):


    HopEgg_BR_CH4S2_Rare<public> := class<final><concrete>(entity):


    HopFlopper_BR_CH2S4_Epic<public> := class<final><concrete>(entity):


    IcecreamCone_BR_CH3S3_Common<public> := class<final><concrete>(entity):


    IcyGrappler_BR_CH2S8_Exotic<public> := class<final><concrete>(entity):


    ImpulseGrenade_BR_CH1S2_Rare<public> := class<final><concrete>(entity):


    ImpulseGrenade_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    InflateABull_BR_CH2S7_Rare<public> := class<final><concrete>(entity):


    JellyBean_BR_CH2S4_Common<public> := class<final><concrete>(entity):


    Jellyfish_BR_CH2S4_Rare<public> := class<final><concrete>(entity):


    Jetpack_BR_CH1S4_Legendary<public> := class<final><concrete>(entity):


    Jewel_Creative_V1_Rare<public> := class<final><concrete>(entity):


    JulesGliderGun_BR_CH2S3_Mythic<public> := class<final><concrete>(entity):


    JunkRift_BR_CH1SX_Epic<public> := class<final><concrete>(entity):


    Key_BR_CH3S4_Rare<public> := class<final><concrete>(entity):


    LaunchPad_BR_CH3S4_Rare<public> := class<final><concrete>(entity):


    SuperLaunchPad_Creative_V1_Epic<public> := class<final><concrete>(entity):


    LawlessRiftLauncher_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    LawlessSlapCannon_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    LawlessSlapJug_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    LemonLime_Creative_V1_Common<public> := class<final><concrete>(entity):


    LilWhipsSpecialServe_BR_CH3S3_Legendary<public> := class<final><concrete>(entity):


    LimitlessSevenSliders_BR_CH7S3_Mythic<public> := class<final><concrete>(entity):


    LumpOfCoal_BR_CH2S1_Common<public> := class<final><concrete>(entity):


    MapleSyrup_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    Meat_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    MechanicalParts_BR_CH2S6_Common<public> := class<final><concrete>(entity):


    RustyMechanicalParts_Creative_V1_Rare<public> := class<final><concrete>(entity):


    SimpleMechanicalParts_Creative_V1_Rare<public> := class<final><concrete>(entity):


    SturdyMechanicalParts_Creative_V1_Rare<public> := class<final><concrete>(entity):


    SleekMechanicalParts_Creative_V1_Rare<public> := class<final><concrete>(entity):


    EfficientMechanicalParts_Creative_V1_Rare<public> := class<final><concrete>(entity):


    VindertechMechanicalParts_Creative_V1_Rare<public> := class<final><concrete>(entity):


    MedMist_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    MedMistSmokeGrenade_BR_CH6S2_Rare<public> := class<final><concrete>(entity):


    MedKit_BR_PreSeason_Uncommon<public> := class<final><concrete>(entity):


    MedKit_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    Metal_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    MidasFlopper_BR_CH2S4_Legendary<public> := class<final><concrete>(entity):


    Milk_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    RoughMineralPowder_Creative_V1_Common<public> := class<final><concrete>(entity):


    SimpleMineralPowder_Creative_V1_Common<public> := class<final><concrete>(entity):


    FineGrainMineralPowder_Creative_V1_Common<public> := class<final><concrete>(entity):


    CharBlackMineralPowder_Creative_V1_Common<public> := class<final><concrete>(entity):


    OxidizedMineralPowder_Creative_V1_Common<public> := class<final><concrete>(entity):


    MonsterParts_BR_CH2S8_Common<public> := class<final><concrete>(entity):


    BlueMushroom_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    PinkMushroom_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    RedMushroom_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    WhiteMushroom_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    YellowMushroom_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    MystForm_BR_CH6S3_Epic<public> := class<final><concrete>(entity):


    MythicGoldfish_BR_CH2S1_Mythic<public> := class<final><concrete>(entity):


    NitroSplash_BR_CH5S3_Rare<public> := class<final><concrete>(entity):


    OrangePaintGrenade_BR_CH2S2_Rare<public> := class<final><concrete>(entity):


    RoughOre_Creative_V1_Common<public> := class<final><concrete>(entity):


    Coal_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    BrightcoreOre_Creative_V1_Epic<public> := class<final><concrete>(entity):


    CopperOre_Creative_V1_Epic<public> := class<final><concrete>(entity):


    MalachiteOre_Creative_V1_Epic<public> := class<final><concrete>(entity):


    ObsidianOre_Creative_V1_Epic<public> := class<final><concrete>(entity):


    SilverOre_Creative_V1_Epic<public> := class<final><concrete>(entity):


    SpectroliteOre_Creative_V1_Epic<public> := class<final><concrete>(entity):


    Overdrive_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    OverdriveGrenade_BR_CH7S2_Rare<public> := class<final><concrete>(entity):


    PatchworkTool_Creative_V1_Rare<public> := class<final><concrete>(entity):


    Pepper_BR_CH1S8_Common<public> := class<final><concrete>(entity):


    PepperMint_BR_CH2S4_Common<public> := class<final><concrete>(entity):


    PizzaParty_BR_CH3S1_Epic<public> := class<final><concrete>(entity):


    PizzaSlice_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    Planks_Creative_V1_Common<public> := class<final><concrete>(entity):


    PoisonDartTrap_BR_CH1S8_Uncommon<public> := class<final><concrete>(entity):


    PortABunker_BR_CH3S4_Uncommon<public> := class<final><concrete>(entity):


    PortACover_BR_CH6S2_Rare<public> := class<final><concrete>(entity):


    PortAFort_BR_CH1S3_Rare<public> := class<final><concrete>(entity):


    PortAFortress_BR_CH1S5_Legendary<public> := class<final><concrete>(entity):


    PrecisionAirStrike_BR_CH6S4_Legendary<public> := class<final><concrete>(entity):


    Presents_BR_CH1S7_Legendary<public> := class<final><concrete>(entity):


    PropOMatic_Creative_V1_Rare<public> := class<final><concrete>(entity):


    ProximityMine_BR_CH2S2_Rare<public> := class<final><concrete>(entity):


    ProximityMine_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    PulseScanner_BR_CH6S2_Epic<public> := class<final><concrete>(entity):


    Pumpkin_Creative_V1_Common<public> := class<final><concrete>(entity):


    PurplePaintGrenade_BR_CH2S2_Rare<public> := class<final><concrete>(entity):


    RaptorEye_Creative_V1_Rare<public> := class<final><concrete>(entity):


    ReconGrenade_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    RemoteExplosives_BR_CH1S3_Epic<public> := class<final><concrete>(entity):


    RepairTorch_BR_CH3S2_Rare<public> := class<final><concrete>(entity):


    RiftToGo_BR_CH1S5_Epic<public> := class<final><concrete>(entity):


    RiftFish_BR_CH2S5_Epic<public> := class<final><concrete>(entity):


    RiftPointDevice_Ballistic_V1_Exotic<public> := class<final><concrete>(entity):


    RigKeycard_BR_CH2S2_Legendary<public> := class<final><concrete>(entity):


    RoastedChicken_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    RotatingGizmo_Creative_V1_Rare<public> := class<final><concrete>(entity):


    RustyCan_BR_CH2S1_Common<public> := class<final><concrete>(entity):


    SevenSliders_BR_CH7S3_Epic<public> := class<final><concrete>(entity):


    ShadowBomb_BR_CH1S8_Uncommon<public> := class<final><concrete>(entity):


    ShadowFlopper_BR_CH2S8_Rare<public> := class<final><concrete>(entity):


    SharkKeycard_BR_CH2S2_Legendary<public> := class<final><concrete>(entity):


    SharkTooth_Creative_V1_Rare<public> := class<final><concrete>(entity):


    ShieldBreakerEMP_BR_CH4S4_Rare<public> := class<final><concrete>(entity):


    ShieldBubble_BR_CH1SX_Rare<public> := class<final><concrete>(entity):


    ShieldBubbleJr_BR_CH5S2_Uncommon<public> := class<final><concrete>(entity):


    ShieldFish_BR_CH2S4_Rare<public> := class<final><concrete>(entity):


    ShieldKeg_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    ShieldMushroom_BR_CH1S4_Common<public> := class<final><concrete>(entity):


    ShieldPotion_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    ShieldPotion_BR_CH5S1_Rare<public> := class<final><concrete>(entity):


    ShockwaveGrenade_BR_CH1S5_Epic<public> := class<final><concrete>(entity):


    Shove_Creative_V1_Common<public> := class<final><concrete>(entity):


    SignalRemote_Creative_V1_Common<public> := class<final><concrete>(entity):


    SignalRemoteA_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    SignalRemoteB_Creative_V1_Rare<public> := class<final><concrete>(entity):


    SignalRemoteC_Creative_V1_Epic<public> := class<final><concrete>(entity):


    SignalRemoteD_Creative_V1_Legendary<public> := class<final><concrete>(entity):


    SkyesGrappler_BR_CH2S2_Mythic<public> := class<final><concrete>(entity):


    SkylineDeployer_BR_CH7S2_Rare<public> := class<final><concrete>(entity):


    SlapBerry_BR_CH4S1_Uncommon<public> := class<final><concrete>(entity):


    SlapJuice_BR_CH4S1_Rare<public> := class<final><concrete>(entity):


    SlapperoniPizza_BR_CH7S2_Legendary<public> := class<final><concrete>(entity):


    SlapperoniSlice_BR_CH7S2_Legendary<public> := class<final><concrete>(entity):


    SlapSplash_BR_CH4S3_Rare<public> := class<final><concrete>(entity):


    SuperSlapSplash_BR_CH4S3_Exotic<public> := class<final><concrete>(entity):


    Slurpfish_BR_CH2S1_Epic<public> := class<final><concrete>(entity):


    SlurpJuice_BR_CH1S1_Legendary<public> := class<final><concrete>(entity):


    SlurpJuice_BR_CH6S4_Epic<public> := class<final><concrete>(entity):


    SlurpMushroom_BR_CH2S1_Common<public> := class<final><concrete>(entity):


    SmallFry_BR_CH2S1_Common<public> := class<final><concrete>(entity):


    SmallShieldPotion_BR_CH1S2_Uncommon<public> := class<final><concrete>(entity):


    SmallShieldPotion_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    SmokeGrenade_BR_CH1S1_Uncommon<public> := class<final><concrete>(entity):


    SmokeGrenade_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    SneakySnowman_BR_CH2S1_Rare<public> := class<final><concrete>(entity):


    SneakySnowman_OG_CH1S7_Common<public> := class<final><concrete>(entity):


    SnowyFlopper_BR_CH2S5_Uncommon<public> := class<final><concrete>(entity):


    SpeedBoostLow_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    SpeedBoostMedium_Creative_V1_Rare<public> := class<final><concrete>(entity):


    SpeedBoostHigh_Creative_V1_Epic<public> := class<final><concrete>(entity):


    SpicyFish_BR_CH2S4_Rare<public> := class<final><concrete>(entity):


    SpicyIcecreamCone_BR_CH3S3_Common<public> := class<final><concrete>(entity):


    SpireJumpboots_BR_CH2S6_Mythic<public> := class<final><concrete>(entity):


    StealthSplash_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    StinkBomb_BR_CH1S4_Rare<public> := class<final><concrete>(entity):


    StinkFish_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    StinkSac_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    Stone_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    StormFlip_BR_CH1S9_Epic<public> := class<final><concrete>(entity):


    SurfCube_BR_CH6S3_Epic<public> := class<final><concrete>(entity):


    LightridersSurfCube_BR_CH6S3_Mythic<public> := class<final><concrete>(entity):


    ThermalFish_BR_CH2S4_Legendary<public> := class<final><concrete>(entity):


    ThermalTaffy_BR_CH2S4_Common<public> := class<final><concrete>(entity):


    Thermite_BR_CH6S2_Rare<public> := class<final><concrete>(entity):


    ThunderboltOfZeus_BR_CH5S2_Mythic<public> := class<final><concrete>(entity):


    Torch_Creative_V1_Rare<public> := class<final><concrete>(entity):


    TrackingVisor_BR_CH6S3_Rare<public> := class<final><concrete>(entity):


    StringyTwine_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    SimpleTwine_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    SturdyTwine_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    PeakyTwine_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    CarvedTwine_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    SpectralTwine_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    UnstableBounceGrenade_BR_CH6S3_Exotic<public> := class<final><concrete>(entity):


    VehicleModCowCatcher_BR_CH3S2_Common<public> := class<final><concrete>(entity):


    VehicleModOffRoadTires_BR_CH2S6_Common<public> := class<final><concrete>(entity):


    VendettaFlopper_BR_CH2S4_Legendary<public> := class<final><concrete>(entity):


    VoidOniMask_BR_CH6S1_Epic<public> := class<final><concrete>(entity):


    NightRosesVoidOniMask_BR_CH6S1_Mythic<public> := class<final><concrete>(entity):


    WallDynamo_BR_CH1S1_Rare<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use WallDynamo_BR_CH1S1_Rare instead.
    WallDynamo_BR_CH4MS1_Rare<public> := class<final><concrete>(entity):


    Wheat_Creative_V1_Common<public> := class<final><concrete>(entity):


    WildwaspJar_BR_CH4S3_Rare<public> := class<final><concrete>(entity):


    WingsOfIcarus_BR_CH5S2_Epic<public> := class<final><concrete>(entity):


    Wingsuit_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    WitchBroom_BR_CH2S4_Mythic<public> := class<final><concrete>(entity):


    WolfTooth_Creative_V1_Uncommon<public> := class<final><concrete>(entity):


    Wood_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    ZeroPointFish_BR_CH2S5_Rare<public> := class<final><concrete>(entity):


    ZeroPointPretzel_BR_CH2S8_Uncommon<public> := class<final><concrete>(entity):


# Module import path: /Fortnite.com/Weapons
Weapons<public> := module:
    using {/Verse.org/SceneGraph}
    AnvilRocketLauncher_BR_CH3S2_Rare<public> := class<final><concrete>(entity):


    AnvilRocketLauncher_BR_CH3S2_Epic<public> := class<final><concrete>(entity):


    AnvilRocketLauncher_BR_CH3S2_Legendary<public> := class<final><concrete>(entity):


    ArcLightningGun_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    ArcLightningGun_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    HumanBillsArcLightningGun_BR_CH7S1_Mythic<public> := class<final><concrete>(entity):


    AscendedMyst_BR_CH6S3_Legendary<public> := class<final><concrete>(entity):


    AssaultRifle_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    AssaultRifle_BR_PreSeason_Uncommon<public> := class<final><concrete>(entity):


    AssaultRifle_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    AssaultRifle_BR_PreSeason_Epic<public> := class<final><concrete>(entity):


    AssaultRifle_BR_PreSeason_Legendary<public> := class<final><concrete>(entity):


    SkyesAssaultRifle_BR_CH2S2_Mythic<public> := class<final><concrete>(entity):


    AssaultRifle_BR_CH4S1_Common<public> := class<final><concrete>(entity):


    AssaultRifle_BR_CH4S1_Uncommon<public> := class<final><concrete>(entity):


    AssaultRifle_BR_CH4S1_Rare<public> := class<final><concrete>(entity):


    AssaultRifle_BR_CH4S1_Epic<public> := class<final><concrete>(entity):


    AssaultRifle_BR_CH4S1_Legendary<public> := class<final><concrete>(entity):


    EnhancedAssaultRifle_BR_CH6S4_Mythic<public> := class<final><concrete>(entity):


    AutomaticSniperRifle_BR_CH1SX_Rare<public> := class<final><concrete>(entity):


    AutomaticSniperRifle_BR_CH1SX_Epic<public> := class<final><concrete>(entity):


    AutomaticSniperRifle_BR_CH1SX_Legendary<public> := class<final><concrete>(entity):


    AutomaticSniperRifle_BR_CH2S5_Uncommon<public> := class<final><concrete>(entity):


    AutoShotgun_BR_CH3S1_Common<public> := class<final><concrete>(entity):


    AutoShotgun_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    AutoShotgun_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    AutoShotgun_BR_CH3S1_Epic<public> := class<final><concrete>(entity):


    AutoShotgun_BR_CH3S1_Legendary<public> := class<final><concrete>(entity):


    AutoShotgun_BR_CH3S1_Mythic<public> := class<final><concrete>(entity):


    BallisticShield_BR_CH5S1_Epic<public> := class<final><concrete>(entity):


    BasicHammer_Creative_V1_Common<public> := class<final><concrete>(entity):


    BasicSword_Creative_V1_Common<public> := class<final><concrete>(entity):


    BassBoost_BR_CH6S3_Rare<public> := class<final><concrete>(entity):


    BassBoost_BR_CH6S3_Epic<public> := class<final><concrete>(entity):


    BassBoost_BR_CH6S3_Mythic<public> := class<final><concrete>(entity):


    BoltActionSniperRifle_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    BoltActionSniperRifle_BR_PreSeason_Epic<public> := class<final><concrete>(entity):


    BoltActionSniperRifle_BR_PreSeason_Legendary<public> := class<final><concrete>(entity):


    BoltActionSniperRifle_BR_CH2S1_Common<public> := class<final><concrete>(entity):


    BoltActionSniperRifle_BR_CH2S1_Uncommon<public> := class<final><concrete>(entity):


    ModularBoomBolt_BR_CH5S3_Rare<public> := class<final><concrete>(entity):


    ModularBoomBolt_BR_CH5S3_Epic<public> := class<final><concrete>(entity):


    ModularBoomBolt_BR_CH5S3_Legendary<public> := class<final><concrete>(entity):


    RingmastersModularBoomBolt_BR_CH5S3_Mythic<public> := class<final><concrete>(entity):


    BoomBow_BR_CH1S8_Legendary<public> := class<final><concrete>(entity):


    BoomSniperRifle_BR_CH2S5_Exotic<public> := class<final><concrete>(entity):


    BugBlaster_BR_CH6S4_Rare<public> := class<final><concrete>(entity):


    BugBlaster_BR_CH6S4_Epic<public> := class<final><concrete>(entity):


    BugBlaster_BR_CH6S4_Legendary<public> := class<final><concrete>(entity):


    BurstAR_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    BurstAssaultRifle_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    BurstAssaultRifle_BR_PreSeason_Uncommon<public> := class<final><concrete>(entity):


    BurstAssaultRifle_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    BurstAssaultRifle_BR_CH1S4_Epic<public> := class<final><concrete>(entity):


    BurstAssaultRifle_BR_CH1S4_Legendary<public> := class<final><concrete>(entity):


    OceansBurstAssaultRifle_BR_CH2S3_Mythic<public> := class<final><concrete>(entity):


    SlonesBurstAssaultRifle_BR_CH2S8_Mythic<public> := class<final><concrete>(entity):


    BurstAssaultRifle_BR_CH4MS1_Common<public> := class<final><concrete>(entity):


    BurstAssaultRifle_BR_CH4MS1_Uncommon<public> := class<final><concrete>(entity):


    BurstAssaultRifle_BR_CH4MS1_Rare<public> := class<final><concrete>(entity):


    BurstAssaultRifle_BR_CH4MS1_Epic<public> := class<final><concrete>(entity):


    BurstAssaultRifle_BR_CH4MS1_Legendary<public> := class<final><concrete>(entity):


    BurstQuadLauncher_BR_CH2S5_Exotic<public> := class<final><concrete>(entity):


    BurstSMG_BR_CH1S9_Common<public> := class<final><concrete>(entity):


    BurstSMG_BR_CH1S9_Uncommon<public> := class<final><concrete>(entity):


    BurstSMG_BR_CH1S9_Rare<public> := class<final><concrete>(entity):


    Chainsaw_BR_CH5S4_Epic<public> := class<final><concrete>(entity):


    ChainsOfHades_BR_CH5S2_Epic<public> := class<final><concrete>(entity):


    ChaosExploderRifle_BR_CH7S3_Common<public> := class<final><concrete>(entity):


    ChaosExploderRifle_BR_CH7S3_Uncommon<public> := class<final><concrete>(entity):


    ChaosExploderRifle_BR_CH7S3_Rare<public> := class<final><concrete>(entity):


    ChaosExploderRifle_BR_CH7S3_Epic<public> := class<final><concrete>(entity):


    ChaosExploderRifle_BR_CH7S3_Legendary<public> := class<final><concrete>(entity):


    ChaosReloaderShotgun_BR_CH7S2_Common<public> := class<final><concrete>(entity):


    ChaosReloaderShotgun_BR_CH7S2_Uncommon<public> := class<final><concrete>(entity):


    ChaosReloaderShotgun_BR_CH7S2_Rare<public> := class<final><concrete>(entity):


    ChaosReloaderShotgun_BR_CH7S2_Epic<public> := class<final><concrete>(entity):


    ChaosReloaderShotgun_BR_CH7S2_Legendary<public> := class<final><concrete>(entity):


    DarkVoyagersObliterator_BR_CH7S2_Mythic<public> := class<final><concrete>(entity):


    ChargeShotgun_BR_CH2S3_Common<public> := class<final><concrete>(entity):


    ChargeShotgun_BR_CH2S3_Uncommon<public> := class<final><concrete>(entity):


    ChargeShotgun_BR_CH2S3_Rare<public> := class<final><concrete>(entity):


    ChargeShotgun_BR_CH2S3_Epic<public> := class<final><concrete>(entity):


    ChargeShotgun_BR_CH2S3_Legendary<public> := class<final><concrete>(entity):


    KitsChargeShotgun_BR_CH2S3_Mythic<public> := class<final><concrete>(entity):


    ChargeSMG_BR_CH3S3_Common<public> := class<final><concrete>(entity):


    ChargeSMG_BR_CH3S3_Uncommon<public> := class<final><concrete>(entity):


    ChargeSMG_BR_CH3S3_Rare<public> := class<final><concrete>(entity):


    ChargeSMG_BR_CH3S3_Epic<public> := class<final><concrete>(entity):


    ChargeSMG_BR_CH3S3_Legendary<public> := class<final><concrete>(entity):


    ChargeSMG_BR_CH3S3_Mythic<public> := class<final><concrete>(entity):


    CobraDMR_BR_CH3S4_Common<public> := class<final><concrete>(entity):


    CobraDMR_BR_CH3S4_Uncommon<public> := class<final><concrete>(entity):


    CobraDMR_BR_CH3S4_Rare<public> := class<final><concrete>(entity):


    CobraDMR_BR_CH3S4_Epic<public> := class<final><concrete>(entity):


    CobraDMR_BR_CH3S4_Legendary<public> := class<final><concrete>(entity):


    CobraDMR_BR_CH3S4_Mythic<public> := class<final><concrete>(entity):


    CollateralDamageAssaultRifle_BR_CH6S2_Common<public> := class<final><concrete>(entity):


    CollateralDamageAssaultRifle_BR_CH6S2_Uncommon<public> := class<final><concrete>(entity):


    CollateralDamageAssaultRifle_BR_CH6S2_Rare<public> := class<final><concrete>(entity):


    CollateralDamageAssaultRifle_BR_CH6S2_Epic<public> := class<final><concrete>(entity):


    CollateralDamageAssaultRifle_BR_CH6S2_Legendary<public> := class<final><concrete>(entity):


    EnhancedCollateralDamageAR_BR_CH6S2_Mythic<public> := class<final><concrete>(entity):


    LawlessTrinityAssaultRifle_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    CombatAssaultRifle_BR_CH2S8_Common<public> := class<final><concrete>(entity):


    CombatAssaultRifle_BR_CH2S8_Uncommon<public> := class<final><concrete>(entity):


    CombatAssaultRifle_BR_CH2S8_Rare<public> := class<final><concrete>(entity):


    CombatAssaultRifle_BR_CH2S8_Epic<public> := class<final><concrete>(entity):


    CombatAssaultRifle_BR_CH2S8_Legendary<public> := class<final><concrete>(entity):


    ModularCombatAssaultRifle_BR_CH5S3_Common<public> := class<final><concrete>(entity):


    ModularCombatAssaultRifle_BR_CH5S3_Uncommon<public> := class<final><concrete>(entity):


    ModularCombatAssaultRifle_BR_CH5S3_Rare<public> := class<final><concrete>(entity):


    ModularCombatAssaultRifle_BR_CH5S3_Epic<public> := class<final><concrete>(entity):


    ModularCombatAssaultRifle_BR_CH5S3_Legendary<public> := class<final><concrete>(entity):


    TheMachinistsModularCombatAssaultRifle_BR_CH5S3_Mythic<public> := class<final><concrete>(entity):


    CombatAssaultRifle_BR_CH7S2_Common<public> := class<final><concrete>(entity):


    CombatAssaultRifle_BR_CH7S2_Uncommon<public> := class<final><concrete>(entity):


    CombatAssaultRifle_BR_CH7S2_Rare<public> := class<final><concrete>(entity):


    CombatAssaultRifle_BR_CH7S2_Epic<public> := class<final><concrete>(entity):


    CombatAssaultRifle_BR_CH7S2_Legendary<public> := class<final><concrete>(entity):


    CombatPistol_BR_CH2S8_Common<public> := class<final><concrete>(entity):


    CombatPistol_BR_CH2S8_Uncommon<public> := class<final><concrete>(entity):


    CombatPistol_BR_CH2S8_Rare<public> := class<final><concrete>(entity):


    CombatPistol_BR_CH2S8_Epic<public> := class<final><concrete>(entity):


    CombatPistol_BR_CH2S8_Legendary<public> := class<final><concrete>(entity):


    CombatShotgun_BR_CH1S9_Rare<public> := class<final><concrete>(entity):


    CombatShotgun_BR_CH1S9_Epic<public> := class<final><concrete>(entity):


    CombatShotgun_BR_CH1S9_Legendary<public> := class<final><concrete>(entity):


    CombatShotgun_BR_CH2S8_Uncommon<public> := class<final><concrete>(entity):


    CombatShotgun_BR_CH4S2_Common<public> := class<final><concrete>(entity):


    ModularCombatShotgun_BR_CH5S3_Common<public> := class<final><concrete>(entity):


    ModularCombatShotgun_BR_CH5S3_Uncommon<public> := class<final><concrete>(entity):


    ModularCombatShotgun_BR_CH5S3_Rare<public> := class<final><concrete>(entity):


    ModularCombatShotgun_BR_CH5S3_Epic<public> := class<final><concrete>(entity):


    ModularCombatShotgun_BR_CH5S3_Legendary<public> := class<final><concrete>(entity):


    MegaloDonsModularCombatShotgun_BR_CH5S3_Mythic<public> := class<final><concrete>(entity):


    CombatSMG_BR_CH3S2_Common<public> := class<final><concrete>(entity):


    CombatSMG_BR_CH3S2_Uncommon<public> := class<final><concrete>(entity):


    CombatSMG_BR_CH3S2_Rare<public> := class<final><concrete>(entity):


    CombatSMG_BR_CH3S2_Epic<public> := class<final><concrete>(entity):


    CombatSMG_BR_CH3S2_Legendary<public> := class<final><concrete>(entity):


    CombatSMG_BR_CH3S2_Mythic<public> := class<final><concrete>(entity):


    CompactSMG_BR_CH1S5_Epic<public> := class<final><concrete>(entity):


    CompactSMG_BR_CH1S5_Legendary<public> := class<final><concrete>(entity):


    CompactSMG_BR_CH6MS2_Uncommon<public> := class<final><concrete>(entity):


    CompactSMG_BR_CH6MS2_Rare<public> := class<final><concrete>(entity):


    EnhancedCompactSMG_BR_CH6MS2_Mythic<public> := class<final><concrete>(entity):


    Crossbow_BR_CH1S3_Rare<public> := class<final><concrete>(entity):


    Crossbow_BR_CH1S3_Epic<public> := class<final><concrete>(entity):


    CubeRifle_BR_CH7S2_Epic<public> := class<final><concrete>(entity):


    CubeRifle_BR_CH7S2_Legendary<public> := class<final><concrete>(entity):


    CubeRifle_BR_CH7S2_Mythic<public> := class<final><concrete>(entity):


    CupidsCrossbow_BR_CH1S2_Epic<public> := class<final><concrete>(entity):


    EmpoweredCupidsCrossbow_BR_CH7S1_Mythic<public> := class<final><concrete>(entity):


    DarkVoyagersChaosRifle_BR_CH7S3_Mythic<public> := class<final><concrete>(entity):


    DeadeyeAssaultRifle_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    DeadeyeAssaultRifle_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    DeadeyeAssaultRifle_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    DeadeyeAssaultRifle_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    DeadeyeAssaultRifle_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    HushsDeadeyeAssaultRifle_BR_CH7S1_Mythic<public> := class<final><concrete>(entity):


    DeadeyeDMR_BR_CH6S3_Common<public> := class<final><concrete>(entity):


    DeadeyeDMR_BR_CH6S3_Uncommon<public> := class<final><concrete>(entity):


    DeadeyeDMR_BR_CH6S3_Rare<public> := class<final><concrete>(entity):


    DeadeyeDMR_BR_CH6S3_Epic<public> := class<final><concrete>(entity):


    DeadeyeDMR_BR_CH6S3_Legendary<public> := class<final><concrete>(entity):


    KorsDeadeyeDMR_BR_CH6S3_Mythic<public> := class<final><concrete>(entity):


    UnstableThunderclapDMR_BR_CH6S3_Exotic<public> := class<final><concrete>(entity):


    DMR_BR_CH3S3_Common<public> := class<final><concrete>(entity):


    DMR_BR_CH3S3_Uncommon<public> := class<final><concrete>(entity):


    DMR_BR_CH3S3_Rare<public> := class<final><concrete>(entity):


    DMR_BR_CH3S3_Epic<public> := class<final><concrete>(entity):


    DMR_BR_CH3S3_Legendary<public> := class<final><concrete>(entity):


    DMR_BR_CH3S3_Mythic<public> := class<final><concrete>(entity):


    Double_BR_CH6S4_Exotic<public> := class<final><concrete>(entity):


    DoubleBarrelShotgun_BR_CH1S5_Epic<public> := class<final><concrete>(entity):


    DoubleBarrelShotgun_BR_CH1S5_Legendary<public> := class<final><concrete>(entity):


    DragonsBreathShotgun_BR_CH6S2_Epic<public> := class<final><concrete>(entity):


    DragonsBreathShotgun_BR_CH6S2_Legendary<public> := class<final><concrete>(entity):


    DragonsBreathSniper_BR_CH2S5_Exotic<public> := class<final><concrete>(entity):


    DragonsBreathShotgun_BR_CH2S5_Epic<public> := class<final><concrete>(entity):


    DragonsBreathShotgun_BR_CH2S5_Legendary<public> := class<final><concrete>(entity):


    DrumGun_BR_CH1S4_Uncommon<public> := class<final><concrete>(entity):


    DrumGun_BR_CH1S4_Rare<public> := class<final><concrete>(entity):


    MidasDrumGun_BR_CH2S2_Mythic<public> := class<final><concrete>(entity):


    JulesDrumGun_BR_CH2S3_Mythic<public> := class<final><concrete>(entity):


    ShadowMidasDrumGun_BR_CH2S4_Mythic<public> := class<final><concrete>(entity):


    ModularDrumGun_BR_CH5S2_Rare<public> := class<final><concrete>(entity):


    ModularDrumGun_BR_CH5S2_Epic<public> := class<final><concrete>(entity):


    ModularDrumGun_BR_CH5S2_Legendary<public> := class<final><concrete>(entity):


    MidasModularDrumGun_BR_CH5S2_Mythic<public> := class<final><concrete>(entity):


    MidasGildedEyeDrumGun_BR_CH6S2_Mythic<public> := class<final><concrete>(entity):


    DrumGun_BR_CH6MS2_Rare<public> := class<final><concrete>(entity):


    DrumGun_BR_CH6MS2_Epic<public> := class<final><concrete>(entity):


    DrumGun_BR_CH6MS2_Legendary<public> := class<final><concrete>(entity):


    DrumGun_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    DrumShotgun_BR_CH1S9_Common<public> := class<final><concrete>(entity):


    DrumShotgun_BR_CH1S9_Uncommon<public> := class<final><concrete>(entity):


    DrumShotgun_BR_CH1S9_Rare<public> := class<final><concrete>(entity):


    DrumShotgun_BR_CH3S2_Epic<public> := class<final><concrete>(entity):


    DrumShotgun_BR_CH3S2_Legendary<public> := class<final><concrete>(entity):


    EnhancedDrumShotgun_BR_CH4S3_Mythic<public> := class<final><concrete>(entity):


    DualFiendHunters_BR_CH2S8_Common<public> := class<final><concrete>(entity):


    DualFiendHunters_BR_CH2S8_Uncommon<public> := class<final><concrete>(entity):


    DualFiendHunters_BR_CH2S8_Rare<public> := class<final><concrete>(entity):


    DualFiendHunters_BR_CH2S8_Epic<public> := class<final><concrete>(entity):


    DualFiendHunters_BR_CH2S8_Legendary<public> := class<final><concrete>(entity):


    DualMicroSMGs_BR_CH5S4_Common<public> := class<final><concrete>(entity):


    DualMicroSMGs_BR_CH5S4_Uncommon<public> := class<final><concrete>(entity):


    DualMicroSMGs_BR_CH5S4_Rare<public> := class<final><concrete>(entity):


    DualMicroSMGs_BR_CH5S4_Epic<public> := class<final><concrete>(entity):


    DualMicroSMGs_BR_CH5S4_Legendary<public> := class<final><concrete>(entity):


    DualMicroSMGs_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    DualMicroSMGs_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    DualMicroSMGs_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    DualMicroSMGs_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    DualMicroSMGs_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    DualPistols_BR_CH1S4_Rare<public> := class<final><concrete>(entity):


    DualPistols_BR_CH1S4_Epic<public> := class<final><concrete>(entity):


    DualPistols_BR_CH2S6_Common<public> := class<final><concrete>(entity):


    DualPistols_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    DualPistols_BR_CH2S6_Legendary<public> := class<final><concrete>(entity):


    DualSuppressedPistols_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    DualSuppressedPistols_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    DualSuppressedPistols_BR_CH3S1_Epic<public> := class<final><concrete>(entity):


    DualSuppressedPistols_BR_CH3S1_Legendary<public> := class<final><concrete>(entity):


    EggLauncher_BR_CH1S3_Rare<public> := class<final><concrete>(entity):


    EggLauncher_BR_CH1S3_Epic<public> := class<final><concrete>(entity):


    EggLauncher_BR_CH1S3_Legendary<public> := class<final><concrete>(entity):


    EggLauncher_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    ModularEnforcerAR_BR_CH5S1_Common<public> := class<final><concrete>(entity):


    ModularEnforcerAR_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    ModularEnforcerAR_BR_CH5S1_Rare<public> := class<final><concrete>(entity):


    ModularEnforcerAR_BR_CH5S1_Epic<public> := class<final><concrete>(entity):


    ModularEnforcerAR_BR_CH5S1_Legendary<public> := class<final><concrete>(entity):


    EnforcerAR_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    EnforcerAR_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    EnforcerAR_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    EnforcerAR_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    EnforcerAR_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    EnforcerAR_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    EvoChromeBurstRifle_BR_CH3S4_Common<public> := class<final><concrete>(entity):


    EvoChromeBurstRifle_BR_CH3S4_Uncommon<public> := class<final><concrete>(entity):


    EvoChromeBurstRifle_BR_CH3S4_Rare<public> := class<final><concrete>(entity):


    EvoChromeBurstRifle_BR_CH3S4_Epic<public> := class<final><concrete>(entity):


    EvoChromeBurstRifle_BR_CH3S4_Legendary<public> := class<final><concrete>(entity):


    EvoChromeBurstRifle_BR_CH3S4_Mythic<public> := class<final><concrete>(entity):


    EvoChromeShotgun_BR_CH3S4_Common<public> := class<final><concrete>(entity):


    EvoChromeShotgun_BR_CH3S4_Uncommon<public> := class<final><concrete>(entity):


    EvoChromeShotgun_BR_CH3S4_Rare<public> := class<final><concrete>(entity):


    EvoChromeShotgun_BR_CH3S4_Epic<public> := class<final><concrete>(entity):


    EvoChromeShotgun_BR_CH3S4_Legendary<public> := class<final><concrete>(entity):


    EvoChromeShotgun_BR_CH3S4_Mythic<public> := class<final><concrete>(entity):


    ExCaliberRifle_BR_CH4S1_Common<public> := class<final><concrete>(entity):


    ExCaliberRifle_BR_CH4S1_Uncommon<public> := class<final><concrete>(entity):


    ExCaliberRifle_BR_CH4S1_Rare<public> := class<final><concrete>(entity):


    ExCaliberRifle_BR_CH4S1_Epic<public> := class<final><concrete>(entity):


    ExCaliberRifle_BR_CH4S1_Legendary<public> := class<final><concrete>(entity):


    TheAgelessChampionsExCaliberRifle_BR_CH4S1_Mythic<public> := class<final><concrete>(entity):


    ExoticLeapingLightningGun_BR_CH7S2_Exotic<public> := class<final><concrete>(entity):


    ExplosiveGooGun_BR_CH3S4_Rare<public> := class<final><concrete>(entity):


    ExplosiveRepeaterRifle_BR_CH4S3_Common<public> := class<final><concrete>(entity):


    ExplosiveRepeaterRifle_BR_CH4S3_Uncommon<public> := class<final><concrete>(entity):


    ExplosiveRepeaterRifle_BR_CH4S3_Rare<public> := class<final><concrete>(entity):


    ExplosiveRepeaterRifle_BR_CH4S3_Epic<public> := class<final><concrete>(entity):


    ExplosiveRepeaterRifle_BR_CH4S3_Legendary<public> := class<final><concrete>(entity):


    ExplosiveRepeaterRifle_BR_CH4S3_Mythic<public> := class<final><concrete>(entity):


    ExtendingFocusShotgun_BR_CH7S3_Common<public> := class<final><concrete>(entity):


    ExtendingFocusShotgun_BR_CH7S3_Uncommon<public> := class<final><concrete>(entity):


    ExtendingFocusShotgun_BR_CH7S3_Rare<public> := class<final><concrete>(entity):


    ExtendingFocusShotgun_BR_CH7S3_Epic<public> := class<final><concrete>(entity):


    ExtendingFocusShotgun_BR_CH7S3_Legendary<public> := class<final><concrete>(entity):


    FalconEyeSniper_BR_CH6S2_Common<public> := class<final><concrete>(entity):


    FalconEyeSniper_BR_CH6S2_Uncommon<public> := class<final><concrete>(entity):


    FalconEyeSniper_BR_CH6S2_Rare<public> := class<final><concrete>(entity):


    FalconEyeSniper_BR_CH6S2_Epic<public> := class<final><concrete>(entity):


    FalconEyeSniper_BR_CH6S2_Legendary<public> := class<final><concrete>(entity):


    EnhancedFalconEyeSniper_BR_CH6S2_Mythic<public> := class<final><concrete>(entity):


    FiendHunterCrossbow_BR_CH1S6_Epic<public> := class<final><concrete>(entity):


    FireOniMask_BR_CH6S1_Epic<public> := class<final><concrete>(entity):


    ShogunXsFireOniMask_BR_CH6S1_Mythic<public> := class<final><concrete>(entity):


    FireworkFlareGun_BR_CH3S3_Rare<public> := class<final><concrete>(entity):


    FlapjackRifle_BR_CH4S3_Common<public> := class<final><concrete>(entity):


    FlapjackRifle_BR_CH4S3_Uncommon<public> := class<final><concrete>(entity):


    FlapjackRifle_BR_CH4S3_Rare<public> := class<final><concrete>(entity):


    FlapjackRifle_BR_CH4S3_Epic<public> := class<final><concrete>(entity):


    FlapjackRifle_BR_CH4S3_Legendary<public> := class<final><concrete>(entity):


    EnhancedFlapJackRifle_BR_CH4S3_Mythic<public> := class<final><concrete>(entity):


    FlareGun_BR_CH2S3_Rare<public> := class<final><concrete>(entity):


    FlashlightPistol_Creative_V1_Rare<public> := class<final><concrete>(entity):


    FlexSMG_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    FlexSMG_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    FlexSMG_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    FlexSMG_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    FlexSMG_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    BigfootsFlexSMG_BR_CH7S1_Mythic<public> := class<final><concrete>(entity):


    FlintKnockPistol_BR_CH1S8_Common<public> := class<final><concrete>(entity):


    FlintKnockPistol_BR_CH1S8_Uncommon<public> := class<final><concrete>(entity):


    ModularFrenzyAutoShotgun_BR_CH5S1_Common<public> := class<final><concrete>(entity):


    ModularFrenzyAutoShotgun_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    ModularFrenzyAutoShotgun_BR_CH5S1_Rare<public> := class<final><concrete>(entity):


    ModularFrenzyAutoShotgun_BR_CH5S1_Epic<public> := class<final><concrete>(entity):


    ModularFrenzyAutoShotgun_BR_CH5S1_Legendary<public> := class<final><concrete>(entity):


    OscarsModularFrenzyAutoShotgun_BR_CH5S1_Mythic<public> := class<final><concrete>(entity):


    FrenzyAutoShotgun_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    FuryAssaultRifle_BR_CH6S1_Common<public> := class<final><concrete>(entity):


    FuryAssaultRifle_BR_CH6S1_Uncommon<public> := class<final><concrete>(entity):


    FuryAssaultRifle_BR_CH6S1_Rare<public> := class<final><concrete>(entity):


    FuryAssaultRifle_BR_CH6S1_Epic<public> := class<final><concrete>(entity):


    FuryAssaultRifle_BR_CH6S1_Legendary<public> := class<final><concrete>(entity):


    EnhancedFuryAssaultRifle_BR_CH6S1_Mythic<public> := class<final><concrete>(entity):


    EradicatorHopRockFuryAssaultRifle_BR_CH6S4_Exotic<public> := class<final><concrete>(entity):


    ModularGatekeeperShotgun_BR_CH5S2_Common<public> := class<final><concrete>(entity):


    ModularGatekeeperShotgun_BR_CH5S2_Uncommon<public> := class<final><concrete>(entity):


    ModularGatekeeperShotgun_BR_CH5S2_Rare<public> := class<final><concrete>(entity):


    ModularGatekeeperShotgun_BR_CH5S2_Epic<public> := class<final><concrete>(entity):


    ModularGatekeeperShotgun_BR_CH5S2_Legendary<public> := class<final><concrete>(entity):


    CerberusModularGatekeeperShotgun_BR_CH5S2_Mythic<public> := class<final><concrete>(entity):


    GrappleBlade_BR_CH5S1_Epic<public> := class<final><concrete>(entity):


    GrapplerBow_BR_CH2S6_Exotic<public> := class<final><concrete>(entity):


    GrenadeLauncher_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    GrenadeLauncher_BR_PreSeason_Epic<public> := class<final><concrete>(entity):


    GrenadeLauncher_BR_PreSeason_Legendary<public> := class<final><concrete>(entity):


    GuidedMissile_OG_CH1S3_Epic<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use GuidedMissile_OG_CH1S3_Epic instead.
    GuidedMissile_BR_CH4MS1_Epic<public> := class<final><concrete>(entity):


    GuidedMissile_OG_CH1S3_Legendary<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use GuidedMissile_OG_CH1S3_Legendary instead.
    GuidedMissile_BR_CH4MS1_Legendary<public> := class<final><concrete>(entity):


    HammerAssaultRifle_BR_CH3S3_Common<public> := class<final><concrete>(entity):


    HammerAssaultRifle_BR_CH3S3_Uncommon<public> := class<final><concrete>(entity):


    HammerAssaultRifle_BR_CH3S3_Rare<public> := class<final><concrete>(entity):


    HammerAssaultRifle_BR_CH3S3_Epic<public> := class<final><concrete>(entity):


    HammerAssaultRifle_BR_CH3S3_Legendary<public> := class<final><concrete>(entity):


    HammerAssaultRifle_BR_CH3S3_Mythic<public> := class<final><concrete>(entity):


    ModularHammerPumpShotgun_BR_CH5S1_Common<public> := class<final><concrete>(entity):


    ModularHammerPumpShotgun_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    ModularHammerPumpShotgun_BR_CH5S1_Rare<public> := class<final><concrete>(entity):


    ModularHammerPumpShotgun_BR_CH5S1_Epic<public> := class<final><concrete>(entity):


    ModularHammerPumpShotgun_BR_CH5S1_Legendary<public> := class<final><concrete>(entity):


    HammerPumpShotgun_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    HammerRevolver_BR_CH7S2_Uncommon<public> := class<final><concrete>(entity):


    HammerRevolver_BR_CH7S2_Rare<public> := class<final><concrete>(entity):


    HammerRevolver_BR_CH7S2_Epic<public> := class<final><concrete>(entity):


    HammerRevolver_BR_CH7S2_Legendary<public> := class<final><concrete>(entity):


    HammerRevolver_BR_CH7S2_Mythic<public> := class<final><concrete>(entity):


    HandCannon_BR_CH1S3_Epic<public> := class<final><concrete>(entity):


    HandCannon_BR_CH1S3_Legendary<public> := class<final><concrete>(entity):


    HandCannon_BR_CH2S2_Rare<public> := class<final><concrete>(entity):


    ModularHandCannon_BR_CH5S2_Rare<public> := class<final><concrete>(entity):


    ModularHandCannon_BR_CH5S2_Epic<public> := class<final><concrete>(entity):


    ModularHandCannon_BR_CH5S2_Legendary<public> := class<final><concrete>(entity):


    ModularConductorHandCannon_BR_CH5S3_Mythic<public> := class<final><concrete>(entity):


    HandCannon_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    ModularHarbingerSMG_BR_CH5S2_Common<public> := class<final><concrete>(entity):


    ModularHarbingerSMG_BR_CH5S2_Uncommon<public> := class<final><concrete>(entity):


    ModularHarbingerSMG_BR_CH5S2_Rare<public> := class<final><concrete>(entity):


    ModularHarbingerSMG_BR_CH5S2_Epic<public> := class<final><concrete>(entity):


    ModularHarbingerSMG_BR_CH5S2_Legendary<public> := class<final><concrete>(entity):


    HadesModularHarbingerSMG_BR_CH5S2_Mythic<public> := class<final><concrete>(entity):


    HavocPumpShotgun_BR_CH4S2_Common<public> := class<final><concrete>(entity):


    HavocPumpShotgun_BR_CH4S2_Uncommon<public> := class<final><concrete>(entity):


    HavocPumpShotgun_BR_CH4S2_Rare<public> := class<final><concrete>(entity):


    HavocPumpShotgun_BR_CH4S2_Epic<public> := class<final><concrete>(entity):


    HavocPumpShotgun_BR_CH4S2_Legendary<public> := class<final><concrete>(entity):


    EnhancedHavocShotgun_BR_CH4S2_Mythic<public> := class<final><concrete>(entity):


    HavocSuppressedAssaultRifle_BR_CH4S2_Common<public> := class<final><concrete>(entity):


    HavocSuppressedAssaultRifle_BR_CH4S2_Uncommon<public> := class<final><concrete>(entity):


    HavocSuppressedAssaultRifle_BR_CH4S2_Rare<public> := class<final><concrete>(entity):


    HavocSuppressedAssaultRifle_BR_CH4S2_Epic<public> := class<final><concrete>(entity):


    HavocSuppressedAssaultRifle_BR_CH4S2_Legendary<public> := class<final><concrete>(entity):


    HavocSuppressedAssaultRifle_BR_CH4S2_Mythic<public> := class<final><concrete>(entity):


    HighcardsHavocSuppressedRifle_BR_CH4S2_Mythic<public> := class<final><concrete>(entity):


    HeartsHavocSuppressedRifle_BR_CH4S4_Mythic<public> := class<final><concrete>(entity):


    HeavyAssaultRifle_BR_CH1S6_Rare<public> := class<final><concrete>(entity):


    HeavyAssaultRifle_BR_CH1S6_Epic<public> := class<final><concrete>(entity):


    HeavyAssaultRifle_BR_CH1S6_Legendary<public> := class<final><concrete>(entity):


    HeavyAssaultRifle_BR_CH1S8_Common<public> := class<final><concrete>(entity):


    HeavyAssaultRifle_BR_CH1S8_Uncommon<public> := class<final><concrete>(entity):


    HeavyImpactSniperRifle_BR_CH5S3_Rare<public> := class<final><concrete>(entity):


    HeavyImpactSniperRifle_BR_CH5S3_Epic<public> := class<final><concrete>(entity):


    HeavyImpactSniperRifle_BR_CH5S3_Legendary<public> := class<final><concrete>(entity):


    LawlessHeavyImpactTrackingRifle_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    LawfulHeavyImpactTrackingRifle_BR_CH7S2_Exotic<public> := class<final><concrete>(entity):


    HeavyShotgun_BR_CH3S1_Common<public> := class<final><concrete>(entity):


    HeavyShotgun_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    HeavyShotgun_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    HeavyShotgun_BR_CH3S1_Epic<public> := class<final><concrete>(entity):


    HeavyShotgun_BR_CH3S1_Legendary<public> := class<final><concrete>(entity):


    HeistedBreacherShotgun_BR_CH4S1_Exotic<public> := class<final><concrete>(entity):


    HeavyShotgun_OG_CH1S3_Epic<public> := class<final><concrete>(entity):


    HeavyShotgun_OG_CH1S3_Legendary<public> := class<final><concrete>(entity):


    HeavySniperRifle_BR_CH1S5_Epic<public> := class<final><concrete>(entity):


    HeavySniperRifle_BR_CH1S5_Legendary<public> := class<final><concrete>(entity):


    HeavySniperRifle_BR_CH3S3_Mythic<public> := class<final><concrete>(entity):


    HoloRushSMG_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    HoloRushSMG_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    HoloRushSMG_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    HoloRushSMG_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    HoloRushSMG_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    YuleTroopersHoloRushSMG_BR_CH7S1_Mythic<public> := class<final><concrete>(entity):


    HoloTwisterAssaultRifle_BR_CH6S1_Common<public> := class<final><concrete>(entity):


    HoloTwisterAssaultRifle_BR_CH6S1_Uncommon<public> := class<final><concrete>(entity):


    HoloTwisterAssaultRifle_BR_CH6S1_Rare<public> := class<final><concrete>(entity):


    HoloTwisterAssaultRifle_BR_CH6S1_Epic<public> := class<final><concrete>(entity):


    HoloTwisterAssaultRifle_BR_CH6S1_Legendary<public> := class<final><concrete>(entity):


    EnhancedHoloTwisterAssaultRifle_BR_CH6S1_Mythic<public> := class<final><concrete>(entity):


    HopRockDualies_BR_CH2S5_Exotic<public> := class<final><concrete>(entity):


    HunterBoltActionSniper_BR_CH3S1_Common<public> := class<final><concrete>(entity):


    HunterBoltActionSniper_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    HunterBoltActionSniper_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    HunterBoltActionSniper_BR_CH3S1_Epic<public> := class<final><concrete>(entity):


    HunterBoltActionSniper_BR_CH3S1_Legendary<public> := class<final><concrete>(entity):


    HuntingRifle_BR_CH1S3_Uncommon<public> := class<final><concrete>(entity):


    HuntingRifle_BR_CH1S3_Rare<public> := class<final><concrete>(entity):


    HuntingRifle_BR_CH2S3_Epic<public> := class<final><concrete>(entity):


    HuntingRifle_BR_CH2S3_Legendary<public> := class<final><concrete>(entity):


    HuntingRifle_BR_CH6S1_Uncommon<public> := class<final><concrete>(entity):


    HuntingRifle_BR_CH6S1_Rare<public> := class<final><concrete>(entity):


    HuntingRifle_BR_CH6S1_Mythic<public> := class<final><concrete>(entity):


    LawlessStinkRifle_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    ModularHuntressDMR_BR_CH5S2_Uncommon<public> := class<final><concrete>(entity):


    ModularHuntressDMR_BR_CH5S2_Rare<public> := class<final><concrete>(entity):


    ModularHuntressDMR_BR_CH5S2_Epic<public> := class<final><concrete>(entity):


    ModularHuntressDMR_BR_CH5S2_Legendary<public> := class<final><concrete>(entity):


    ModularZeusHuntressDMR_BR_CH5S2_Mythic<public> := class<final><concrete>(entity):


    HyperburstPistol_BR_CH6S3_Common<public> := class<final><concrete>(entity):


    HyperburstPistol_BR_CH6S3_Uncommon<public> := class<final><concrete>(entity):


    HyperburstPistol_BR_CH6S3_Rare<public> := class<final><concrete>(entity):


    HyperburstPistol_BR_CH6S3_Epic<public> := class<final><concrete>(entity):


    HyperburstPistol_BR_CH6S3_Legendary<public> := class<final><concrete>(entity):


    EnhancedHyperburstPistol_BR_CH6S3_Mythic<public> := class<final><concrete>(entity):


    UnstableVoltageBurstPistol_BR_CH6S3_Exotic<public> := class<final><concrete>(entity):


    ModularHyperSMG_BR_CH5S1_Common<public> := class<final><concrete>(entity):


    ModularHyperSMG_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    ModularHyperSMG_BR_CH5S1_Rare<public> := class<final><concrete>(entity):


    ModularHyperSMG_BR_CH5S1_Epic<public> := class<final><concrete>(entity):


    ModularHyperSMG_BR_CH5S1_Legendary<public> := class<final><concrete>(entity):


    ValeriasModularHyperSMG_BR_CH5S1_Mythic<public> := class<final><concrete>(entity):


    HyperSMG_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    IceKingsGauntlets_BR_CH7S2_Mythic<public> := class<final><concrete>(entity):


    InfantryRifle_BR_CH1S7_Common<public> := class<final><concrete>(entity):


    InfantryRifle_BR_CH1S7_Uncommon<public> := class<final><concrete>(entity):


    InfantryRifle_BR_CH1S7_Rare<public> := class<final><concrete>(entity):


    InfantryRifle_BR_CH1S8_Epic<public> := class<final><concrete>(entity):


    InfantryRifle_BR_CH1S8_Legendary<public> := class<final><concrete>(entity):


    InfantryRifle_BR_CH6MS2_Epic<public> := class<final><concrete>(entity):


    InfantryRifle_BR_CH6MS2_Legendary<public> := class<final><concrete>(entity):


    InfiltratorPumpShotgun_BR_CH4S4_Common<public> := class<final><concrete>(entity):


    InfiltratorPumpShotgun_BR_CH4S4_Uncommon<public> := class<final><concrete>(entity):


    InfiltratorPumpShotgun_BR_CH4S4_Rare<public> := class<final><concrete>(entity):


    InfiltratorPumpShotgun_BR_CH4S4_Epic<public> := class<final><concrete>(entity):


    InfiltratorPumpShotgun_BR_CH4S4_Legendary<public> := class<final><concrete>(entity):


    EnhancedInfiltratorPumpShotgun_BR_CH4S4_Mythic<public> := class<final><concrete>(entity):


    InfinityBlade_BR_CH1S7_Mythic<public> := class<final><concrete>(entity):


    IronPumpShotgun_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    IronPumpShotgun_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    IronPumpShotgun_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    IronPumpShotgun_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    IronPumpShotgun_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    PinpointIronPumpShotgun_BR_CH7S1_Mythic<public> := class<final><concrete>(entity):


    KillswitchsRevolvers_BR_CH6S3_Mythic<public> := class<final><concrete>(entity):


    KillswitchRevolvers_BR_CH6S3_Rare<public> := class<final><concrete>(entity):


    KillswitchRevolvers_BR_CH6S3_Epic<public> := class<final><concrete>(entity):


    KillswitchRevolvers_BR_CH6S3_Legendary<public> := class<final><concrete>(entity):


    KineticBlade_BR_CH4S2_Rare<public> := class<final><concrete>(entity):


    KineticBlade_BR_CH4S2_Epic<public> := class<final><concrete>(entity):


    ThornesVampiricBlade_BR_CH4S4_Mythic<public> := class<final><concrete>(entity):


    KineticBoomerang_BR_CH4S3_Epic<public> := class<final><concrete>(entity):


    KymeraRayGun_BR_CH2S7_Rare<public> := class<final><concrete>(entity):


    KymeraRayGun_BR_CH2S7_Epic<public> := class<final><concrete>(entity):


    KymeraRayGun_BR_CH2S7_Legendary<public> := class<final><concrete>(entity):


    ZygAndChoppysRayGun_BR_CH2S7_Mythic<public> := class<final><concrete>(entity):


    LawfulAccelerantHoloTwisterAR_BR_CH7S2_Exotic<public> := class<final><concrete>(entity):


    LawfulShockwaveRocketLauncher_BR_CH7S2_Exotic<public> := class<final><concrete>(entity):


    LawlessAccelerantHoloTwisterAR_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    LawlessFinalMarkRifle_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    LawlessShockwaveRocketLauncher_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    Leadspitter3000_BR_CH6S4_Epic<public> := class<final><concrete>(entity):


    Leadspitter3000_BR_CH6S4_Legendary<public> := class<final><concrete>(entity):


    Leadspitter3000_BR_CH6S4_Mythic<public> := class<final><concrete>(entity):


    LeverActionRifle_BR_CH2S5_Uncommon<public> := class<final><concrete>(entity):


    LeverActionRifle_BR_CH2S5_Rare<public> := class<final><concrete>(entity):


    LeverActionRifle_BR_CH2S5_Epic<public> := class<final><concrete>(entity):


    LeverActionRifle_BR_CH2S5_Legendary<public> := class<final><concrete>(entity):


    LeverActionShotgun_BR_CH2S5_Common<public> := class<final><concrete>(entity):


    LeverActionShotgun_BR_CH2S5_Uncommon<public> := class<final><concrete>(entity):


    LeverActionShotgun_BR_CH2S5_Rare<public> := class<final><concrete>(entity):


    LeverActionShotgun_BR_CH2S5_Epic<public> := class<final><concrete>(entity):


    LeverActionShotgun_BR_CH2S5_Legendary<public> := class<final><concrete>(entity):


    LightMachineGun_BR_CH1S3_Rare<public> := class<final><concrete>(entity):


    LightMachineGun_BR_CH1S3_Epic<public> := class<final><concrete>(entity):


    LightMachineGun_BR_CH3S2_Common<public> := class<final><concrete>(entity):


    LightMachineGun_BR_CH3S2_Uncommon<public> := class<final><concrete>(entity):


    LightMachineGun_BR_CH3S2_Legendary<public> := class<final><concrete>(entity):


    LockOnAssaultRifle_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    LockOnAssaultRifle_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    LockOnAssaultRifle_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    LockOnAssaultRifle_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    LockOnAssaultRifle_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    LockOnPistol_BR_CH4S2_Rare<public> := class<final><concrete>(entity):


    MachinePistol_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    MachineSMG_BR_CH3S1_Common<public> := class<final><concrete>(entity):


    MachineSMG_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    MachineSMG_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    MachineSMG_BR_CH3S1_Epic<public> := class<final><concrete>(entity):


    MachineSMG_BR_CH3S1_Legendary<public> := class<final><concrete>(entity):


    MakeshiftBow_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    MakeshiftRevolver_BR_CH2S6_Common<public> := class<final><concrete>(entity):


    MakeshiftRevolver_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    MakeshiftRevolver_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    MakeshiftRifle_BR_CH2S6_Common<public> := class<final><concrete>(entity):


    MakeshiftRifle_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    MakeshiftRifle_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    MakeshiftShotgun_BR_CH2S6_Common<public> := class<final><concrete>(entity):


    MakeshiftShotgun_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    MakeshiftShotgun_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    MakeshiftSubmachineGun_BR_CH2S6_Common<public> := class<final><concrete>(entity):


    MakeshiftSubmachineGun_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    MakeshiftSubmachineGun_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    MammothPistol_BR_CH4S3_Common<public> := class<final><concrete>(entity):


    MammothPistol_BR_CH4S3_Uncommon<public> := class<final><concrete>(entity):


    MammothPistol_BR_CH4S3_Rare<public> := class<final><concrete>(entity):


    MammothPistol_BR_CH4S3_Epic<public> := class<final><concrete>(entity):


    MammothPistol_BR_CH4S3_Legendary<public> := class<final><concrete>(entity):


    BaronsDoubleDownPistol_BR_CH6S2_Mythic<public> := class<final><concrete>(entity):


    LawlessExplosiveMammothPistol_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    LawfulExplosiveMammothPistol_BR_CH7S2_Exotic<public> := class<final><concrete>(entity):


    MarksmanSixShooter_BR_CH2S6_Exotic<public> := class<final><concrete>(entity):


    MavenAutoShotgun_BR_CH4S1_Common<public> := class<final><concrete>(entity):


    MavenAutoShotgun_BR_CH4S1_Uncommon<public> := class<final><concrete>(entity):


    MavenAutoShotgun_BR_CH4S1_Rare<public> := class<final><concrete>(entity):


    MavenAutoShotgun_BR_CH4S1_Epic<public> := class<final><concrete>(entity):


    MavenAutoShotgun_BR_CH4S1_Legendary<public> := class<final><concrete>(entity):


    HeistedAccelerantShotgun_BR_CH4S1_Exotic<public> := class<final><concrete>(entity):


    MechanicalBow_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    MechanicalExplosiveBow_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    MechanicalExplosiveBow_BR_CH2S6_Epic<public> := class<final><concrete>(entity):


    MechanicalExplosiveBow_BR_CH2S6_Legendary<public> := class<final><concrete>(entity):


    RazsExplosiveBow_BR_CH2S6_Mythic<public> := class<final><concrete>(entity):


    MechanicalShockwaveBow_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    MechanicalShockwaveBow_BR_CH2S6_Epic<public> := class<final><concrete>(entity):


    MechanicalShockwaveBow_BR_CH2S6_Legendary<public> := class<final><concrete>(entity):


    MeowsclesPeowPeowRifle_BR_CH2S2_Mythic<public> := class<final><concrete>(entity):


    Minigun_BR_CH1S2_Epic<public> := class<final><concrete>(entity):


    Minigun_BR_CH1S2_Legendary<public> := class<final><concrete>(entity):


    BrutusMinigun_BR_CH2S2_Mythic<public> := class<final><concrete>(entity):


    Minigun_BR_CH5S3_Rare<public> := class<final><concrete>(entity):


    MKAlphaAssaultRifle_BR_CH4S2_Common<public> := class<final><concrete>(entity):


    MKAlphaAssaultRifle_BR_CH4S2_Uncommon<public> := class<final><concrete>(entity):


    MKAlphaAssaultRifle_BR_CH4S2_Rare<public> := class<final><concrete>(entity):


    MKAlphaAssaultRifle_BR_CH4S2_Epic<public> := class<final><concrete>(entity):


    MKAlphaAssaultRifle_BR_CH4S2_Legendary<public> := class<final><concrete>(entity):


    MKSevenAssaultRifle_BR_CH3S1_Common<public> := class<final><concrete>(entity):


    MKSevenAssaultRifle_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    MKSevenAssaultRifle_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    MKSevenAssaultRifle_BR_CH3S1_Epic<public> := class<final><concrete>(entity):


    MKSevenAssaultRifle_BR_CH3S1_Legendary<public> := class<final><concrete>(entity):


    ReliksMKAlphaAssaultRifle_BR_CH4S2_Mythic<public> := class<final><concrete>(entity):


    TheFoundationsMKSevenAssaultRifle_BR_CH3S1_Mythic<public> := class<final><concrete>(entity):


    ModularMonarchPistol_BR_CH5S4_Common<public> := class<final><concrete>(entity):


    ModularMonarchPistol_BR_CH5S4_Uncommon<public> := class<final><concrete>(entity):


    ModularMonarchPistol_BR_CH5S4_Rare<public> := class<final><concrete>(entity):


    ModularMonarchPistol_BR_CH5S4_Epic<public> := class<final><concrete>(entity):


    ModularMonarchPistol_BR_CH5S4_Legendary<public> := class<final><concrete>(entity):


    MystGauntlets_BR_CH6S3_Epic<public> := class<final><concrete>(entity):


    ModularNemesisAR_BR_CH5S1_Common<public> := class<final><concrete>(entity):


    ModularNemesisAR_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    ModularNemesisAR_BR_CH5S1_Rare<public> := class<final><concrete>(entity):


    ModularNemesisAR_BR_CH5S1_Epic<public> := class<final><concrete>(entity):


    ModularNemesisAR_BR_CH5S1_Legendary<public> := class<final><concrete>(entity):


    MontaguesModularNemesisAR_BR_CH5S1_Mythic<public> := class<final><concrete>(entity):


    NemesisAR_BR_CH7S2_Common<public> := class<final><concrete>(entity):


    NemesisAR_BR_CH7S2_Uncommon<public> := class<final><concrete>(entity):


    NemesisAR_BR_CH7S2_Rare<public> := class<final><concrete>(entity):


    NemesisAR_BR_CH7S2_Epic<public> := class<final><concrete>(entity):


    NemesisAR_BR_CH7S2_Legendary<public> := class<final><concrete>(entity):


    NemesisAR_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    NightHawk_BR_CH2S5_Exotic<public> := class<final><concrete>(entity):


    NitroFists_BR_CH5S3_Epic<public> := class<final><concrete>(entity):


    MegaloDonsNitroFists_BR_CH5S3_Mythic<public> := class<final><concrete>(entity):


    OXRRifle_BR_CH6S4_Common<public> := class<final><concrete>(entity):


    OXRRifle_BR_CH6S4_Uncommon<public> := class<final><concrete>(entity):


    OXRRifle_BR_CH6S4_Rare<public> := class<final><concrete>(entity):


    OXRRifle_BR_CH6S4_Epic<public> := class<final><concrete>(entity):


    OXRRifle_BR_CH6S4_Legendary<public> := class<final><concrete>(entity):


    OXRRifle_BR_CH6S4_Mythic<public> := class<final><concrete>(entity):


    OniShotgun_BR_CH6S1_Common<public> := class<final><concrete>(entity):


    OniShotgun_BR_CH6S1_Uncommon<public> := class<final><concrete>(entity):


    OniShotgun_BR_CH6S1_Rare<public> := class<final><concrete>(entity):


    OniShotgun_BR_CH6S1_Epic<public> := class<final><concrete>(entity):


    OniShotgun_BR_CH6S1_Legendary<public> := class<final><concrete>(entity):


    EnhancedOniShotgun_BR_CH6S1_Mythic<public> := class<final><concrete>(entity):


    OrangePaintLauncher_BR_CH2S2_Rare<public> := class<final><concrete>(entity):


    OutlawShotgun_BR_CH6S2_Common<public> := class<final><concrete>(entity):


    OutlawShotgun_BR_CH6S2_Uncommon<public> := class<final><concrete>(entity):


    OutlawShotgun_BR_CH6S2_Rare<public> := class<final><concrete>(entity):


    OutlawShotgun_BR_CH6S2_Epic<public> := class<final><concrete>(entity):


    OutlawShotgun_BR_CH6S2_Legendary<public> := class<final><concrete>(entity):


    EnhancedOutlawShotgun_BR_CH6S2_Mythic<public> := class<final><concrete>(entity):


    UnstableYoinkShotgun_BR_CH6S3_Exotic<public> := class<final><concrete>(entity):


    EradicatorOXRRifle_BR_CH6S4_Exotic<public> := class<final><concrete>(entity):


    Pistol_BR_CH4MS1_Common<public> := class<final><concrete>(entity):


    Pistol_BR_CH4MS1_Uncommon<public> := class<final><concrete>(entity):


    Pistol_BR_CH4MS1_Rare<public> := class<final><concrete>(entity):


    Pistol_BR_CH7S2_Common<public> := class<final><concrete>(entity):


    Pistol_BR_CH7S2_Uncommon<public> := class<final><concrete>(entity):


    Pistol_BR_CH7S2_Rare<public> := class<final><concrete>(entity):


    Pistol_BR_CH7S2_Epic<public> := class<final><concrete>(entity):


    Pistol_BR_CH7S2_Legendary<public> := class<final><concrete>(entity):


    PlasmaBurstLaser_BR_CH6S2_Epic<public> := class<final><concrete>(entity):


    PlasmaCannon_BR_CH2S7_Legendary<public> := class<final><concrete>(entity):


    PrimalBow_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    PrimalFlameBow_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    PrimalFlameBow_BR_CH2S6_Epic<public> := class<final><concrete>(entity):


    PrimalFlameBow_BR_CH2S6_Legendary<public> := class<final><concrete>(entity):


    PrimalPistol_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    PrimalPistol_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    PrimalPistol_BR_CH2S6_Epic<public> := class<final><concrete>(entity):


    PrimalPistol_BR_CH2S6_Legendary<public> := class<final><concrete>(entity):


    PrimalRifle_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    PrimalRifle_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    PrimalRifle_BR_CH2S6_Epic<public> := class<final><concrete>(entity):


    PrimalRifle_BR_CH2S6_Legendary<public> := class<final><concrete>(entity):


    SpireGuardiansPrimalAssaultRifle_BR_CH2S6_Mythic<public> := class<final><concrete>(entity):


    PrimalShotgun_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    PrimalShotgun_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    PrimalShotgun_BR_CH2S6_Epic<public> := class<final><concrete>(entity):


    PrimalShotgun_BR_CH2S6_Legendary<public> := class<final><concrete>(entity):


    SpireAssassinsPrimalShotgun_BR_CH2S6_Mythic<public> := class<final><concrete>(entity):


    PrimalSMG_BR_CH2S6_Uncommon<public> := class<final><concrete>(entity):


    PrimalSMG_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    PrimalSMG_BR_CH2S6_Epic<public> := class<final><concrete>(entity):


    PrimalSMG_BR_CH2S6_Legendary<public> := class<final><concrete>(entity):


    PrimalStinkBow_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    PrimalStinkBow_BR_CH2S6_Epic<public> := class<final><concrete>(entity):


    PrimalStinkBow_BR_CH2S6_Legendary<public> := class<final><concrete>(entity):


    PrimeShotgun_BR_CH3S3_Common<public> := class<final><concrete>(entity):


    PrimeShotgun_BR_CH3S3_Uncommon<public> := class<final><concrete>(entity):


    PrimeShotgun_BR_CH3S3_Rare<public> := class<final><concrete>(entity):


    PrimeShotgun_BR_CH3S3_Epic<public> := class<final><concrete>(entity):


    PrimeShotgun_BR_CH3S3_Legendary<public> := class<final><concrete>(entity):


    PrimeShotgun_BR_CH3S3_Mythic<public> := class<final><concrete>(entity):


    ProximityGrenadeLauncher_BR_CH1S9_Epic<public> := class<final><concrete>(entity):


    ProximityGrenadeLauncher_BR_CH1S9_Legendary<public> := class<final><concrete>(entity):


    PulseRifle_BR_CH2S7_Rare<public> := class<final><concrete>(entity):


    PulseRifle_BR_CH2S7_Epic<public> := class<final><concrete>(entity):


    PulseRifle_BR_CH2S7_Legendary<public> := class<final><concrete>(entity):


    SlonesPulseRifle_BR_CH2S7_Mythic<public> := class<final><concrete>(entity):


    BurstPulseRifle_BR_CH2S7_Exotic<public> := class<final><concrete>(entity):


    OverclockedPulseRifle_BR_CH4S2_Mythic<public> := class<final><concrete>(entity):


    PulseRifle_BR_CH7S2_Uncommon<public> := class<final><concrete>(entity):


    OverdrivePulseRifle_BR_CH7S2_Exotic<public> := class<final><concrete>(entity):


    PumpDump_BR_CH6S2_Common<public> := class<final><concrete>(entity):


    PumpDump_BR_CH6S2_Uncommon<public> := class<final><concrete>(entity):


    PumpDump_BR_CH6S2_Rare<public> := class<final><concrete>(entity):


    PumpDump_BR_CH6S2_Epic<public> := class<final><concrete>(entity):


    PumpDump_BR_CH6S2_Legendary<public> := class<final><concrete>(entity):


    PumpDump_BR_CH6S2_Mythic<public> := class<final><concrete>(entity):


    LawlessBlinkPumpDump_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    PumpkinLauncher_BR_CH1S1_Rare<public> := class<final><concrete>(entity):


    PumpkinLauncher_BR_CH1S1_Epic<public> := class<final><concrete>(entity):


    PumpkinLauncher_BR_CH1S1_Legendary<public> := class<final><concrete>(entity):


    PumpkinLauncher_BR_CH2S1_Uncommon<public> := class<final><concrete>(entity):


    PumpkinLauncher_BR_CH6S4_Rare<public> := class<final><concrete>(entity):


    PumpkinLauncher_BR_CH6S4_Epic<public> := class<final><concrete>(entity):


    PumpkinLauncher_BR_CH6S4_Legendary<public> := class<final><concrete>(entity):


    PumpShotgun_BR_PreSeason_Uncommon<public> := class<final><concrete>(entity):


    PumpShotgun_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    PumpShotgun_BR_CH1S6_Epic<public> := class<final><concrete>(entity):


    PumpShotgun_BR_CH1S6_Legendary<public> := class<final><concrete>(entity):


    PumpShotgun_BR_CH2S1_Common<public> := class<final><concrete>(entity):


    PumpShotgun_BR_CH4MS1_Common<public> := class<final><concrete>(entity):


    PumpShotgun_BR_CH4MS1_Uncommon<public> := class<final><concrete>(entity):


    PumpShotgun_BR_CH4MS1_Rare<public> := class<final><concrete>(entity):


    PumpShotgun_BR_CH4MS1_Epic<public> := class<final><concrete>(entity):


    PumpShotgun_BR_CH4MS1_Legendary<public> := class<final><concrete>(entity):


    PurplePaintLauncher_BR_CH2S2_Rare<public> := class<final><concrete>(entity):


    QuadLauncher_BR_CH1S6_Epic<public> := class<final><concrete>(entity):


    QuadLauncher_BR_CH1S6_Legendary<public> := class<final><concrete>(entity):


    RailGun_BR_CH2S7_Rare<public> := class<final><concrete>(entity):


    RailGun_BR_CH2S7_Epic<public> := class<final><concrete>(entity):


    RailGun_BR_CH2S7_Legendary<public> := class<final><concrete>(entity):


    RangerAssaultRifle_BR_CH3S1_Common<public> := class<final><concrete>(entity):


    RangerAssaultRifle_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    RangerAssaultRifle_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    RangerAssaultRifle_BR_CH3S1_Epic<public> := class<final><concrete>(entity):


    RangerAssaultRifle_BR_CH3S1_Legendary<public> := class<final><concrete>(entity):


    RangerAssaultRifle_BR_CH3S1_Mythic<public> := class<final><concrete>(entity):


    ModularRangerPistol_BR_CH5S1_Common<public> := class<final><concrete>(entity):


    ModularRangerPistol_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    ModularRangerPistol_BR_CH5S1_Rare<public> := class<final><concrete>(entity):


    ModularRangerPistol_BR_CH5S1_Epic<public> := class<final><concrete>(entity):


    ModularRangerPistol_BR_CH5S1_Legendary<public> := class<final><concrete>(entity):


    RangerPistol_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    RangerShotgun_BR_CH3S2_Common<public> := class<final><concrete>(entity):


    RangerShotgun_BR_CH3S2_Uncommon<public> := class<final><concrete>(entity):


    RangerShotgun_BR_CH3S2_Rare<public> := class<final><concrete>(entity):


    RangerShotgun_BR_CH3S2_Epic<public> := class<final><concrete>(entity):


    RangerShotgun_BR_CH3S2_Legendary<public> := class<final><concrete>(entity):


    RapidFireSMG_BR_CH2S2_Uncommon<public> := class<final><concrete>(entity):


    RapidFireSMG_BR_CH2S2_Rare<public> := class<final><concrete>(entity):


    RapidFireSMG_BR_CH2S3_Common<public> := class<final><concrete>(entity):


    RapidFireSMG_BR_CH2S3_Epic<public> := class<final><concrete>(entity):


    RapidFireSMG_BR_CH2S3_Legendary<public> := class<final><concrete>(entity):


    RapidFireSMG_BR_CH3S4_Mythic<public> := class<final><concrete>(entity):


    ReacherExtendingShotgun_BR_CH7S3_Mythic<public> := class<final><concrete>(entity):


    ReaperModularSniperRifle_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    ReaperModularSniperRifle_BR_CH5S1_Rare<public> := class<final><concrete>(entity):


    ReaperModularSniperRifle_BR_CH5S1_Epic<public> := class<final><concrete>(entity):


    ReaperModularSniperRifle_BR_CH5S1_Legendary<public> := class<final><concrete>(entity):


    ReaperSniperRifle_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    ExoticReconBow_BR_CH7S2_Exotic<public> := class<final><concrete>(entity):


    ReconScanner_BR_CH2S7_Rare<public> := class<final><concrete>(entity):


    Recycler_BR_CH2S6_Rare<public> := class<final><concrete>(entity):


    Recycler_BR_CH2S6_Epic<public> := class<final><concrete>(entity):


    Recycler_BR_CH2S6_Legendary<public> := class<final><concrete>(entity):


    SpireAssassinsRecycler_BR_CH2S6_Mythic<public> := class<final><concrete>(entity):


    RedEyeAssaultRifle_BR_CH4S1_Common<public> := class<final><concrete>(entity):


    RedEyeAssaultRifle_BR_CH4S1_Uncommon<public> := class<final><concrete>(entity):


    RedEyeAssaultRifle_BR_CH4S1_Rare<public> := class<final><concrete>(entity):


    RedEyeAssaultRifle_BR_CH4S1_Epic<public> := class<final><concrete>(entity):


    RedEyeAssaultRifle_BR_CH4S1_Legendary<public> := class<final><concrete>(entity):


    HeistedExplosiveAssaultRifle_BR_CH4S1_Exotic<public> := class<final><concrete>(entity):


    Revolver_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    Revolver_BR_PreSeason_Uncommon<public> := class<final><concrete>(entity):


    Revolver_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    Revolver_BR_CH1S9_Epic<public> := class<final><concrete>(entity):


    Revolver_BR_CH1S9_Legendary<public> := class<final><concrete>(entity):


    Revolver_OG_CH1S1_Common<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use Revolver_OG_CH1S1_Common instead.
    Revolver_BR_CH4MS1_Common<public> := class<final><concrete>(entity):


    Revolver_OG_CH1S1_Uncommon<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use Revolver_OG_CH1S1_Uncommon instead.
    Revolver_BR_CH4MS1_Uncommon<public> := class<final><concrete>(entity):


    Revolver_OG_CH1S1_Rare<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use Revolver_OG_CH1S1_Rare instead.
    Revolver_BR_CH4MS1_Rare<public> := class<final><concrete>(entity):


    Revolver_OG_CH1S1_Epic<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use Revolver_OG_CH1S1_Epic instead.
    Revolver_BR_CH4MS1_Epic<public> := class<final><concrete>(entity):


    Revolver_OG_CH1S1_Legendary<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use Revolver_OG_CH1S1_Legendary instead.
    Revolver_BR_CH4MS1_Legendary<public> := class<final><concrete>(entity):


    RipsawLauncher_BR_CH3S3_Rare<public> := class<final><concrete>(entity):


    RocketDrill_BR_CH6S2_Epic<public> := class<final><concrete>(entity):


    RocketLauncher_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    RocketLauncher_BR_PreSeason_Epic<public> := class<final><concrete>(entity):


    RocketLauncher_BR_PreSeason_Legendary<public> := class<final><concrete>(entity):


    RocketLauncher_BR_CH2S1_Common<public> := class<final><concrete>(entity):


    RocketLauncher_BR_CH2S1_Uncommon<public> := class<final><concrete>(entity):


    RocketRam_BR_CH4S4_Rare<public> := class<final><concrete>(entity):


    ScopedAssaultRifle_BR_PreSeason_Uncommon<public> := class<final><concrete>(entity):


    ScopedAssaultRifle_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    ScopedAssaultRifle_BR_CH2S4_Epic<public> := class<final><concrete>(entity):


    ScopedAssaultRifle_BR_CH2S4_Legendary<public> := class<final><concrete>(entity):


    ScopedBurstSMG_BR_CH4S4_Common<public> := class<final><concrete>(entity):


    ScopedBurstSMG_BR_CH4S4_Uncommon<public> := class<final><concrete>(entity):


    ScopedBurstSMG_BR_CH4S4_Rare<public> := class<final><concrete>(entity):


    ScopedBurstSMG_BR_CH4S4_Epic<public> := class<final><concrete>(entity):


    ScopedBurstSMG_BR_CH4S4_Legendary<public> := class<final><concrete>(entity):


    ThornesScopedBurstSMG_BR_CH4S4_Mythic<public> := class<final><concrete>(entity):


    ScopedRevolver_BR_CH1S7_Epic<public> := class<final><concrete>(entity):


    ScopedRevolver_BR_CH1S7_Legendary<public> := class<final><concrete>(entity):


    SemiAutoPistol_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    SemiAutoPistol_BR_PreSeason_Uncommon<public> := class<final><concrete>(entity):


    SemiAutoPistol_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    SemiAutoPistol_BR_CH2S1_Epic<public> := class<final><concrete>(entity):


    SemiAutoPistol_BR_CH2S1_Legendary<public> := class<final><concrete>(entity):


    SemiAutoSniperRifle_BR_PreSeason_Uncommon<public> := class<final><concrete>(entity):


    SemiAutoSniperRifle_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    SemiAutoSniperRifle_BR_CH2S2_Epic<public> := class<final><concrete>(entity):


    SemiAutoSniperRifle_BR_CH2S2_Legendary<public> := class<final><concrete>(entity):


    SemiAutoSuppressedPistol_BR_CH1S2_Rare<public> := class<final><concrete>(entity):


    SemiAutoSuppressedPistol_BR_CH1S2_Epic<public> := class<final><concrete>(entity):


    SemiAutoSuppressedPistol_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    SemiAutoSuppressedPistol_BR_CH3S1_Legendary<public> := class<final><concrete>(entity):


    SentinelPumpShotgun_BR_CH6S1_Common<public> := class<final><concrete>(entity):


    SentinelPumpShotgun_BR_CH6S1_Uncommon<public> := class<final><concrete>(entity):


    SentinelPumpShotgun_BR_CH6S1_Rare<public> := class<final><concrete>(entity):


    SentinelPumpShotgun_BR_CH6S1_Epic<public> := class<final><concrete>(entity):


    SentinelPumpShotgun_BR_CH6S1_Legendary<public> := class<final><concrete>(entity):


    EnhancedSentinelPumpShotgun_BR_CH6S1_Mythic<public> := class<final><concrete>(entity):


    SevenClusterCannon_BR_CH7S2_Epic<public> := class<final><concrete>(entity):


    SevenClusterCannon_BR_CH7S2_Legendary<public> := class<final><concrete>(entity):


    SevenPowerGloves_BR_CH7S2_Epic<public> := class<final><concrete>(entity):


    FoundationsPowerGloves_BR_CH7S2_Mythic<public> := class<final><concrete>(entity):


    ShadowTracker_BR_CH2S5_Exotic<public> := class<final><concrete>(entity):


    SharpToothShotgun_BR_CH4S3_Uncommon<public> := class<final><concrete>(entity):


    SharpToothShotgun_BR_CH4S3_Rare<public> := class<final><concrete>(entity):


    SharpToothShotgun_BR_CH4S3_Epic<public> := class<final><concrete>(entity):


    SharpToothShotgun_BR_CH4S3_Legendary<public> := class<final><concrete>(entity):


    ShockwaveHammer_BR_CH4S1_Epic<public> := class<final><concrete>(entity):


    TheAgelessChampionsShockwaveHammer_BR_CH4S1_Mythic<public> := class<final><concrete>(entity):


    KitsShockwaveLauncher_BR_CH2S3_Mythic<public> := class<final><concrete>(entity):


    ShockwaveLauncher_BR_CH2S8_Legendary<public> := class<final><concrete>(entity):


    ShockwaveLauncher_BR_CH6S4_Epic<public> := class<final><concrete>(entity):


    EradicatorShockNSlowShockwaveLauncher_BR_CH6S4_Exotic<public> := class<final><concrete>(entity):


    SidearmPistol_BR_CH3S1_Common<public> := class<final><concrete>(entity):


    SidearmPistol_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    SidearmPistol_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    SidearmPistol_BR_CH3S1_Epic<public> := class<final><concrete>(entity):


    SidearmPistol_BR_CH3S1_Legendary<public> := class<final><concrete>(entity):


    SidewaysMinigun_BR_CH2S8_Common<public> := class<final><concrete>(entity):


    SidewaysMinigun_BR_CH2S8_Uncommon<public> := class<final><concrete>(entity):


    SidewaysMinigun_BR_CH2S8_Rare<public> := class<final><concrete>(entity):


    SidewaysMinigun_BR_CH2S8_Epic<public> := class<final><concrete>(entity):


    SidewaysMinigun_BR_CH2S8_Legendary<public> := class<final><concrete>(entity):


    SidewaysMinigun_BR_CH2S8_Mythic<public> := class<final><concrete>(entity):


    SidewaysRifle_BR_CH2S8_Common<public> := class<final><concrete>(entity):


    SidewaysRifle_BR_CH2S8_Uncommon<public> := class<final><concrete>(entity):


    SidewaysRifle_BR_CH2S8_Rare<public> := class<final><concrete>(entity):


    SidewaysRifle_BR_CH2S8_Epic<public> := class<final><concrete>(entity):


    SidewaysRifle_BR_CH2S8_Legendary<public> := class<final><concrete>(entity):


    SidewaysRifle_BR_CH2S8_Mythic<public> := class<final><concrete>(entity):


    SidewaysScythe_BR_CH2S8_Common<public> := class<final><concrete>(entity):


    SidewaysScythe_BR_CH2S8_Uncommon<public> := class<final><concrete>(entity):


    SidewaysScythe_BR_CH2S8_Rare<public> := class<final><concrete>(entity):


    SidewaysScythe_BR_CH2S8_Epic<public> := class<final><concrete>(entity):


    SidewaysScythe_BR_CH2S8_Legendary<public> := class<final><concrete>(entity):


    SidewaysScythe_BR_CH2S8_Mythic<public> := class<final><concrete>(entity):


    SixShooter_BR_CH1S6_Uncommon<public> := class<final><concrete>(entity):


    SixShooter_BR_CH1S6_Rare<public> := class<final><concrete>(entity):


    SixShooter_BR_CH1S6_Epic<public> := class<final><concrete>(entity):


    SixShooter_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    SnowballLauncher_BR_CH1S2_Rare<public> := class<final><concrete>(entity):


    SnowballLauncher_BR_CH1S2_Epic<public> := class<final><concrete>(entity):


    SnowballLauncher_BR_CH1S2_Legendary<public> := class<final><concrete>(entity):


    SnowballLauncher_BR_CH2S1_Uncommon<public> := class<final><concrete>(entity):


    ModularSovereignShotgun_BR_CH5S4_Common<public> := class<final><concrete>(entity):


    ModularSovereignShotgun_BR_CH5S4_Uncommon<public> := class<final><concrete>(entity):


    ModularSovereignShotgun_BR_CH5S4_Rare<public> := class<final><concrete>(entity):


    ModularSovereignShotgun_BR_CH5S4_Epic<public> := class<final><concrete>(entity):


    ModularSovereignShotgun_BR_CH5S4_Legendary<public> := class<final><concrete>(entity):


    SovereignShotgun_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    SovereignShotgun_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    SovereignShotgun_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    SovereignShotgun_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    SovereignShotgun_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    SovereignSniper_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    SpireRifle_BR_CH6S3_Common<public> := class<final><concrete>(entity):


    SpireRifle_BR_CH6S3_Uncommon<public> := class<final><concrete>(entity):


    SpireRifle_BR_CH6S3_Rare<public> := class<final><concrete>(entity):


    SpireRifle_BR_CH6S3_Epic<public> := class<final><concrete>(entity):


    SpireRifle_BR_CH6S3_Legendary<public> := class<final><concrete>(entity):


    EnhancedSpireRifle_BR_CH6S3_Mythic<public> := class<final><concrete>(entity):


    StickyGrenadeLauncher_BR_CH4S4_Epic<public> := class<final><concrete>(entity):


    StickyGrenadeLauncher_BR_CH4S4_Legendary<public> := class<final><concrete>(entity):


    StingerSMG_BR_CH3S1_Common<public> := class<final><concrete>(entity):


    StingerSMG_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    StingerSMG_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    StingerSMG_BR_CH3S1_Epic<public> := class<final><concrete>(entity):


    StingerSMG_BR_CH3S1_Legendary<public> := class<final><concrete>(entity):


    GunnarsStingerSMG_BR_CH3S1_Mythic<public> := class<final><concrete>(entity):


    StormScout_BR_CH2S5_Exotic<public> := class<final><concrete>(entity):


    StormScoutSniperRifle_BR_CH1S9_Epic<public> := class<final><concrete>(entity):


    StormScoutSniperRifle_BR_CH1S9_Legendary<public> := class<final><concrete>(entity):


    ModularStrikerAR_BR_CH5S1_Common<public> := class<final><concrete>(entity):


    ModularStrikerAR_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    ModularStrikerAR_BR_CH5S1_Rare<public> := class<final><concrete>(entity):


    ModularStrikerAR_BR_CH5S1_Epic<public> := class<final><concrete>(entity):


    ModularStrikerAR_BR_CH5S1_Legendary<public> := class<final><concrete>(entity):


    NishasModularStrikerAR_BR_CH5S1_Mythic<public> := class<final><concrete>(entity):


    StrikerAR_BR_CH6MS2_Common<public> := class<final><concrete>(entity):


    StrikerAR_BR_CH6MS2_Uncommon<public> := class<final><concrete>(entity):


    StrikerAR_BR_CH6MS2_Rare<public> := class<final><concrete>(entity):


    StrikerAR_BR_CH6MS2_Epic<public> := class<final><concrete>(entity):


    StrikerAR_BR_CH6MS2_Legendary<public> := class<final><concrete>(entity):


    StrikerAR_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    StrikerBurstRifle_BR_CH3S2_Common<public> := class<final><concrete>(entity):


    StrikerBurstRifle_BR_CH3S2_Uncommon<public> := class<final><concrete>(entity):


    StrikerBurstRifle_BR_CH3S2_Rare<public> := class<final><concrete>(entity):


    StrikerBurstRifle_BR_CH3S2_Epic<public> := class<final><concrete>(entity):


    StrikerBurstRifle_BR_CH3S2_Legendary<public> := class<final><concrete>(entity):


    StrikerBurstRifle_BR_CH3S2_Mythic<public> := class<final><concrete>(entity):


    SlonesStrikerBurstRifle_BR_CH3S2_Mythic<public> := class<final><concrete>(entity):


    ModularStrikerBurstRifle_BR_CH5S4_Common<public> := class<final><concrete>(entity):


    ModularStrikerBurstRifle_BR_CH5S4_Uncommon<public> := class<final><concrete>(entity):


    ModularStrikerBurstRifle_BR_CH5S4_Rare<public> := class<final><concrete>(entity):


    ModularStrikerBurstRifle_BR_CH5S4_Epic<public> := class<final><concrete>(entity):


    ModularStrikerBurstRifle_BR_CH5S4_Legendary<public> := class<final><concrete>(entity):


    StrikerPumpShotgun_BR_CH3S1_Common<public> := class<final><concrete>(entity):


    StrikerPumpShotgun_BR_CH3S1_Uncommon<public> := class<final><concrete>(entity):


    StrikerPumpShotgun_BR_CH3S1_Rare<public> := class<final><concrete>(entity):


    StrikerPumpShotgun_BR_CH3S1_Epic<public> := class<final><concrete>(entity):


    StrikerPumpShotgun_BR_CH3S1_Legendary<public> := class<final><concrete>(entity):


    StrikerPumpShotgun_BR_CH3S1_Mythic<public> := class<final><concrete>(entity):


    SubmachineGun_BR_CH1S5_Common<public> := class<final><concrete>(entity):


    SubmachineGun_BR_CH1S5_Uncommon<public> := class<final><concrete>(entity):


    SubmachineGun_BR_CH1S5_Rare<public> := class<final><concrete>(entity):


    SubmachineGun_BR_CH2S1_Epic<public> := class<final><concrete>(entity):


    SubmachineGun_BR_CH2S1_Legendary<public> := class<final><concrete>(entity):


    HeistedRunNGunSMG_BR_CH4S1_Exotic<public> := class<final><concrete>(entity):


    SubmachineGun_BR_CH4S2_Epic<public> := class<final><concrete>(entity):


    SubmachineGun_BR_CH4S2_Legendary<public> := class<final><concrete>(entity):


    SubmachineGun_OG_CH1S1_Common<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use SubmachineGun_OG_CH1S1_Common instead.
    SubmachineGun_BR_CH4MS1_Common<public> := class<final><concrete>(entity):


    SubmachineGun_OG_CH1S1_Uncommon<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use SubmachineGun_OG_CH1S1_Uncommon instead.
    SubmachineGun_BR_CH4MS1_Uncommon<public> := class<final><concrete>(entity):


    SubmachineGun_OG_CH1S1_Rare<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use SubmachineGun_OG_CH1S1_Rare instead.
    SubmachineGun_BR_CH4MS1_Rare<public> := class<final><concrete>(entity):


    SuperShredder_BR_CH7S2_Rare<public> := class<final><concrete>(entity):


    SuperShredder_BR_CH7S2_Epic<public> := class<final><concrete>(entity):


    SuperShredder_BR_CH7S2_Legendary<public> := class<final><concrete>(entity):


    SuppressedAssaultRifle_BR_CH1S5_Epic<public> := class<final><concrete>(entity):


    SuppressedAssaultRifle_BR_CH1S5_Legendary<public> := class<final><concrete>(entity):


    SuppressedAssaultRifle_BR_CH2S2_Rare<public> := class<final><concrete>(entity):


    SuppressedAssaultRifle_BR_CH6MS2_Common<public> := class<final><concrete>(entity):


    SuppressedAssaultRifle_BR_CH6MS2_Uncommon<public> := class<final><concrete>(entity):


    SuppressedPistol_BR_CH4S4_Common<public> := class<final><concrete>(entity):


    SuppressedPistol_BR_CH4S4_Uncommon<public> := class<final><concrete>(entity):


    SuppressedPistol_BR_CH4S4_Rare<public> := class<final><concrete>(entity):


    SuppressedPistol_BR_CH4S4_Epic<public> := class<final><concrete>(entity):


    SuppressedPistol_BR_CH4S4_Legendary<public> := class<final><concrete>(entity):


    SuppressedPistol_BR_CH6S2_Mythic<public> := class<final><concrete>(entity):


    SuppressedSniperRifle_BR_CH1S7_Epic<public> := class<final><concrete>(entity):


    SuppressedSniperRifle_BR_CH1S7_Legendary<public> := class<final><concrete>(entity):


    SuppressedSniperRifle_BR_CH2S2_Rare<public> := class<final><concrete>(entity):


    SuppressedSubmachineGun_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    SuppressedSubmachineGun_BR_PreSeason_Uncommon<public> := class<final><concrete>(entity):


    SuppressedSubmachineGun_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    SuppressedSubmachineGun_BR_CH3S4_Epic<public> := class<final><concrete>(entity):


    SuppressedSubmachineGun_BR_CH3S4_Legendary<public> := class<final><concrete>(entity):


    InkquisitorsSuppressedSMG_BR_CH3S4_Mythic<public> := class<final><concrete>(entity):


    SurgefireSMG_BR_CH6S1_Common<public> := class<final><concrete>(entity):


    SurgefireSMG_BR_CH6S1_Uncommon<public> := class<final><concrete>(entity):


    SurgefireSMG_BR_CH6S1_Rare<public> := class<final><concrete>(entity):


    SurgefireSMG_BR_CH6S1_Epic<public> := class<final><concrete>(entity):


    SurgefireSMG_BR_CH6S1_Legendary<public> := class<final><concrete>(entity):


    EnhancedSurgefireSMG_BR_CH6S1_Mythic<public> := class<final><concrete>(entity):


    VanguardBurstRifle_BR_CH7S3_Common<public> := class<final><concrete>(entity):


    VanguardBurstRifle_BR_CH7S3_Uncommon<public> := class<final><concrete>(entity):


    VanguardBurstRifle_BR_CH7S3_Rare<public> := class<final><concrete>(entity):


    VanguardBurstRifle_BR_CH7S3_Epic<public> := class<final><concrete>(entity):


    VanguardBurstRifle_BR_CH7S3_Legendary<public> := class<final><concrete>(entity):


    Swarmstrike_BR_CH6S4_Epic<public> := class<final><concrete>(entity):


    Swarmstrike_BR_CH6S4_Legendary<public> := class<final><concrete>(entity):


    SweeperShotgun_BR_CH6S4_Common<public> := class<final><concrete>(entity):


    SweeperShotgun_BR_CH6S4_Uncommon<public> := class<final><concrete>(entity):


    SweeperShotgun_BR_CH6S4_Rare<public> := class<final><concrete>(entity):


    SweeperShotgun_BR_CH6S4_Epic<public> := class<final><concrete>(entity):


    SweeperShotgun_BR_CH6S4_Legendary<public> := class<final><concrete>(entity):


    SweeperShotgun_BR_CH6S4_Mythic<public> := class<final><concrete>(entity):


    TacticalAssaultRifle_BR_CH1S9_Rare<public> := class<final><concrete>(entity):


    TacticalAssaultRifle_BR_CH1S9_Epic<public> := class<final><concrete>(entity):


    TacticalAssaultRifle_BR_CH1S9_Legendary<public> := class<final><concrete>(entity):


    TacticalAssaultRifle_BR_CH4S1_Common<public> := class<final><concrete>(entity):


    TacticalAssaultRifle_BR_CH4S1_Uncommon<public> := class<final><concrete>(entity):


    ModularTacticalAssaultRifle_BR_CH5S2_Common<public> := class<final><concrete>(entity):


    ModularTacticalAssaultRifle_BR_CH5S2_Uncommon<public> := class<final><concrete>(entity):


    ModularTacticalAssaultRifle_BR_CH5S2_Rare<public> := class<final><concrete>(entity):


    ModularTacticalAssaultRifle_BR_CH5S2_Epic<public> := class<final><concrete>(entity):


    ModularTacticalAssaultRifle_BR_CH5S2_Legendary<public> := class<final><concrete>(entity):


    TacticalAssaultRifle_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    TacticalAssaultRifle_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    TacticalAssaultRifle_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    TacticalAssaultRifle_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    TacticalAssaultRifle_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    TacticalDMR_BR_CH4S4_Common<public> := class<final><concrete>(entity):


    TacticalDMR_BR_CH4S4_Uncommon<public> := class<final><concrete>(entity):


    TacticalDMR_BR_CH4S4_Rare<public> := class<final><concrete>(entity):


    TacticalDMR_BR_CH4S4_Epic<public> := class<final><concrete>(entity):


    TacticalDMR_BR_CH4S4_Legendary<public> := class<final><concrete>(entity):


    TacticalPistol_BR_CH4S1_Common<public> := class<final><concrete>(entity):


    TacticalPistol_BR_CH4S1_Uncommon<public> := class<final><concrete>(entity):


    TacticalPistol_BR_CH4S1_Rare<public> := class<final><concrete>(entity):


    TacticalPistol_BR_CH4S1_Epic<public> := class<final><concrete>(entity):


    TacticalPistol_BR_CH4S1_Legendary<public> := class<final><concrete>(entity):


    TacticalPistol_BR_CH4S1_Mythic<public> := class<final><concrete>(entity):


    TacticalPistol_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    TacticalPistol_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    TacticalPistol_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    TacticalPistol_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    TacticalPistol_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    OverdriveTacticalPistol_BR_CH7S1_Mythic<public> := class<final><concrete>(entity):


    TacticalShotgun_BR_PreSeason_Common<public> := class<final><concrete>(entity):


    TacticalShotgun_BR_PreSeason_Uncommon<public> := class<final><concrete>(entity):


    TacticalShotgun_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    TacticalShotgun_BR_CH1S9_Epic<public> := class<final><concrete>(entity):


    TacticalShotgun_BR_CH1S9_Legendary<public> := class<final><concrete>(entity):


    TacticalShotgun_BR_CH6MS2_Epic<public> := class<final><concrete>(entity):


    TacticalShotgun_BR_CH6MS2_Legendary<public> := class<final><concrete>(entity):


    TacticalSubmachineGun_BR_PreSeason_Uncommon<public> := class<final><concrete>(entity):


    TacticalSubmachineGun_BR_PreSeason_Rare<public> := class<final><concrete>(entity):


    TacticalSubmachineGun_BR_PreSeason_Epic<public> := class<final><concrete>(entity):


    TacticalSubmachineGun_BR_CH1SX_Legendary<public> := class<final><concrete>(entity):


    TheBigChill_BR_CH2S5_Exotic<public> := class<final><concrete>(entity):


    TheDub_BR_CH2S5_Exotic<public> := class<final><concrete>(entity):


    TheFoundationsRiftRifle_BR_CH7S2_Exotic<public> := class<final><concrete>(entity):


    TheKneecapper_BR_CH6S2_Epic<public> := class<final><concrete>(entity):


    ThermalDMR_BR_CH4S3_Common<public> := class<final><concrete>(entity):


    ThermalDMR_BR_CH4S3_Uncommon<public> := class<final><concrete>(entity):


    ThermalDMR_BR_CH4S3_Rare<public> := class<final><concrete>(entity):


    ThermalDMR_BR_CH4S3_Epic<public> := class<final><concrete>(entity):


    ThermalDMR_BR_CH4S3_Legendary<public> := class<final><concrete>(entity):


    ThermalDMR_BR_CH4S3_Mythic<public> := class<final><concrete>(entity):


    DiamondsThermalDMR_BR_CH4S4_Mythic<public> := class<final><concrete>(entity):


    ThermalScopedAssaultRifle_BR_CH1S4_Epic<public> := class<final><concrete>(entity):


    ThermalScopedAssaultRifle_BR_CH1S4_Legendary<public> := class<final><concrete>(entity):


    HuntmasterSabersThermalRifle_BR_CH3S2_Mythic<public> := class<final><concrete>(entity):


    TheVoidbladesBurstRifle_BR_CH7S3_Mythic<public> := class<final><concrete>(entity):


    ModularThunderBurstSMG_BR_CH5S1_Common<public> := class<final><concrete>(entity):


    ModularThunderBurstSMG_BR_CH5S1_Uncommon<public> := class<final><concrete>(entity):


    ModularThunderBurstSMG_BR_CH5S1_Rare<public> := class<final><concrete>(entity):


    ModularThunderBurstSMG_BR_CH5S1_Epic<public> := class<final><concrete>(entity):


    ModularThunderBurstSMG_BR_CH5S1_Legendary<public> := class<final><concrete>(entity):


    ThunderBurstSMG_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    ThunderShotgun_BR_CH4S1_Common<public> := class<final><concrete>(entity):


    ThunderShotgun_BR_CH4S1_Uncommon<public> := class<final><concrete>(entity):


    ThunderShotgun_BR_CH4S1_Rare<public> := class<final><concrete>(entity):


    ThunderShotgun_BR_CH4S1_Epic<public> := class<final><concrete>(entity):


    ThunderShotgun_BR_CH4S1_Legendary<public> := class<final><concrete>(entity):


    TNTinasKaBoomBow_BR_CH2S2_Mythic<public> := class<final><concrete>(entity):


    TowHookCannon_BR_CH5S3_Rare<public> := class<final><concrete>(entity):


    Trouble_BR_CH6S4_Exotic<public> := class<final><concrete>(entity):


    TwinfireAutoShotgun_BR_CH6S1_Common<public> := class<final><concrete>(entity):


    TwinfireAutoShotgun_BR_CH6S1_Uncommon<public> := class<final><concrete>(entity):


    TwinfireAutoShotgun_BR_CH6S1_Rare<public> := class<final><concrete>(entity):


    TwinfireAutoShotgun_BR_CH6S1_Epic<public> := class<final><concrete>(entity):


    TwinfireAutoShotgun_BR_CH6S1_Legendary<public> := class<final><concrete>(entity):


    EnhancedTwinfireAutoShotgun_BR_CH6S1_Mythic<public> := class<final><concrete>(entity):


    LawlessTwinfireSlapShotgun_BR_CH6S2_Exotic<public> := class<final><concrete>(entity):


    TwinHammerShotguns_BR_CH7S1_Common<public> := class<final><concrete>(entity):


    TwinHammerShotguns_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    TwinHammerShotguns_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    TwinHammerShotguns_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    TwinHammerShotguns_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    BrutusTwinHammerShotguns_BR_CH7S1_Mythic<public> := class<final><concrete>(entity):


    TwinMagAssaultRifle_BR_CH4S4_Common<public> := class<final><concrete>(entity):


    TwinMagAssaultRifle_BR_CH4S4_Uncommon<public> := class<final><concrete>(entity):


    TwinMagAssaultRifle_BR_CH4S4_Rare<public> := class<final><concrete>(entity):


    TwinMagAssaultRifle_BR_CH4S4_Epic<public> := class<final><concrete>(entity):


    TwinMagAssaultRifle_BR_CH4S4_Legendary<public> := class<final><concrete>(entity):


    TwinMagSMG_BR_CH4S1_Common<public> := class<final><concrete>(entity):


    TwinMagSMG_BR_CH4S1_Uncommon<public> := class<final><concrete>(entity):


    TwinMagSMG_BR_CH4S1_Rare<public> := class<final><concrete>(entity):


    TwinMagSMG_BR_CH4S1_Epic<public> := class<final><concrete>(entity):


    TwinMagSMG_BR_CH4S1_Legendary<public> := class<final><concrete>(entity):


    HeistedBlinkMagSMG_BR_CH4S1_Exotic<public> := class<final><concrete>(entity):


    TwoShotShotgun_BR_CH3S3_Common<public> := class<final><concrete>(entity):


    TwoShotShotgun_BR_CH3S3_Uncommon<public> := class<final><concrete>(entity):


    TwoShotShotgun_BR_CH3S3_Rare<public> := class<final><concrete>(entity):


    TwoShotShotgun_BR_CH3S3_Epic<public> := class<final><concrete>(entity):


    TwoShotShotgun_BR_CH3S3_Legendary<public> := class<final><concrete>(entity):


    TwoShotShotgun_BR_CH3S3_Mythic<public> := class<final><concrete>(entity):


    TyphoonBlade_BR_CH6S1_Epic<public> := class<final><concrete>(entity):


    TyphoonBlade_BR_CH6S1_Mythic<public> := class<final><concrete>(entity):


    UnstableBow_BR_CH2S6_Exotic<public> := class<final><concrete>(entity):


    UnstableFrostfireShotgun_BR_CH6S3_Exotic<public> := class<final><concrete>(entity):


    Vector7DMR_BR_CH7S2_Rare<public> := class<final><concrete>(entity):


    Vector7DMR_BR_CH7S2_Epic<public> := class<final><concrete>(entity):


    Vector7DMR_BR_CH7S2_Legendary<public> := class<final><concrete>(entity):


    VeiledPrecisionSMG_BR_CH6S1_Common<public> := class<final><concrete>(entity):


    VeiledPrecisionSMG_BR_CH6S1_Uncommon<public> := class<final><concrete>(entity):


    VeiledPrecisionSMG_BR_CH6S1_Rare<public> := class<final><concrete>(entity):


    VeiledPrecisionSMG_BR_CH6S1_Epic<public> := class<final><concrete>(entity):


    VeiledPrecisionSMG_BR_CH6S1_Legendary<public> := class<final><concrete>(entity):


    NightRoseVeiledPrecisionSMG_BR_CH6S1_Mythic<public> := class<final><concrete>(entity):


    EradicatorShadowPrecisionSMG_BR_CH6S4_Exotic<public> := class<final><concrete>(entity):


    VeiledPrecisionSMG_Ballistic_V1_Common<public> := class<final><concrete>(entity):


    VengefulSniperRifle_BR_CH7S1_Uncommon<public> := class<final><concrete>(entity):


    VengefulSniperRifle_BR_CH7S1_Rare<public> := class<final><concrete>(entity):


    VengefulSniperRifle_BR_CH7S1_Epic<public> := class<final><concrete>(entity):


    VengefulSniperRifle_BR_CH7S1_Legendary<public> := class<final><concrete>(entity):


    ModularWarforgedAssaultRifle_BR_CH5S2_Common<public> := class<final><concrete>(entity):


    ModularWarforgedAssaultRifle_BR_CH5S2_Uncommon<public> := class<final><concrete>(entity):


    ModularWarforgedAssaultRifle_BR_CH5S2_Rare<public> := class<final><concrete>(entity):


    ModularWarforgedAssaultRifle_BR_CH5S2_Epic<public> := class<final><concrete>(entity):


    ModularWarforgedAssaultRifle_BR_CH5S2_Legendary<public> := class<final><concrete>(entity):


    AresModularWarforgedAssaultRifle_BR_CH5S2_Mythic<public> := class<final><concrete>(entity):


    WoodStakeShotgun_BR_CH4S4_Rare<public> := class<final><concrete>(entity):


    WoodStakeShotgun_BR_CH4S4_Epic<public> := class<final><concrete>(entity):


    WoodStakeShotgun_BR_CH4S4_Legendary<public> := class<final><concrete>(entity):


    HighStakesShotgun_BR_CH4S4_Mythic<public> := class<final><concrete>(entity):


    WreckerRevolver_BR_CH6S4_Common<public> := class<final><concrete>(entity):


    WreckerRevolver_BR_CH6S4_Uncommon<public> := class<final><concrete>(entity):


    WreckerRevolver_BR_CH6S4_Rare<public> := class<final><concrete>(entity):


    WreckerRevolver_BR_CH6S4_Epic<public> := class<final><concrete>(entity):


    WreckerRevolver_BR_CH6S4_Legendary<public> := class<final><concrete>(entity):


    EnhancedWreckerRevolver_BR_CH6S4_Mythic<public> := class<final><concrete>(entity):


    EradicatorMarksmanWreckerRevolver_BR_CH6S4_Exotic<public> := class<final><concrete>(entity):


    Zapotron_OG_CH1S2_Legendary<public> := class<final><concrete>(entity):


    @deprecated
    # Deprecated. Please use Zapotron_OG_CH1S2_Legendary instead.
    Zapotron_OG_CH1S1_Legendary<public> := class<final><concrete>(entity):
